package certs

import (
	"fmt"
	"net/url"

	mdbv1 "github.com/10gen/ops-manager-kubernetes/api/v1/mdb"
	"github.com/hashicorp/go-multierror"
	mdbcv1 "github.com/mongodb/mongodb-kubernetes-operator/api/v1"

	"github.com/10gen/ops-manager-kubernetes/controllers/operator/secrets"
	"github.com/10gen/ops-manager-kubernetes/controllers/operator/workflow"
	"go.uber.org/zap"

	enterprisepem "github.com/10gen/ops-manager-kubernetes/controllers/operator/pem"
	"github.com/10gen/ops-manager-kubernetes/pkg/dns"
	"github.com/10gen/ops-manager-kubernetes/pkg/kube"
	"github.com/10gen/ops-manager-kubernetes/pkg/multicluster"
	"github.com/10gen/ops-manager-kubernetes/pkg/util"
	"github.com/10gen/ops-manager-kubernetes/pkg/vault"

	"github.com/mongodb/mongodb-kubernetes-operator/pkg/kube/secret"
	corev1 "k8s.io/api/core/v1"

	"github.com/10gen/ops-manager-kubernetes/pkg/util/stringutil"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
)

type certDestination string

const (
	OperatorGeneratedCertSuffix = "-pem"
	CertHashAnnotationkey       = "certHash"

	Unused     = "unused"
	Database   = "database"
	OpsManager = "opsmanager"
	AppDB      = "appdb"
)

// CreatePEMSecretClient creates a PEM secret from the original secretName.
func CreatePEMSecretClient(secretClient secrets.SecretClient, secretNamespacedName types.NamespacedName, data map[string]string, ownerReferences []metav1.OwnerReference, podType certDestination, log *zap.SugaredLogger) error {
	operatorGeneratedSecret := secretNamespacedName
	operatorGeneratedSecret.Name = fmt.Sprintf("%s%s", secretNamespacedName.Name, OperatorGeneratedCertSuffix)

	secretBuilder := secret.Builder().
		SetName(operatorGeneratedSecret.Name).
		SetNamespace(operatorGeneratedSecret.Namespace).
		SetStringData(data).
		SetOwnerReferences(ownerReferences)

	var path string
	if vault.IsVaultSecretBackend() && podType != Unused {
		switch podType {
		case Database:
			path = secretClient.VaultClient.DatabaseSecretPath()
		case OpsManager:
			path = secretClient.VaultClient.OpsManagerSecretPath()
		case AppDB:
			path = secretClient.VaultClient.AppDBSecretPath()
		default:
			return fmt.Errorf("unexpected pod type got: %s", podType)
		}
	}

	return secretClient.PutSecretIfChanged(secretBuilder.Build(), path)
}

// VerifyTLSSecretForStatefulSet verifies a `Secret`'s `StringData` is a valid
// certificate, considering the amount of members for a resource named on
// `opts`.
func VerifyTLSSecretForStatefulSet(secretData map[string][]byte, opts Options) (string, error) {
	crt, key := secretData["tls.crt"], secretData["tls.key"]
	data := append(crt, key...)

	additionalDomains := []string{}
	for i := range getPodNames(opts) {
		additionalDomains = append(additionalDomains, GetAdditionalCertDomainsForMember(opts, i)...)
	}

	if err := validatePemData(data, additionalDomains); err != nil {
		return "", err
	}
	return string(data), nil
}

// VerifyAndEnsureCertificatesForStatefulSet ensures that the provided certificates are correct.
// If the secret is of type kubernetes.io/tls, it creates a new secret containing the concatenation fo the tls.crt and tls.key fields
func VerifyAndEnsureCertificatesForStatefulSet(secretReadClient, secretWriteClient secrets.SecretClient, secretName string, opts Options, log *zap.SugaredLogger) (error, bool) {

	needToCreatePEM := false
	var err error
	var secretData map[string][]byte
	var s corev1.Secret
	var databaseSecretPath string

	if vault.IsVaultSecretBackend() {
		needToCreatePEM = true
		databaseSecretPath = secretReadClient.VaultClient.DatabaseSecretPath()
		secretData, err = secretReadClient.VaultClient.ReadSecretBytes(fmt.Sprintf("%s/%s/%s", databaseSecretPath, opts.Namespace, secretName))
		if err != nil {
			return err, false
		}

	} else {
		s, err = secretReadClient.KubeClient.GetSecret(kube.ObjectKey(opts.Namespace, secretName))
		if err != nil {
			return err, true
		}

		// SecretTypeTLS is kubernetes.io/tls
		// This is the standard way in K8S to have secrets that hold TLS certs
		// And it is the one generated by cert manager
		// These type of secrets contain tls.crt and tls.key entries
		if s.Type == corev1.SecretTypeTLS {
			needToCreatePEM = true
			secretData = s.Data
		}
	}

	if needToCreatePEM {
		data, err := VerifyTLSSecretForStatefulSet(secretData, opts)
		if err != nil {
			return err, true
		}

		secretHash := enterprisepem.ReadHashFromSecret(secretReadClient, opts.Namespace, secretName, databaseSecretPath, log)
		return CreatePEMSecretClient(secretWriteClient, kube.ObjectKey(opts.Namespace, secretName), map[string]string{secretHash: data}, opts.OwnerReference, Database, log), true

	}

	var errs error

	if opts.ClusterMode == multi {
		// get the pod names and get the service FQDN for each of the service hostnames
		mdbmName, clusterNum := multicluster.GetRsNamefromMultiStsName(opts.ResourceName),
			multicluster.MustGetClusterNumFromMultiStsName(opts.ResourceName)

		for podNum := 0; podNum < opts.Replicas; podNum++ {
			podName, serviceFQDN := dns.GetMultiPodName(mdbmName, clusterNum, podNum), dns.GetMultiServiceFQDN(mdbmName, opts.Namespace, clusterNum, podNum)
			pem := fmt.Sprintf("%s-pem", podName)
			if err := validatePemSecret(s, pem, []string{serviceFQDN}); err != nil {
				errs = multierror.Append(errs, err)
			}
		}

		return errs, false
	}

	for i, pod := range getPodNames(opts) {
		pem := fmt.Sprintf("%s-pem", pod)
		additionalDomains := GetAdditionalCertDomainsForMember(opts, i)
		if err := validatePemSecret(s, pem, additionalDomains); err != nil {
			errs = multierror.Append(errs, err)
		}
	}

	return errs, false
}

// getPodNames returns the pod names based on the Cert Options provided.
func getPodNames(opts Options) []string {
	_, podnames := dns.GetDNSNames(opts.ResourceName, opts.ServiceName, opts.Namespace, opts.ClusterDomain, opts.Replicas)
	return podnames
}

func GetDNSNames(opts Options) (hostnames, podnames []string) {
	return dns.GetDNSNames(opts.ResourceName, opts.ServiceName, opts.Namespace, opts.ClusterDomain, opts.Replicas)
}

// GetAdditionalCertDomainsForMember gets any additional domains that the
// certificate for the given member of the stateful set should be signed for.
func GetAdditionalCertDomainsForMember(opts Options, member int) (hostnames []string) {
	_, podnames := GetDNSNames(opts)
	for _, certDomain := range opts.additionalCertificateDomains {
		hostnames = append(hostnames, podnames[member]+"."+certDomain)
	}
	if len(opts.horizons) > 0 {
		//at this point len(ss.ReplicaSetHorizons) should be equal to the number
		//of members in the replica set
		for _, externalHost := range opts.horizons[member] {
			//need to use the URL struct directly instead of url.Parse as
			//Parse expects the URL to have a scheme.
			hostURL := url.URL{Host: externalHost}
			hostnames = append(hostnames, hostURL.Hostname())
		}
	}
	return hostnames
}

func validatePemData(data []byte, additionalDomains []string) error {
	pemFile := enterprisepem.NewFileFromData(data)
	if !pemFile.IsComplete() {
		return fmt.Errorf("the certificate is not complete\n")
	}

	cert, err := pemFile.ParseCertificate()
	if err != nil {
		return fmt.Errorf("can't parse certificate: %s\n", err)
	}

	for _, domain := range additionalDomains {
		if !stringutil.CheckCertificateAddresses(cert.DNSNames, domain) {
			return fmt.Errorf("domain %s is not contained in the list of DNSNames %v\n", domain, cert.DNSNames)
		}
	}
	return nil
}

// validatePemSecret returns true if the given Secret contains a parsable certificate and contains all required domains.
func validatePemSecret(secret corev1.Secret, key string, additionalDomains []string) error {
	data, ok := secret.Data[key]
	if !ok {
		return fmt.Errorf("the secret %s does not contain the expected key %s\n", secret.Name, key)
	}

	return validatePemData(data, additionalDomains)
}

// ValidateCertificates verifies the Secret containing the certificates and the keys is valid.
func ValidateCertificates(secretGetter secret.Getter, name, namespace string) error {
	byteData, err := secret.ReadByteData(secretGetter, kube.ObjectKey(namespace, name))
	if err == nil {
		// Validate that the secret contains the keys, if it contains the certs.
		for _, value := range byteData {
			pemFile := enterprisepem.NewFileFromData(value)
			if !pemFile.IsValid() {
				return fmt.Errorf(fmt.Sprintf("The Secret %s containing certificates is not valid. Entries must contain a certificate and a private key.", name))
			}
		}
	}
	return nil
}

// VerifyAndEnsureClientCertificatesForAgentsAndTLSType ensures that agent certs are present and correct, and returns whether or not they are of the kubernetes.io/tls type.
// If the secret is of type kubernetes.io/tls, it creates a new secret containing the concatenation fo the tls.crt and tls.key fields
func VerifyAndEnsureClientCertificatesForAgentsAndTLSType(secretReadClient, secretWriteClient secrets.SecretClient, secret types.NamespacedName, log *zap.SugaredLogger) (error, bool) {

	needToCreatePEM := false
	var secretData map[string][]byte
	var s corev1.Secret
	var err error

	if vault.IsVaultSecretBackend() {
		needToCreatePEM = true
		secretData, err = secretReadClient.VaultClient.ReadSecretBytes(fmt.Sprintf("%s/%s/%s", secretReadClient.VaultClient.DatabaseSecretPath(), secret.Namespace, secret.Name))
		if err != nil {
			return err, false
		}
	} else {
		s, err = secretReadClient.KubeClient.GetSecret(secret)
		if err != nil {
			return err, true
		}

		if s.Type == corev1.SecretTypeTLS {
			needToCreatePEM = true
			secretData = s.Data
		}
	}
	if needToCreatePEM {
		data, err := VerifyTLSSecretForStatefulSet(secretData, Options{Replicas: 0})
		if err != nil {
			return err, false
		}
		dataMap := map[string]string{
			util.AutomationAgentPemSecretKey: data,
		}
		return CreatePEMSecretClient(secretWriteClient, secret, dataMap, []metav1.OwnerReference{}, Database, log), true
	}

	additionalDomains := []string{} // agents have no additional domains
	return validatePemSecret(s, util.AutomationAgentPemSecretKey, additionalDomains), false
}

// EnsureSSLCertsForStatefulSet contains logic to ensure that all of the
// required SSL certs for a StatefulSet object exist.
// It also returns a boolean value indicating whether or no the new tls design must be used
func EnsureSSLCertsForStatefulSet(secretReadClient, secretWriteClient secrets.SecretClient, ms mdbv1.Security, opts Options, log *zap.SugaredLogger) (workflow.Status, bool) {
	if !ms.IsTLSEnabled() {
		// if there's no SSL certs to generate, return
		// Note that we return true, so that enabling TLS later won't cause restarts
		return workflow.OK(), true
	}

	secretName := opts.CertSecretName
	if !ms.TLSConfig.IsSelfManaged() {
		return workflow.Failed("Operator-generated certs are not supported. You must create your own certificates."), true
	}
	return ValidateSelfManagedSSLCertsForStatefulSet(secretReadClient, secretWriteClient, secretName, opts, log)

}

// EnsureTLSCertsForPrometheus creates a new Secret with a Certificate in
// PEM-format. Returns the hash for the certificate in order to be used in
// AutomationConfig.
//
// For Prometheus we *only accept* certificates of type `corev1.SecretTypeTLS`
// so they always need to be concatenated into PEM-format.
func EnsureTLSCertsForPrometheus(secretClient secrets.SecretClient, namespace string, prom *mdbcv1.Prometheus, log *zap.SugaredLogger) (string, error) {
	if prom == nil || prom.TLSSecretRef.Name == "" {
		return "", nil
	}

	var secretData map[string][]byte
	var err error

	var databaseSecretPath string
	if vault.IsVaultSecretBackend() {
		databaseSecretPath = secretClient.VaultClient.DatabaseSecretPath()
		secretData, err = secretClient.VaultClient.ReadSecretBytes(fmt.Sprintf("%s/%s/%s", databaseSecretPath, namespace, prom.TLSSecretRef.Name))
		if err != nil {
			return "", err
		}
	} else {
		s, err := secretClient.KubeClient.GetSecret(kube.ObjectKey(namespace, prom.TLSSecretRef.Name))
		if err != nil {
			return "", fmt.Errorf("could not read Prometheus TLS certificate: %s", err)
		}

		if s.Type != corev1.SecretTypeTLS {
			return "", fmt.Errorf("secret containing the Prometheus TLS certificate needs to be of type kubernetes.io/tls")
		}

		secretData = s.Data
	}

	// We only need VerifyTLSSecretForStatefulSet to return the concatenated
	// tls.key and tls.crt as Strings, but to not divert from the existing code,
	// I'm still calling it, but that can be definitely improved.
	//
	// Make VerifyTLSSecretForStatefulSet receive `s.Data` but only return if it
	// has been verified to be valid or not (boolean return).
	//
	// Use another function to concatenate tls.key and tls.crt into a `string`,
	// or make `CreatePEMSecretClient` able to receive a byte[] instead on its
	// `data` parameter.
	data, err := VerifyTLSSecretForStatefulSet(secretData, Options{Replicas: 0})
	if err != nil {
		return "", err
	}

	// ReadHashFromSecret will read the Secret once again from Kubernetes API,
	// we can improve this function by providing the Secret Data contents,
	// instead of `secretClient`.
	secretHash := enterprisepem.ReadHashFromSecret(secretClient, namespace, prom.TLSSecretRef.Name, databaseSecretPath, log)
	err = CreatePEMSecretClient(secretClient, kube.ObjectKey(namespace, prom.TLSSecretRef.Name), map[string]string{secretHash: data}, []metav1.OwnerReference{}, Database, log)
	if err != nil {
		return "", fmt.Errorf("error creating hashed Secret: %s", err)
	}

	return secretHash, nil
}

// ValidateSelfManagedSSLCertsForStatefulSet ensures that a stateful set using
// user-provided certificates has all of the relevant certificates in place.
// It also returns a boolean value indicating whether or no the new tls design must be used
func ValidateSelfManagedSSLCertsForStatefulSet(secretReadClient, secretWriteClient secrets.SecretClient, secretName string, opts Options, log *zap.SugaredLogger) (workflow.Status, bool) {
	// A "Certs" attribute has been provided
	// This means that the customer has provided with a secret name they have
	// already populated with the certs and keys for this deployment.
	// Because of the async nature of Kubernetes, this object might not be ready yet,
	// in which case, we'll keep reconciling until the object is created and is correct.
	err, newTlsDesign := VerifyAndEnsureCertificatesForStatefulSet(secretReadClient, secretWriteClient, secretName, opts, log)
	if err != nil {
		return workflow.Failed("The secret object '%s' does not contain all the valid certificates needed: %s", secretName, err), true
	}

	if newTlsDesign {
		secretName = fmt.Sprintf("%s-pem", secretName)
	}
	if err := ValidateCertificates(secretReadClient.KubeClient, secretName, opts.Namespace); err != nil {
		return workflow.Failed(err.Error()), true
	}

	return workflow.OK(), newTlsDesign
}
