export K8S_CTX="<your kubernetes context here>"

export MDB_NS="mongodb"

# name of the MongoDB Custom Resource.
export MDB_RESOURCE_NAME="mdb-rs"

# OM/CM's project name to be used to manage mongodb replica set
export OPS_MANAGER_PROJECT_NAME="random-project"

# URL to Cloud Manager or Ops Manager instance
export OPS_MANAGER_API_URL="https://cloud-qa.mongodb.com"

# The API key can be an Org Owner - the operator can create the project automatically.
# The API key can also be created in a particular project that was created manually with the Project Owner scope .
export OPS_MANAGER_API_USER=""
export OPS_MANAGER_API_KEY=""
export OPS_MANAGER_ORG_ID=""

# minimum required MongoDB version for running MongoDB Search is 8.0.10
export MDB_VERSION="8.0.10"

export MDB_ADMIN_USER_PASSWORD="admin-user-password-CHANGE-ME"
export MDB_USER_PASSWORD="mdb-user-password-CHANGE-ME"
export MDB_SEARCH_SYNC_USER_PASSWORD="search-sync-user-password-CHANGE-ME"

export MDB_SEARCH_HOSTNAME="mdbs-search"

# External MongoDB replica set members - REPLACE THESE VALUES with your actual external MongoDB hosts
# For testing purposes, these point to the MongoDB Enterprise resource created by test.sh
# In production, replace with your actual external MongoDB replica set members
export MDB_EXTERNAL_HOST_0="${MDB_RESOURCE_NAME}-0.${MDB_RESOURCE_NAME}-svc.${MDB_NS}.svc.cluster.local:27017"
export MDB_EXTERNAL_HOST_1="${MDB_RESOURCE_NAME}-1.${MDB_RESOURCE_NAME}-svc.${MDB_NS}.svc.cluster.local:27017"
export MDB_EXTERNAL_HOST_2="${MDB_RESOURCE_NAME}-2.${MDB_RESOURCE_NAME}-svc.${MDB_NS}.svc.cluster.local:27017"

# REPLACE with your external MongoDB keyfile secret name
export MDB_EXTERNAL_KEYFILE_SECRET_NAME="${MDB_RESOURCE_NAME}-keyfile"

# REPLACE with the actual keyfile content from your external MongoDB replica set
# For testing, this will be automatically generated by the MongoDB Enterprise resource
export MDB_EXTERNAL_KEYFILE_CONTENT="your-mongodb-keyfile-content-CHANGE-ME"

# REPLACE with your actual external MongoDB replica set name
export MDB_EXTERNAL_REPLICA_SET_NAME="${MDB_RESOURCE_NAME}"

# Search sync source password secret name
export MDB_SEARCH_SYNC_SOURCE_PASSWORD_SECRET_NAME="${MDB_RESOURCE_NAME}-search-sync-source-password"

export OPERATOR_HELM_CHART="mongodb/mongodb-kubernetes"
export OPERATOR_ADDITIONAL_HELM_VALUES=""

export MDB_CONNECTION_STRING="mongodb://mdb-user:${MDB_USER_PASSWORD}@${MDB_EXTERNAL_HOST_0}/?replicaSet=${MDB_EXTERNAL_REPLICA_SET_NAME}"
