"""Standalone cross-layer log analyzer.

Usage:
  python -m tests.common.search.log_analyzer.cli --namespace ls-25 --since 5m

Discovers MongoDBSearch + MongoDB resources in the namespace, pulls logs
from mongos / mongod / mongot / envoy LB pods over the given timeframe,
builds per-cursor cross-layer trees, and prints them. RS vs sharded is
auto-detected by inspecting ``spec.type`` on the MongoDB resource.

Examples:

  # Sharded: render last 5 minutes of operations from ns ls-25
  python -m tests.common.search.log_analyzer.cli \\
    --namespace ls-25 --mdbs-name mdb-sh-conn-tool --since 5m

  # RS: only print the timeline view, not the trees
  python -m tests.common.search.log_analyzer.cli \\
    --namespace ls-25 --since 10m --no-trees

  # Render the single-lsid interleaved timeline (color-coded per cursor).
  python -m tests.common.search.log_analyzer.cli \\
    --namespace ls-25 --since 5m --lsid e7e9aa0b... --color

The envoy access-log surface (always-on JSON stdout records emitted by
the operator-configured HCM) drives the ``envoy.stream`` tree branches.
For frame-level envoy debugging, POST to the admin endpoint manually:
``kubectl exec <envoy-pod> -- curl -X POST localhost:9901/logging?paths=...``.

This module does NOT inject pymongo CommandListener events (the live
test harness is the only source for those). Instead it synthesises
``ClientWireOp`` records from mongod COMMAND aggregate/getMore/
killCursors entries, so the existing ``build_cursor_trees`` /
``build_sharded_cursor_trees`` builders produce one tree per observed
cursor id.

Cross-layer correlation join keys
---------------------------------

Three keys carry across the layers. Spot-check them in the rendered tree:

* lsid (Logical Session ID — 32-hex-char UUID)
  Generated by pymongo, written by mongos and per-shard mongod in every
  COMMAND ``Slow query`` log record (``attr.command.lsid.id``). One lsid
  per logical session — every aggregate / getMore / killCursors on the
  same client cursor shares it. Load-bearing join: pytest <-> mongos <->
  per-shard mongod.

* cursor_id
  Allocated by mongod (or mongos for the top cursor) on the aggregate
  response. Mongos's ``attr.cursor.cursors[]`` lists each shard's
  sub-cursor id; per-shard mongod logs the same id on its own COMMAND
  records.

* clientId (UUID — 32-hex-char)
  Allocated by per-shard mongod when it opens a gRPC egress session to
  envoy. Surfaces in:
    - mongod NETWORK log id=7401401 ``attr.session.clientId``
    - envoy access/debug log ``mongodb-clientid`` request header
    - mongot ``MongoDbGrpcProtocolInterceptor`` DEBUG record
      ``attr.clientId``
  Load-bearing join: per-shard mongod <-> envoy <-> mongot. A single
  client cursor produces N clientIds for an N-way fanout (one per shard
  mongot connection).
"""

from __future__ import annotations

import argparse
import glob
import os
import re
import sys
from typing import Optional

from kubernetes import client, config
from tests.common.search.log_analyzer import collector as log_collector
from tests.common.search.log_analyzer.analyzer import (
    ClientWireOp,
    MongodCommand,
    MongosCommand,
    build_stream_summaries,
    merge_envoy_access_log_into_streams,
    parse_client_wire_ops,
    parse_envoy_debug_log,
    print_cursor_trees,
    print_lsid_timeline,
    print_lsids_summary,
    print_sharded_cursor_trees,
    print_unified_timeline,
    read_envoy_access_log,
    read_mongod_commands,
    read_mongod_sessions,
    read_mongos_commands,
    read_mongos_remote_requests,
    read_mongot_interceptor_events,
    set_mongod_debug_logs,
    set_mongos_debug_logs,
)
from tests.common.search.log_analyzer.store import (
    LogStore,
    build_cursor_trees_sql,
    build_sharded_cursor_trees_sql,
    build_unified_timeline_sql,
)

# ---------------------------------------------------------------------------
# Kube config + resource discovery
# ---------------------------------------------------------------------------


def _client_for_context(context: Optional[str] = None, *, set_default: bool = False) -> Optional[client.ApiClient]:
    """Build an ApiClient for one kube context, honoring per-cluster proxy-url.

    ``context=None`` selects the kubeconfig's current context. With
    ``set_default`` the resulting Configuration is installed as the process
    default and ``None`` is returned (so default-client callers — e.g. resource
    discovery — work); otherwise a dedicated ``ApiClient`` is returned, used by
    ``boost`` to fan out across the member clusters of a multi-cluster
    deployment (mongos / shard mongod / envoy pods live in different kind
    clusters). Falls back to in-cluster config when no kubeconfig is present.
    """
    try:
        from kubetester.kubetester import load_proxy_config

        merger = config.kube_config.KubeConfigMerger(config.kube_config.KUBE_CONFIG_DEFAULT_LOCATION)
        cfg = client.Configuration()
        config.load_kube_config_from_dict(merger.config, context=context, client_configuration=cfg)
        try:
            load_proxy_config(merger.config, cfg)
        except Exception:
            pass
        if set_default:
            client.Configuration.set_default(cfg)
            return None
        return client.ApiClient(configuration=cfg)
    except Exception:
        config.load_incluster_config()
        return None


def _load_kube_config() -> None:
    """Load the current-context kubeconfig (proxy-url aware) as the default."""
    _client_for_context(None, set_default=True)


_MDB_GROUP = "mongodb.com"
_MDB_VERSION = "v1"


def _list_mdb_resources(namespace: str, plural: str) -> list[dict]:
    api = client.CustomObjectsApi()
    try:
        res = api.list_namespaced_custom_object(
            group=_MDB_GROUP,
            version=_MDB_VERSION,
            namespace=namespace,
            plural=plural,
        )
    except client.exceptions.ApiException as exc:
        sys.stderr.write(f"# list {plural}/{namespace}: status={exc.status}\n")
        return []
    return res.get("items", []) or []


def _resolve_mdb_and_mdbs(
    namespace: str,
    mdb_name: Optional[str],
    mdbs_name: Optional[str],
) -> tuple[str, str, str]:
    """Return ``(mdb_name, mdbs_name, spec_type)``."""
    mdbs_items = _list_mdb_resources(namespace, "mongodbsearch")
    mdb_items = _list_mdb_resources(namespace, "mongodb")
    mdbs_list = [m["metadata"]["name"] for m in mdbs_items]
    mdb_list = [(m["metadata"]["name"], (m.get("spec") or {}).get("type", "")) for m in mdb_items]

    if mdbs_name is None and mdb_name is None:
        if len(mdbs_list) == 1:
            mdbs_name = mdbs_list[0]
        elif len(mdb_list) == 1:
            mdb_name = mdb_list[0][0]
        else:
            raise SystemExit(
                f"namespace {namespace!r} has {len(mdbs_list)} MongoDBSearch and "
                f"{len(mdb_list)} MongoDB resources; pass --mdbs-name and/or --mdb-name"
            )

    if mdb_name is None and mdbs_name is not None:
        candidates = [m for m, _ in mdb_list if m == mdbs_name]
        mdb_name = candidates[0] if candidates else mdbs_name

    if mdbs_name is None and mdb_name is not None:
        candidates = [m for m in mdbs_list if m == mdb_name]
        mdbs_name = candidates[0] if candidates else mdb_name

    spec_type = next((t for m, t in mdb_list if m == mdb_name), "")
    assert mdb_name is not None, "internal: mdb_name resolution invariant violated"
    assert mdbs_name is not None, "internal: mdbs_name resolution invariant violated"
    return mdb_name, mdbs_name, spec_type


def _detect_topology(spec_type: str) -> str:
    if spec_type.strip().lower() in {"shardedcluster", "sharded"}:
        return "sharded"
    return "rs"


def _get_shard_count(namespace: str, mdb_name: str) -> int:
    api = client.CustomObjectsApi()
    try:
        obj = api.get_namespaced_custom_object(
            group=_MDB_GROUP,
            version=_MDB_VERSION,
            namespace=namespace,
            plural="mongodb",
            name=mdb_name,
        )
    except client.exceptions.ApiException:
        return 0
    return int((obj.get("spec") or {}).get("shardCount") or 0)


# ---------------------------------------------------------------------------
# Pod-group resolution
# ---------------------------------------------------------------------------


def _pod_groups(
    namespace: str,
    mdb_name: str,
    mdbs_name: str,
    topology: str,
) -> dict[str, list[str]]:
    """Resolve which pods to pull logs from per layer.

    Keys: ``mongos``, ``mongod``, ``mongot``, ``envoy``. Empty lists when
    the layer doesn't apply.
    """
    lb_prefix = f"{mdbs_name}-search-lb-0-"
    envoy = log_collector.discover_pods(namespace, name_prefix=lb_prefix)

    if topology == "sharded":
        mongos = log_collector.discover_pods(namespace, name_prefix=f"{mdb_name}-mongos-")
        mongot = log_collector.discover_pods(namespace, name_prefix=f"{mdbs_name}-search-0-{mdb_name}-")

        # Shard mongods: filter to <mdb>-<idx>-<n> with idx in [0, shardCount).
        shard_count = _get_shard_count(namespace, mdb_name)
        shard_re = re.compile(rf"^{re.escape(mdb_name)}-(\d+)-\d+$")
        all_pods = log_collector.discover_pods(namespace, name_prefix=f"{mdb_name}-")
        mongod: list[str] = []
        for p in all_pods:
            m = shard_re.match(p)
            if m and (shard_count == 0 or int(m.group(1)) < shard_count):
                mongod.append(p)
        return {"mongos": mongos, "mongod": sorted(mongod), "mongot": mongot, "envoy": envoy}

    # RS topology
    rs_re = re.compile(rf"^{re.escape(mdb_name)}-\d+$")
    all_pods = log_collector.discover_pods(namespace, name_prefix=f"{mdb_name}-")
    mongod = sorted(p for p in all_pods if rs_re.match(p))
    # RS mongots live under `<search>-search-` but exclude envoy LB pods.
    raw_mongot = log_collector.discover_pods(namespace, name_prefix=f"{mdbs_name}-search-")
    mongot = sorted(p for p in raw_mongot if not p.startswith(lb_prefix))
    return {"mongos": [], "mongod": mongod, "mongot": mongot, "envoy": envoy}


# ---------------------------------------------------------------------------
# Synthetic client wire ops
# ---------------------------------------------------------------------------


def _synthesize_client_wire_ops(
    mongos_commands: list[MongosCommand],
    mongod_commands: list[MongodCommand],
    topology: str,
) -> list[ClientWireOp]:
    """Build fake pymongo wire-op records from server-side COMMAND logs."""
    ops: list[ClientWireOp] = []
    req_id = 1

    def _emit(command, ts, cursor_id, lsid):
        nonlocal req_id
        rid = req_id
        req_id += 1
        for phase in ("started", "succeeded"):
            ops.append(
                ClientWireOp(
                    phase=phase,
                    command_name=command,
                    request_id=rid,
                    timestamp=ts,
                    lsid=lsid,
                    cursor_id=cursor_id,
                )
            )

    if topology == "sharded":
        for mc in mongos_commands:
            if mc.timestamp is None or mc.cursor_id is None:
                continue
            _emit(mc.command, mc.timestamp, mc.cursor_id, mc.lsid)
    else:
        for mc in mongod_commands:
            if mc.timestamp is None or mc.cursor_id is None:
                continue
            if mc.command == "aggregate" and not mc.has_search_stage:
                continue
            _emit(mc.command, mc.timestamp, mc.cursor_id, mc.lsid)
    return ops


# ---------------------------------------------------------------------------
# Tree builders (orchestration)
# ---------------------------------------------------------------------------


def _build_rs_trees(
    namespace: str,
    paths_by_group: dict[str, list[str]],
    collection_ns_regex: Optional[str] = None,
) -> tuple[list, list, "LogStore"]:
    """Return ``(trees, timeline_events, log_store)`` for the RS case.

    ``collection_ns_regex`` filters mongod_commands to those whose
    ``namespace`` (e.g. ``sample_mflix.movies``) matches the regex.
    """
    mongod_paths = paths_by_group.get("mongod", [])
    mongot_paths = paths_by_group.get("mongot", [])
    envoy_paths = paths_by_group.get("envoy", [])

    mongod_cmds = read_mongod_commands(mongod_paths, namespace=namespace) if mongod_paths else []
    if collection_ns_regex:
        pat = re.compile(collection_ns_regex)
        mongod_cmds = [c for c in mongod_cmds if c.namespace and pat.search(c.namespace)]
    mongod_sessions = read_mongod_sessions(mongod_paths, namespace=namespace) if mongod_paths else []
    envoy_streams = parse_envoy_debug_log(envoy_paths, namespace=namespace) if envoy_paths else []
    envoy_access = read_envoy_access_log(envoy_paths, namespace=namespace) if envoy_paths else []
    envoy_streams = merge_envoy_access_log_into_streams(envoy_streams, envoy_access)
    mongot_streams, mongot_batches = (
        build_stream_summaries(mongot_paths, namespace=namespace) if mongot_paths else ({}, [])
    )
    mongot_opens, mongot_cmds = (
        read_mongot_interceptor_events(mongot_paths, namespace=namespace) if mongot_paths else ([], [])
    )

    client_ops = parse_client_wire_ops(_synthesize_client_wire_ops([], mongod_cmds, "rs"))

    store = LogStore()
    store.load_from_parsed_records(
        client_ops=client_ops,
        mongod_commands=mongod_cmds,
        mongod_sessions=mongod_sessions,
        envoy_streams=envoy_streams,
        envoy_access=envoy_access,
        mongot_streams=mongot_streams,
        mongot_batches=mongot_batches,
        mongot_stream_opens=mongot_opens,
        mongot_cmds=mongot_cmds,
    )
    trees = build_cursor_trees_sql(store)
    timeline = build_unified_timeline_sql(store, include_client_ops=False)
    timeline.extend(_client_ops_as_timeline_events(client_ops))
    timeline.sort(key=lambda e: (e.timestamp, e.layer, e.pod or ""))
    return trees, timeline, store


def _client_ops_as_timeline_events(client_ops):
    """Surface synthesised ClientWireOp records as TimelineEvents."""
    from tests.common.search.log_analyzer.analyzer import TimelineEvent

    out = []
    seen = set()
    for op in client_ops:
        key = (op.request_id, op.phase)
        if key in seen or op.phase != "started":
            continue
        seen.add(key)
        out.append(
            TimelineEvent(
                timestamp=op.timestamp,
                layer="client",
                pod=None,
                kind=op.command_name,
                lsid=op.lsid,
                cursor_id=op.cursor_id,
                server_connection_id=op.server_connection_id,
            )
        )
    return out


def _build_sharded_trees(
    namespace: str,
    paths_by_group: dict[str, list[str]],
    mdb_name: str,
    mdbs_name: str,
    collection_ns_regex: Optional[str] = None,
) -> tuple[list, list, "LogStore"]:
    mongos_paths = paths_by_group.get("mongos", [])
    mongod_paths = paths_by_group.get("mongod", [])
    mongot_paths = paths_by_group.get("mongot", [])
    envoy_paths = paths_by_group.get("envoy", [])

    mongos_cmds = read_mongos_commands(mongos_paths, namespace=namespace) if mongos_paths else []
    mongos_reqs = read_mongos_remote_requests(mongos_paths, namespace=namespace) if mongos_paths else []
    mongod_cmds = read_mongod_commands(mongod_paths, namespace=namespace) if mongod_paths else []
    if collection_ns_regex:
        pat = re.compile(collection_ns_regex)
        mongos_cmds = [c for c in mongos_cmds if c.namespace and pat.search(c.namespace)]
        mongod_cmds = [c for c in mongod_cmds if c.namespace and pat.search(c.namespace)]
    mongod_sessions = read_mongod_sessions(mongod_paths, namespace=namespace) if mongod_paths else []
    envoy_streams = parse_envoy_debug_log(envoy_paths, namespace=namespace) if envoy_paths else []
    envoy_access = read_envoy_access_log(envoy_paths, namespace=namespace) if envoy_paths else []
    envoy_streams = merge_envoy_access_log_into_streams(envoy_streams, envoy_access)
    mongot_streams, mongot_batches = (
        build_stream_summaries(mongot_paths, namespace=namespace) if mongot_paths else ({}, [])
    )
    mongot_opens, mongot_cmds = (
        read_mongot_interceptor_events(mongot_paths, namespace=namespace) if mongot_paths else ([], [])
    )

    # Determine shard indices from observed mongod pod filenames.
    shard_indices: set[int] = set()
    pod_re = re.compile(rf"^{re.escape(mdb_name)}-(\d+)-\d+$")
    for path in mongod_paths:
        base = os.path.basename(path)
        if base.endswith(".log"):
            base = base[:-4]
        m = pod_re.match(base)
        if m:
            shard_indices.add(int(m.group(1)))
    shard_pod_prefixes = {f"{mdb_name}-{i}": f"{mdb_name}-{i}-" for i in sorted(shard_indices)}
    shard_mongot_pod_prefixes = {
        f"{mdb_name}-{i}": f"{mdbs_name}-search-0-{mdb_name}-{i}-" for i in sorted(shard_indices)
    }

    client_ops = parse_client_wire_ops(_synthesize_client_wire_ops(mongos_cmds, mongod_cmds, "sharded"))

    store = LogStore()
    store.load_from_parsed_records(
        client_ops=client_ops,
        mongod_commands=mongod_cmds,
        mongod_sessions=mongod_sessions,
        mongos_commands=mongos_cmds,
        mongos_remote_requests=mongos_reqs,
        envoy_streams=envoy_streams,
        envoy_access=envoy_access,
        mongot_streams=mongot_streams,
        mongot_batches=mongot_batches,
        mongot_stream_opens=mongot_opens,
        mongot_cmds=mongot_cmds,
    )
    trees = build_sharded_cursor_trees_sql(
        store,
        shard_pod_prefixes=shard_pod_prefixes,
        shard_mongot_pod_prefixes=shard_mongot_pod_prefixes,
    )

    timeline = build_unified_timeline_sql(store, include_client_ops=False)
    timeline.extend(_client_ops_as_timeline_events(client_ops))
    timeline.sort(key=lambda e: (e.timestamp, e.layer, e.pod or ""))
    return trees, timeline, store


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _resolve_paths_from_logs_dir(logs_dir: str) -> tuple[dict[str, list[str]], str]:
    """Discover per-layer log paths under a snapshot dir.

    Recognised subdirs (each may be missing or empty):
      ``mongod*/``, ``mongot*/`` (mongot-pre + mongot-post welcome),
      ``envoy*/``, ``mongos*/``. Returns ``({layer: [paths]}, topology)``;
      topology is "sharded" iff any mongos log file is present.
    """
    if not os.path.isdir(logs_dir):
        raise SystemExit(f"--logs-dir not a directory: {logs_dir}")

    def _collect(prefix: str) -> list[str]:
        return sorted(glob.glob(os.path.join(logs_dir, f"{prefix}*", "*.log")))

    paths = {
        "mongod": _collect("mongod"),
        "mongot": _collect("mongot"),
        "envoy": _collect("envoy"),
        "mongos": _collect("mongos"),
    }
    topology = "sharded" if paths["mongos"] else "rs"
    return paths, topology


def _parse_since_to_seconds(since: str) -> int:
    """``5m``/``90s``/``2h`` -> seconds (int)."""
    m = re.fullmatch(r"(\d+)([smh]?)", since.strip())
    if not m:
        raise SystemExit(f"invalid --since value {since!r} (use e.g. 30s, 5m, 1h)")
    n = int(m.group(1))
    unit = m.group(2) or "s"
    return n * {"s": 1, "m": 60, "h": 3600}[unit]


# ---------------------------------------------------------------------------
# boost: raise per-layer log verbosity before driving a workload
# ---------------------------------------------------------------------------

ENVOY_DEBUG_PATHS = "connection:debug,http2:debug,http:debug,router:debug,pool:debug"
ENVOY_ADMIN_PORT = 9901


def _boost_envoy(namespace: str, mdbs_name: str, contexts: list[Optional[str]], *, restore: bool, paths: str) -> None:
    """Raise (or restore) the per-frame HTTP/2 component log level on each envoy
    LB pod by POSTing its admin ``/logging`` endpoint through the API server's
    pod-proxy subresource (``/pods/<pod>:9901/proxy/logging?paths=...``). This
    needs no curl/wget inside the container (the envoy image ships neither) and
    no port-forward — the apiserver proxies to the pod's admin port.

    The always-on JSON access log (``bytes_in``/``bytes_out``/``grpc=OK`` per
    mongot stream) needs no boost; this surfaces the per-frame DATA/RST_STREAM
    detail (``parse_envoy_debug_log``) for stream-level forensics."""
    target = "connection:info,http2:info,http:info,router:info,pool:info" if restore else paths
    for ctx in contexts:
        api = _client_for_context(ctx)
        core = client.CoreV1Api(api_client=api) if api is not None else client.CoreV1Api()
        pods = log_collector.discover_pods(namespace, name_prefix=f"{mdbs_name}-search-lb-0-", api_client=api)
        if not pods:
            print(f"  envoy[{ctx or 'current'}]: no search-lb pods found")
            continue
        for pod in pods:
            try:
                core.api_client.call_api(
                    f"/api/v1/namespaces/{namespace}/pods/{pod}:{ENVOY_ADMIN_PORT}/proxy/logging",
                    "POST",
                    query_params=[("paths", target)],
                    response_type="str",
                    _return_http_data_only=True,
                    auth_settings=["BearerToken"],
                )
                status = "ok"
            except Exception as exc:  # report-and-continue across pods/clusters
                status = f"FAILED ({exc!r})"
            print(f"  envoy[{ctx or 'current'}] {pod}: {status} ({'restored' if restore else 'debug'})")


def _boost_mongo(mongo_uri: str, *, restore: bool, command_level: int, network_level: int) -> None:
    """Raise mongos/mongod COMMAND+NETWORK verbosity via setParameter over a
    pymongo connection. Auto-detects mongos (``hello.msg == 'isdbgrid'``) vs
    mongod. NOTE: setParameter on a mongos does NOT propagate to shards — for a
    sharded cluster, also run with a ``--mongo-uri`` pointed at each shard's RS
    (directConnection) to capture the per-shard ``$search``/idLookup records."""
    from pymongo import MongoClient

    cl = 0 if restore else command_level
    nl = 0 if restore else network_level
    mc = MongoClient(mongo_uri, serverSelectionTimeoutMS=10000)
    is_mongos = mc.admin.command("hello").get("msg") == "isdbgrid"
    if is_mongos:
        set_mongos_debug_logs(mc, command_level=cl, network_level=nl)
        print(f"  mongos: COMMAND={cl} NETWORK={nl} ({'restored' if restore else 'debug'})")
    else:
        set_mongod_debug_logs(mc, command_level=cl, network_level=nl)
        print(f"  mongod: COMMAND={cl} NETWORK={nl} QUERY={'0' if restore else '1'} ({'restored' if restore else 'debug'})")


def _run_boost(args: argparse.Namespace) -> int:
    if not args.namespace:
        raise SystemExit("--namespace required for --boost")
    namespace = args.namespace
    contexts: list[Optional[str]] = (
        [c.strip() for c in args.contexts.split(",") if c.strip()] if args.contexts else [None]
    )
    # Install a default config for resource discovery from the first target
    # context (a multi-cluster kubeconfig often has no current-context, so
    # default-context selection would fail).
    _client_for_context(contexts[0], set_default=True)
    if args.mdbs_name:
        mdbs_name = args.mdbs_name
    else:
        _mdb_name, mdbs_name, _spec = _resolve_mdb_and_mdbs(namespace, args.mdb_name, args.mdbs_name)
    print(
        f"# boost namespace={namespace} mdbs={mdbs_name} "
        f"action={'restore' if args.restore else 'debug'} contexts={[c or 'current' for c in contexts]}"
    )
    if not args.no_envoy:
        _boost_envoy(namespace, mdbs_name, contexts, restore=args.restore, paths=args.envoy_paths)
    if not args.no_mongo:
        if args.mongo_uri:
            _boost_mongo(
                args.mongo_uri,
                restore=args.restore,
                command_level=args.command_level,
                network_level=args.network_level,
            )
        else:
            print(
                "  mongo: skipped (pass --mongo-uri <conn-str>; for sharded, target "
                "the mongos AND each shard RS directly — setParameter does not fan out)"
            )
    return 0


def _parse_args(argv: Optional[list[str]] = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        prog="log_analyzer.cli",
        description=(
            "Standalone cross-layer log analyzer for MongoDB + MongoDBSearch. "
            "Pulls logs from mongos/mongod/mongot/envoy and renders per-cursor "
            "trees plus a unified timeline."
        ),
    )
    p.add_argument("--namespace", help="K8s namespace (live mode)")
    p.add_argument("--mdb-name", help="MongoDB resource name (auto-detected if unset)")
    p.add_argument("--mdbs-name", help="MongoDBSearch resource name (auto-detected if unset)")
    p.add_argument(
        "--logs-dir",
        help=(
            "Replay from a snapshot dir instead of the K8s API. Layout: "
            "<dir>/mongod*/*.log, <dir>/mongot*/*.log, <dir>/envoy*/*.log, "
            "<dir>/mongos*/*.log. Topology auto-detected (sharded iff any "
            "mongos/*.log present)."
        ),
    )
    p.add_argument(
        "--collection-namespace",
        metavar="REGEX",
        help=(
            "Filter mongod / mongos commands by their MongoDB namespace "
            "(e.g. ``sample_mflix.movies`` or ``sample_mflix\\..*``). "
            "Drops oplog and other internal noise from the tree/timeline."
        ),
    )
    p.add_argument(
        "--since",
        default="10m",
        help="log lookback window for live mode (default: 10m; e.g. 30s, 5m, 1h).",
    )
    p.add_argument(
        "--topology",
        choices=("rs", "sharded"),
        help="Override topology detection (rare).",
    )
    tg = p.add_mutually_exclusive_group()
    tg.add_argument("--trees", dest="trees", action="store_true", default=True, help="Render cursor trees (default)")
    tg.add_argument("--no-trees", dest="trees", action="store_false", help="Suppress cursor-tree rendering")
    tl = p.add_mutually_exclusive_group()
    tl.add_argument(
        "--timeline", dest="timeline", action="store_true", default=True, help="Print the unified timeline (default)"
    )
    tl.add_argument("--no-timeline", dest="timeline", action="store_false", help="Suppress the unified timeline")
    p.add_argument(
        "--timeline-max",
        type=int,
        default=200,
        help="Max number of timeline events to print (0 = unlimited).",
    )
    p.add_argument(
        "--lsid",
        help=(
            "Filter to a single logical session id (32-hex). When set, prints a "
            "chronological interleaved timeline of events sharing this lsid, "
            "color-coded by cursor_id. Suppresses the default tree + timeline output."
        ),
    )
    cg = p.add_mutually_exclusive_group()
    cg.add_argument(
        "--color",
        dest="color",
        action="store_true",
        default=None,
        help="Force ANSI color in --lsid output (default: auto/TTY).",
    )
    cg.add_argument(
        "--no-color",
        dest="color",
        action="store_false",
        default=None,
        help="Disable ANSI color in --lsid output (also respects NO_COLOR env).",
    )
    p.add_argument(
        "--sql",
        metavar="QUERY",
        help=(
            "Run an arbitrary SQL query against the in-memory LogStore "
            "(SQLite). Prints rows as TSV. Short-circuits the tree / "
            "timeline output. Useful for ad-hoc cross-layer joins."
        ),
    )
    bg = p.add_argument_group("boost", "raise per-layer log verbosity before driving a workload (then exit)")
    bg.add_argument(
        "--boost",
        action="store_true",
        help="Boost mode: POST envoy admin /logging to debug and/or setParameter mongo verbosity, then exit.",
    )
    bg.add_argument(
        "--restore",
        action="store_true",
        help="With --boost: restore log levels (envoy -> info, mongo COMMAND/NETWORK/QUERY -> 0) instead of raising.",
    )
    bg.add_argument("--no-envoy", action="store_true", help="With --boost: skip the envoy LB pods.")
    bg.add_argument("--no-mongo", action="store_true", help="With --boost: skip mongos/mongod.")
    bg.add_argument(
        "--envoy-paths",
        default=ENVOY_DEBUG_PATHS,
        help=f"With --boost: envoy admin /logging paths (default: {ENVOY_DEBUG_PATHS}).",
    )
    bg.add_argument(
        "--mongo-uri",
        help=(
            "With --boost: pymongo connection string for the mongos (or a shard RS via "
            "directConnection). setParameter does NOT fan out to shards — pass each shard RS "
            "separately to capture per-shard $search/idLookup records."
        ),
    )
    bg.add_argument("--command-level", type=int, default=2, help="With --boost: mongo COMMAND verbosity (default 2).")
    bg.add_argument("--network-level", type=int, default=2, help="With --boost: mongo NETWORK verbosity (default 2).")
    bg.add_argument(
        "--contexts",
        help=(
            "With --boost: comma-separated kube contexts to fan the envoy boost across "
            "(multi-cluster: e.g. kind-e2e-cluster-1,kind-e2e-cluster-2,kind-e2e-cluster-3). "
            "Defaults to the current context."
        ),
    )
    return p.parse_args(argv)


def main(argv: Optional[list[str]] = None) -> int:
    args = _parse_args(argv)

    if args.boost:
        return _run_boost(args)

    if args.logs_dir:
        paths_by_group, detected_topology = _resolve_paths_from_logs_dir(args.logs_dir)
        topology = args.topology or detected_topology
        namespace = args.namespace or ""
        mdb_name = args.mdb_name or ""
        mdbs_name = args.mdbs_name or ""
        print(f"# logs_dir={args.logs_dir}  topology={topology}  " f"mdb={mdb_name or '-'}  mdbs={mdbs_name or '-'}")
        for name, paths in paths_by_group.items():
            if paths:
                print(f"  {name}: {[os.path.basename(p) for p in paths]}")
    else:
        if not args.namespace:
            raise SystemExit("--namespace required (or use --logs-dir for offline replay)")
        _load_kube_config()
        namespace = args.namespace
        mdb_name, mdbs_name, spec_type = _resolve_mdb_and_mdbs(namespace, args.mdb_name, args.mdbs_name)
        topology = args.topology or _detect_topology(spec_type)
        print(
            f"# namespace={namespace}  mdb={mdb_name}  mdbs={mdbs_name}  "
            f"topology={topology}  spec.type={spec_type or '?'}"
        )
        groups = _pod_groups(namespace, mdb_name, mdbs_name, topology)
        since_seconds = _parse_since_to_seconds(args.since)
        paths_by_group = {}
        for name, pods in groups.items():
            if not pods:
                paths_by_group[name] = []
                continue
            print(f"  {name}: {pods}")
            paths_by_group[name] = log_collector.fetch_pod_logs(
                namespace,
                pods,
                since_seconds=since_seconds,
            )

    if topology == "sharded":
        if not (mdb_name and mdbs_name):
            raise SystemExit("sharded topology needs --mdb-name and --mdbs-name in --logs-dir mode")
        trees, timeline, store = _build_sharded_trees(
            namespace=namespace,
            paths_by_group=paths_by_group,
            mdb_name=mdb_name,
            mdbs_name=mdbs_name,
            collection_ns_regex=args.collection_namespace,
        )
    else:
        trees, timeline, store = _build_rs_trees(
            namespace=namespace,
            paths_by_group=paths_by_group,
            collection_ns_regex=args.collection_namespace,
        )

    if args.sql:
        cur = store.conn.execute(args.sql)
        cols = [d[0] for d in cur.description] if cur.description else []
        if cols:
            print("\t".join(cols))
        for row in cur:
            print("\t".join("" if v is None else str(v) for v in row))
        return 0

    if args.lsid:
        print_lsid_timeline(timeline, args.lsid, color=args.color)
    else:
        print_lsids_summary(timeline)
        if args.trees:
            if topology == "sharded":
                print_sharded_cursor_trees(trees)
            else:
                print_cursor_trees(trees)
        if args.timeline:
            print_unified_timeline(
                timeline,
                max_events=args.timeline_max,
                color=args.color,
            )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
