//go:build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package search

import (
	"github.com/mongodb/mongodb-kubernetes/api/v1/status"
	"github.com/mongodb/mongodb-kubernetes/api/v1/user"
	"github.com/mongodb/mongodb-kubernetes/mongodb-community-operator/api/v1/common"
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBSearch) DeepCopyInto(out *MongoDBSearch) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBSearch.
func (in *MongoDBSearch) DeepCopy() *MongoDBSearch {
	if in == nil {
		return nil
	}
	out := new(MongoDBSearch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongoDBSearch) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBSearchList) DeepCopyInto(out *MongoDBSearchList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MongoDBSearch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBSearchList.
func (in *MongoDBSearchList) DeepCopy() *MongoDBSearchList {
	if in == nil {
		return nil
	}
	out := new(MongoDBSearchList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongoDBSearchList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBSearchSpec) DeepCopyInto(out *MongoDBSearchSpec) {
	*out = *in
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(MongoDBSource)
		(*in).DeepCopyInto(*out)
	}
	if in.StatefulSetConfiguration != nil {
		in, out := &in.StatefulSetConfiguration, &out.StatefulSetConfiguration
		*out = (*in).DeepCopy()
	}
	if in.Persistence != nil {
		in, out := &in.Persistence, &out.Persistence
		*out = new(common.Persistence)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceRequirements != nil {
		in, out := &in.ResourceRequirements, &out.ResourceRequirements
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBSearchSpec.
func (in *MongoDBSearchSpec) DeepCopy() *MongoDBSearchSpec {
	if in == nil {
		return nil
	}
	out := new(MongoDBSearchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBSearchStatus) DeepCopyInto(out *MongoDBSearchStatus) {
	*out = *in
	in.Common.DeepCopyInto(&out.Common)
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make([]status.Warning, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBSearchStatus.
func (in *MongoDBSearchStatus) DeepCopy() *MongoDBSearchStatus {
	if in == nil {
		return nil
	}
	out := new(MongoDBSearchStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBSource) DeepCopyInto(out *MongoDBSource) {
	*out = *in
	if in.MongoDBResourceRef != nil {
		in, out := &in.MongoDBResourceRef, &out.MongoDBResourceRef
		*out = new(user.MongoDBResourceRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBSource.
func (in *MongoDBSource) DeepCopy() *MongoDBSource {
	if in == nil {
		return nil
	}
	out := new(MongoDBSource)
	in.DeepCopyInto(out)
	return out
}
