{% extends "Dockerfile.template" %}

{% set base_image = "registry.access.redhat.com/ubi8/ubi-minimal" %}

{% block packages -%}
# Building an UBI-based image: https://red.ht/3n6b9y0
RUN microdnf update \
    --disableplugin=subscription-manager \
    --disablerepo=* --enablerepo=ubi-8-appstream-rpms --enablerepo=ubi-8-baseos-rpms -y \
    && rm -rf /var/cache/yum
{% endblock -%}
