{% extends "Dockerfile.template" %}

{% block packages %}
# Adds up-to-date CA certificates.
RUN apt-get -qq update && \
      apt-get -y -qq install ca-certificates curl && \
      apt-get upgrade -y -qq && \
      apt-get dist-upgrade -y -qq && \
      rm -rf /var/lib/apt/lists/*
{% endblock %}
