{% extends "Dockerfile.template" %}

# Packages is empty because there's nothing to install on RHEL.

{% block static %}
COPY licenses/ /licenses
COPY LICENSE /licenses/mongodb-enterprise-operator
{% endblock %}
