#!/usr/bin/env bash
#
# A script Evergreen will use to compile the Operator
#
# This should be executed from root of the evergreen build dir
#

set -xeo pipefail

# ${WORKDIR} refers to the MCI working directory
GOPATH="${WORKDIR}"
export GOPATH

export GOROOT="/usr/lib/go"
export GOBIN="${GOPATH}/bin"
export PATH="${GOBIN}:${PATH}"

mkdir -p "${GOBIN}"
curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

./scripts/build/prepare_build_environment
# This skips the regeneration of code + download of dependencies if this step was
# taken care of by the test_operator script.
export BUILD_ENVIRONMENT_READY=true

if [ -z "${SKIP_TESTING}" ]; then
    ./scripts/build/test_operator "$*"
fi
./scripts/build/build_operator "$*"
