#!/usr/bin/env bash
set -Eeou pipefail

KUBECONFIG_SAVED="${KUBECONFIG}"
unset KUBECONFIG

# Make sure kubectl fails if no KUBECONFIG is set
if kubectl get nodes &> /dev/null; then
    echo "There's a kubectl context defined globally ($HOME/.kube/config exists)"
    exit 1
fi

KUBECONFIG="${KUBECONFIG_SAVED}"
export KUBECONFIG

source scripts/funcs/kubernetes

##
## Does some preliminary actions to prepare testing environment:
## - fixes AWS
## - installs cluster cleaner
## - starts Ops Manager if it's not started yet and if it's necessary
##

# cleanup_env fixes AWS problems if any
fix_env() {
    ns_count="$(kubectl get ns -o name | grep a- --count || true)"
    echo "Current number of test namespaces: $ns_count"

    # sometimes in kops cluster some nodes get this taint that makes nodes non-schedulable. Just going over all nodes and
    # trying to remove the taint is supposed to help
    echo "##### Fixing taints"
    for n in $(kubectl get nodes -o name); do
        kubectl taint nodes "${n}" NodeWithImpairedVolumes:NoSchedule- 2> /dev/null || true
    done

    echo "##### Removing FAILED Persistent Volumes if any"
    # Note, that these volumes will be removed from EBS eventually (during a couple of hours), most of all they are stuck
    # in attaching - this results in nodes getting taints "NoSchedule"
    for v in $(kubectl get pv -o=custom-columns=NAME:.metadata.name,status:.status.phase | grep Failed | awk '{ print $1 }'); do
        kubectl delete pv "${v}"
    done
}

upgrade_crds() {
    kubectl apply -f public/helm_chart/crds
}

deploy_cluster_cleaner() {
    ops_manager_namespace="${1}"
    cleaner_namespace="cluster-cleaner"
    if ! kubectl get "ns/${cleaner_namespace=}" &> /dev/null ; then
        kubectl create namespace "${cleaner_namespace=}"
    fi

    if [[ -n "${ops_manager_namespace}" ]]; then
        kubectl create namespace "${ops_manager_namespace}" || true
    fi

    helm template docker/cluster-cleaner \
         --set cleanerVersion=latest \
         --set namespace="${ops_manager_namespace}" \
         --set cleanerNamespace=cluster-cleaner \
         > cluster-cleaner.yaml
    kubectl apply -f cluster-cleaner.yaml
    rm cluster-cleaner.yaml
}

ops_manager_namespace="${1:-}"
ops_manager_version="${2:-}"
node_port="${3:-}"

echo "Fixing AWS problems if any"
fix_env

echo "Deploying cluster-cleaner"
deploy_cluster_cleaner "${ops_manager_namespace}"

echo "Installing/Upgrading all CRDs"
upgrade_crds

if [[ "${OM_EXTERNALLY_CONFIGURED:-}" != "true" ]] && [[ -n "${ops_manager_namespace}" ]]; then
    ensure_ops_manager_k8s "${ops_manager_namespace}" "${ops_manager_version}" "${node_port}"
fi
