#!/usr/bin/env bash

# Does general cleanup work for external sources (currently only aws). Must be called once per Evergreen run
prepare_aws() {
    echo "##### Detaching the EBS Volumes that are stuck"
    for v in $(aws ec2 describe-volumes --filters Name=attachment.status,Values=attaching | grep VolumeId | cut -d "\"" -f 4); do
        set -v
        aws ec2 detach-volume --volume-id ${v} --force || true
        set +v
    done

    echo "##### Removing ESB volumes which are not used any more"
    # Seems Openshift (sometimes?) doesn't remove the volumes but marks them as available - we need to clean these volumes
    # manually
    for v in $(aws ec2 describe-volumes --filters Name=status,Values=available | grep VolumeId | cut -d "\"" -f 4); do
        set -v
        aws ec2 delete-volume --volume-id ${v} || true
        set +v
    done

    echo "##### Removing old s3 buckets"
    # note, to run this on mac you need to install coreutils ('brew install coreutils') and use 'gdate' instead
    yesterday=$(date +%Y-%m-%d -d "yesterday")
    for bucket in $(aws s3api list-buckets --query 'Buckets[?CreationDate<=`'$yesterday'`&&contains(Name,`test-bucket-`)]' | jq --raw-output '.[].Name'); do
        aws s3 rb s3://$bucket --force
    done
}
prepare_aws
