#!/usr/bin/env bash

set -xeuo pipefail

echo "Installing the aws-cli...."

curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
unzip awscli-bundle.zip
./awscli-bundle/install -b ~/aws

echo "Aws-cli is installed"

