#!/usr/bin/env bash

BINDIR="${workdir}/bin"
mkdir -p "${BINDIR}" || true

echo "Downloading kubectl v1.15.4"
curl -s -LO https://storage.googleapis.com/kubernetes-release/release/v1.15.4/bin/linux/amd64/kubectl
chmod +x kubectl
mv kubectl $BINDIR

echo "Downloading helm"
HELM=helm.tgz
curl -s https://storage.googleapis.com/kubernetes-helm/helm-v2.10.0-linux-amd64.tar.gz --output $HELM
tar xfz $HELM &> /dev/null
mv linux-amd64/helm $BINDIR
rm $HELM
