#!/usr/bin/env bash

#
# Configures docker-credential-ecr-login which allows for accessing
# ECR registries without using `aws ecr login`, hence, avoiding
# installing `aws` Python client.
#

curl -LO https://amazon-ecr-credential-helper-releases.s3.us-east-2.amazonaws.com/0.3.1/linux-amd64/docker-credential-ecr-login
chmod +x docker-credential-ecr-login

mkdir -p "${BIN_PATH}"
sudo mv docker-credential-ecr-login "${BIN_PATH}"

# Creates credsStore configuration for Docker for ECR
mkdir -p "${HOME}/.docker"
cat <<EOF > "${HOME}/.docker/config.json"
{
	"credHelpers": {
		"268558157000.dkr.ecr.us-east-1.amazonaws.com": "ecr-login"
	}
}
EOF
