#!/usr/bin/env bash
#
# This script should be run from the root evergreen work dir

set -euo pipefail

INSTALL_DIR="$(pwd)/.local/lib/aws"
BIN_LOCATION="$(pwd)/bin/aws"

curl -s "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
unzip awscli-bundle.zip &> /dev/null
./awscli-bundle/install --bin-location "${BIN_LOCATION}" --install-dir "${INSTALL_DIR}"
