#!/usr/bin/env bash

set -Eeou pipefail

# shellcheck disable=SC2154
context_config="${workdir}/${kube_environment_name}_config"
if [ -f "${context_config}" ]; then
    echo "Context configuration already exist, host was not clearly cleaned up!"
    rm "${context_config}"

    exit 1
fi

if [ "${kube_environment_name}" = "openshift_4" ]; then
    echo "Downloading OC & setting up Openshift 4 cluster"
    OC_PKG=oc-linux.tar.gz
    curl --fail --retry 3 -s -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.3.1/openshift-client-linux-4.3.1.tar.gz --output $OC_PKG
    tar xfz $OC_PKG &> /dev/null
    mv oc "$BINDIR"

    # This uses a kubeconfig yaml file stored in the Evergreen project instead of the old token login
    # to avoid having to keep the tokens valid forever.
    echo "${openshift43_cluster_kubeconfig:?}" | base64 --decode > "${context_config}"

elif [ "${kube_environment_name}" = "vanilla" ]; then
    if [ -n "${cluster_name-}" ]; then
        export CLUSTER=${cluster_name}
    else
        export CLUSTER=e2e.mongokubernetes.com
    fi

    export AWS_ACCESS_KEY_ID="${mms_eng_test_aws_access_key:?}"
    export AWS_SECRET_ACCESS_KEY="${mms_eng_test_aws_secret:?}"
    export AWS_DEFAULT_REGION="${mms_eng_test_aws_region:?}"
    export KOPS_STATE_STORE=s3://kube-om-state-store

    echo "Downloading kops"
    curl -s -L https://github.com/kubernetes/kops/releases/download/1.14.0/kops-linux-amd64 -o kops
    chmod +x kops
    mv kops "$BINDIR"

    if ! kops get clusters | grep -q $CLUSTER; then
        echo "Cluster $CLUSTER not found, exiting..."
        echo run "make recreate-e2e-kops imsure=yes cluster=$CLUSTER"
        kops get clusters
        exit 1
    fi

    kops export kubecfg $CLUSTER
    mv "${HOME}"/.kube/config "${context_config}"

elif [ "${kube_environment_name}" = "kind" ]; then
    echo "Starting Kind"
    kubernetes_image="kindest/node:v1.16.9@sha256:b91a2c2317a000f3a783489dfb755064177dbc3a0b2f4147d50f04825d016f55"
    kind create cluster \
        --image "${kubernetes_image}" \
        --config "${HOME}/.operator-dev/kind-ecr-config.yaml" \
        --kubeconfig "${context_config}"
else
    echo "kube_environment_name not recognized"
    echo "value is <<${kube_environment_name}>>. If empty it means it was not set"

    # Fail if there's no Kubernetes environment set
    exit 1
fi
