#!/usr/bin/env bash


# shellcheck disable=SC2154
context_config="${workdir}/${kube_environment_name}_config"

if [ "${kube_environment_name}" = "kind" ]; then
    echo "Deleting Kind cluster"
    kind delete cluster
fi

if [ -f "${context_config}" ]; then
    rm "${context_config}"
fi
