#!/usr/bin/env bash

set -xeou pipefail


generate_standalone_yaml() {
    # Generates a yaml file to install the operator from the helm sources.

    charttmpdir=$(mktemp -d 2>/dev/null || mktemp -d -t 'charttmpdir')
    charttmpdir=${charttmpdir}/chart
    mkdir -p "${charttmpdir}"

    helm template -f helm_chart/values.yaml helm_chart --output-dir "${charttmpdir}"

    cat "${charttmpdir}"/mongodb-enterprise-operator/templates/{operator-roles.yaml,database-roles.yaml,operator.yaml} > mongodb-enterprise.yaml
    cp "${charttmpdir}"/mongodb-enterprise-operator/templates/crds.yaml crds.yaml

    rm -rf ${charttmpdir}/*

    helm template -f helm_chart/values.yaml helm_chart --output-dir "${charttmpdir}" --values helm_chart/values-openshift.yaml

    cat "${charttmpdir}"/mongodb-enterprise-operator/templates/{operator-roles.yaml,database-roles.yaml,operator.yaml} > mongodb-enterprise-openshift.yaml
}

PUBLIC_REPO="$1"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
pushd "${DIR}" &> /dev/null
cd "$(../gitroot)" || exit 1

GITHASH="$(git rev-parse HEAD)"

cd "${PUBLIC_REPO}"
git pull

cd -

rsync -avP --delete public/ "${PUBLIC_REPO}" \
  --filter 'protect .git'

cd "${PUBLIC_REPO}"

generate_standalone_yaml

STATUS=$(git status --porcelain)
if ! [ z"${STATUS}" = z ]; then
    if [ -z "${GENERATE_ONLY+x}" ]; then
        echo "Commiting (don't forget to push)"
        git add .
        git commit -m "${GITHASH}: update public repo contents"
#        git push
    else
        echo "Not commiting nor pushing"
    fi
fi
