#!/usr/bin/env bash

set -xeou pipefail

PUBLIC_REPO="$1"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
pushd "${DIR}" &> /dev/null
cd "$(../gitroot)" || exit 1

GITHASH="$(git rev-parse HEAD)"

rsync -avP --delete public/ "${PUBLIC_REPO}" \
  --filter 'protect .git'

cd "${PUBLIC_REPO}"

git add .

STATUS=$(git status --porcelain)

if ! [ z"${STATUS}" = z ] ; then
  git commit -m "${GITHASH}: update public repo contents"
  git push
fi
