#!/usr/bin/env bash
#
# This script should be run from the root evergreen work dir

set -xeuo pipefail

PATH="$PATH:$(pwd)/bin"
export PATH

cd "src/github.com/10gen/ops-manager-kubernetes"

IMAGE="$1"

AWS_REPO="268558157000.dkr.ecr.us-east-1.amazonaws.com/dev/${IMAGE}"
QUAY_REPO="quay.io/mongodb-enterprise-private/${IMAGE}"

eval "sudo $(aws ecr get-login --no-include-email --region us-east-1)"

sudo docker tag "dev/${IMAGE}" "${AWS_REPO}"

sudo docker push "${AWS_REPO}"

echo "Built and pushed the docker image ${IMAGE} to ECR"

# Quay
set -v
echo "running: sudo docker login -u mongodb-enterprise-private+build_robot -p <password> quay.io"
sudo docker login -u mongodb-enterprise-private+build_robot -p "${QUAY_ROBOT_TOKEN}" quay.io
set +v

sudo docker tag "dev/${IMAGE}" "${QUAY_REPO}"

sudo docker push "${QUAY_REPO}"

echo "Built and pushed the docker image ${IMAGE} to Quay"
