#!/usr/bin/env bash

set -xeuo pipefail

# Important: this script can be launch only if 'setup_' scripts were run for aws and docker!
# also operator must be checked out and compiled beforehand

export GOPATH="$(pwd)"
cd "${GOPATH}/src/github.com/10gen/ops-manager-kubernetes"

aws_repo='268558157000.dkr.ecr.us-east-1.amazonaws.com/dev/mongodb-enterprise-operator'
quay_repo='quay.io/mongodb-enterprise-private/mongodb-enterprise-operator'

echo "Building the operator image..."

sudo docker build -t dev/mongodb-enterprise-operator .

# AWS ECR
eval "sudo $(aws ecr get-login --no-include-email --region us-east-1)"

sudo docker tag dev/mongodb-enterprise-operator ${aws_repo}

sudo docker push ${aws_repo}

echo "Built and pushed the docker image for operator to ECR"

# Quay
sudo docker login -u mongodb-enterprise-private+build_robot -p ${QUAY_ROBOT_TOKEN} quay.io

sudo docker tag dev/mongodb-enterprise-operator ${quay_repo}

sudo docker push ${quay_repo}

echo "Built and pushed the docker image for operator to Quay"
