#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel || echo "Failed to find git root"; exit 1)"

s3_bucket_path="ops-manager-operator/${version_id:?}/${IMAGE_TYPE}/contexts/${context:?}-context.tar.gz"

echo "=> Uploading Kaniko context for docker/${docker_dir_name:?} directory to s3 bucket (path:${s3_bucket_path})"

tar -C "docker/${docker_dir_name}" -zcf "${context}-context.tar.gz" .
aws s3api head-bucket --bucket operator-kubernetes-build \
    || aws s3api create-bucket --bucket operator-kubernetes-build --acl public-read --region us-east-1
aws s3api put-object --bucket operator-kubernetes-build \
    --key "${s3_bucket_path}" \
    --body "${context}-context.tar.gz" \
    --content-type application/octet-stream
rm -rf "${context}-context.tar.gz"

echo "=> Kaniko context successfully uploaded to S3"
