variables:
  - &setup_and_teardown_group_gke_code_snippets
    setup_task_can_fail_task: true
    setup_group:
      - func: clone
      - func: setup_gcloud_cli
      - func: setup_mongosh
      - func: download_kube_tools
      - func: build_multi_cluster_binary
    teardown_task:
      - func: upload_e2e_logs
      - func: upload_code_snippets_logs

  - &setup_and_teardown_group_kind_code_snippets
    setup_task_can_fail_task: true
    setup_group:
      - func: clone
      - func: cleanup_exec_environment
      - func: download_kube_tools
      - func: configure_docker_auth
      - func: setup_kubernetes_environment
    teardown_task:
      - func: upload_e2e_logs
      - func: upload_code_snippets_logs

# This variable is copied over from .evergreen.yml because anchors don't work for included files
  - &base_om8_dependency
    depends_on:
      - name: build_om_images
        variant: build_om80_images
      - name: build_operator_ubi
        variant: init_test_run
      - name: build_init_database_image_ubi
        variant: init_test_run
      - name: build_database_image_ubi
        variant: init_test_run
      - name: build_test_image
        variant: init_test_run
      - name: build_init_appdb_images_ubi
        variant: init_test_run
      - name: build_init_om_images_ubi
        variant: init_test_run
      - name: build_agent_images_ubi
        variant: init_test_run

tasks:
  # Code snippets tasks
  # Each scripts/code_snippets/tests/test_*.sh should have its task defined here.
  # TODO: it should be autogenerated
  # Each task executes test_code_snippets functon executes scripts/code_snippets/tests/${task_name} by task name convention
  - name: test_gke_multi_cluster_snippets.sh
    tags: [ "code_snippets" ]
    commands:
      - func: test_code_snippets
      - func: sample_commit_output

  - name: test_gke_multi_cluster_no_mesh_snippets.sh
    tags: [ "code_snippets" ]
    commands:
      - func: test_code_snippets
      - func: sample_commit_output

  - name: test_kind_search_community_snippets.sh
    tags: [ "code_snippets", "patch-run" ]
    commands:
      - func: test_code_snippets
      - func: sample_commit_output

task_groups:
  - name: gke_code_snippets_task_group
    <<: *setup_and_teardown_group_gke_code_snippets
    max_hosts: -1
    tasks:
      - test_gke_multi_cluster_snippets.sh
      - test_gke_multi_cluster_no_mesh_snippets.sh

  - name: kind_code_snippets_task_group
    <<: *setup_and_teardown_group_kind_code_snippets
    max_hosts: -1
    tasks:
      - test_kind_search_community_snippets.sh

buildvariants:
  # These variants are used to test the code snippets and each one can be used in patches
  # Prerelease is especially used when the repo is tagged
  # More details in the TD: https://docs.google.com/document/d/1fuTxfRtP8QPtn7sKYxQM_AGcD6xycTZH8svngGxyKhc/edit?tab=t.0#bookmark=id.e8uva0393mbe
  - name: public_gke_code_snippets
    display_name: public_gke_code_snippets
    allowed_requesters: [ "patch" ]
    run_on:
      - ubuntu2204-small
    tasks:
      - name: gke_code_snippets_task_group

  - name: prerelease_gke_code_snippets
    display_name: prerelease_gke_code_snippets
    tags: [ "release" ]
    allowed_requesters: [ "patch", "github_tag" ]
    depends_on:
      - variant: release_images
        name: '*'
        patch_optional: true
    run_on:
      - ubuntu2204-small
    tasks:
      - name: gke_code_snippets_task_group

  - name: private_gke_code_snippets
    display_name: private_gke_code_snippets
    allowed_requesters: [ "patch" ]
    run_on:
      - ubuntu2204-small
    <<: *base_om8_dependency
    tasks:
      - name: gke_code_snippets_task_group

  - name: private_kind_code_snippets
    display_name: private_kind_code_snippets
    tags: [ "e2e_test_suite" ]
    allowed_requesters: [ "patch", "github_pr" ]
    run_on:
      - ubuntu2204-large
    <<: *base_om8_dependency
    tasks:
      - name: kind_code_snippets_task_group

  - name: prerelease_kind_code_snippets
    display_name: prerelease_kind_code_snippets
    allowed_requesters: [ "patch" ]
    run_on:
      - ubuntu2204-large
    tasks:
      - name: kind_code_snippets_task_group

  - name: public_kind_code_snippets
    display_name: public_kind_code_snippets
    allowed_requesters: [ "patch" ]
    run_on:
      - ubuntu2204-large
    tasks:
      - name: kind_code_snippets_task_group
