include:
  - filename: .evergreen-functions.yml
  - filename: .evergreen-tasks.yml

variables:
  - &setup_group
    setup_group_can_fail_task: true
    setup_group:
      - func: clone
      - func: setup_docker_sbom
      - func: download_kube_tools
      - func: setup_building_host
      - func: quay_login
      - func: switch_context

tasks:
  - name: periodic_teardown_aws
    commands:
      - func: cleanup_aws

  - name: periodic_teardown_cloudqa
    commands:
      - func: teardown_cloud_qa_all

task_groups:
  - name: periodic_teardown_task_group
    <<: *setup_group
    tasks:
      - periodic_teardown_aws
      - periodic_teardown_cloudqa

buildvariants:
  - name: periodic_teardown
    display_name: periodic_teardown
    tags: [ "periodic_teardown" ]
    run_on:
      - ubuntu2204-small
    tasks:
      - name: periodic_teardown_task_group
