include:
  - filename: .evergreen-functions.yml
  - filename: .evergreen-tasks.yml

parameters:
  - key: pin_tag_at
    value: 00:00
    description: Pin tags at this time of the day. Midnight by default.

variables:
  - &setup_group
    setup_group_can_fail_task: true
    setup_group:
      - func: clone
      - func: setup_docker_sbom
      - func: download_kube_tools
      - func: setup_building_host
      - func: quay_login
      - func: switch_context

tasks:
  - name: periodic_build_operator
    commands:
      - func: legacy_pipeline
        vars:
          image_name: operator-daily

  - name: periodic_teardown_aws
    commands:
      - func: cleanup_aws

  - name: periodic_teardown_cloudqa
    commands:
      - func: teardown_cloud_qa_all

  - name: periodic_build_init_appdb
    commands:
      - func: legacy_pipeline
        vars:
          image_name: init-appdb-daily

  - name: periodic_build_init_database
    commands:
      - func: legacy_pipeline
        vars:
          image_name: init-database-daily

  - name: periodic_build_init_opsmanager
    commands:
      - func: legacy_pipeline
        vars:
          image_name: init-ops-manager-daily

  - name: periodic_build_database
    commands:
      - func: legacy_pipeline
        vars:
          image_name: database-daily

  - name: periodic_build_sbom_cli
    commands:
      - func: legacy_pipeline
        vars:
          image_name: cli

  - name: periodic_build_ops_manager_6
    commands:
      - func: legacy_pipeline
        vars:
          image_name: ops-manager-6-daily

  - name: periodic_build_ops_manager_7
    commands:
      - func: legacy_pipeline
        vars:
          image_name: ops-manager-7-daily

  - name: periodic_build_ops_manager_8
    commands:
      - func: legacy_pipeline
        vars:
          image_name: ops-manager-8-daily

  # the periodic agent builds are more commented in the pipeline.py file.
  # The gist is - we want to split up the periodic build on as many machines as possible
  # To speed up the builds as we have too many agents due to the matrix build.
  # For now its one without operator suffix and the last 3. This only works as long as we
  # only have operator versions we support (minor version), as soon as we have multiple patch versions -
  # this won't work anymore and we will need a dynamic solution.
  - name: periodic_build_agent
    exec_timeout_secs: 43200
    commands:
      - func: enable_QEMU
      - func: legacy_pipeline
        vars:
          image_name: mongodb-agent-daily

  - name: periodic_build_agent_1
    exec_timeout_secs: 43200
    commands:
      - func: enable_QEMU
      - func: legacy_pipeline
        vars:
          image_name: mongodb-agent-1-daily

  - name: periodic_build_agent_2
    exec_timeout_secs: 43200
    commands:
      - func: enable_QEMU
      - func: pipeline
        vars:
          image_name: mongodb-agent-2-daily

  - name: periodic_build_agent_3
    exec_timeout_secs: 43200
    commands:
      - func: enable_QEMU
      - func: pipeline
        vars:
          image_name: mongodb-agent-3-daily

  #TODO should we still build the community operator?
  - name: periodic_build_community_operator
    commands:
      - func: enable_QEMU
      - func: legacy_pipeline
        vars:
          image_name: mongodb-kubernetes-operator-daily

  - name: periodic_build_readiness_probe
    commands:
      - func: legacy_pipeline
        vars:
          image_name: readinessprobe-daily

  - name: periodic_build_version_upgrade_post_start_hook
    commands:
      - func: legacy_pipeline
        vars:
          image_name: operator-version-upgrade-post-start-hook-daily

task_groups:
  - name: periodic_build_task_group
    max_hosts: -1
    <<: *setup_group
    tasks:
      - periodic_build_operator
      - periodic_build_readiness_probe
      - periodic_build_version_upgrade_post_start_hook
      - periodic_build_init_appdb
      - periodic_build_init_database
      - periodic_build_init_opsmanager
      - periodic_build_ops_manager_6
      - periodic_build_ops_manager_7
      - periodic_build_ops_manager_8
      - periodic_build_database
      - periodic_build_community_operator
      - periodic_build_sbom_cli
      - periodic_build_agent
      - periodic_build_agent_1
      - periodic_build_agent_2
      - periodic_build_agent_3

  - name: periodic_teardown_task_group
    <<: *setup_group
    tasks:
      - periodic_teardown_aws
      - periodic_teardown_cloudqa

buildvariants:
  - name: periodic_teardown
    display_name: periodic_teardown
    tags: [ "periodic_teardown" ]
    run_on:
      - ubuntu2204-small
    tasks:
      - name: periodic_teardown_task_group

  - name: periodic_build
    display_name: periodic_build
    tags: [ "periodic_build" ]
    run_on:
      - release-ubuntu2204-large # This is required for CISA attestation https://jira.mongodb.org/browse/DEVPROD-17780
    tasks:
      - name: periodic_build_task_group

  - name: preflight_release_images_check_only
    display_name: preflight_release_images_check_only
    tags: [ "periodic_build" ]
    depends_on:
      - name: "*"
        variant: periodic_build
    run_on:
      - rhel90-large
    tasks:
      - name: preflight_images_task_group
