include:
  - filename: .evergreen-functions.yml
  - filename: .evergreen-tasks.yml

parameters:
  - key: pin_tag_at
    value: 00:00
    description: Pin tags at this time of the day. Midnight by default.

variables:
  - &setup_group
    setup_group_can_fail_task: true
    setup_group:
      - func: clone
      - func: setup_docker_sbom
      - func: download_kube_tools
      - func: setup_building_host
      - func: quay_login
      - func: switch_context

tasks:
  - name: periodic_teardown_task_group
    <<: *setup_group
    tasks:
      - periodic_teardown_aws
      - periodic_teardown_cloudqa

buildvariants:
  - name: periodic_teardown
    display_name: periodic_teardown
    tags: [ "periodic_teardown" ]
    run_on:
      - ubuntu2204-small
    tasks:
      - name: periodic_teardown_task_group

  - name: preflight_release_images_check_only
    display_name: preflight_release_images_check_only
    tags: [ "periodic_build" ]
    depends_on:
      - name: "*"
        variant: periodic_build
    run_on:
      - rhel90-large
    tasks:
      - name: preflight_images_task_group
