%%{
  init: {
    'theme': 'dark',
    'logLevel': 'debug',
    'gitGraph': {
      'showBranches': true,
      'mainBranchName': 'master',
      'parallelCommits': true
    },
    'themeVariables': {
      'commitLabelColor': '#ffffff',
      'commitLabelBackground': '#333333'
    }
  }
}%%
gitGraph
    checkout master
    commit id: "A1" tag:"v1.0.0"
    commit id: "A2: fix v1.0.1"
    commit id: "A3: fix v1.0.1"
    commit id: "A4: fix v1.0.1" tag:"v1.0.1"
    commit id: "A5: feature v1.1.0"
    commit id: "A6: feature v1.1.0"
    commit id: "A7: feature v1.1.0" tag:"v1.1.0"
    commit id: "A8: feature v1.2.0" tag:"v1.2.0"
    commit id: "A9: feature v1.3.0"
