apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Example Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: mongodb
    server: https://central.mongokubernetes.com
  clusterResourceWhitelist:
  # Allow MongoDBMultiCluster resources to be synced
  - group: ''
    kind: MongoDBMultiCluster
  - group: ''
    kind: Namespace
