//go:build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package vai

import (
	"github.com/mongodb/mongodb-kubernetes/api/v1/status"
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BatchingConfig) DeepCopyInto(out *BatchingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BatchingConfig.
func (in *BatchingConfig) DeepCopy() *BatchingConfig {
	if in == nil {
		return nil
	}
	out := new(BatchingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataParallelConfig) DeepCopyInto(out *DataParallelConfig) {
	*out = *in
	if in.NumWorkers != nil {
		in, out := &in.NumWorkers, &out.NumWorkers
		*out = new(int32)
		**out = **in
	}
	if in.Batching != nil {
		in, out := &in.Batching, &out.Batching
		*out = new(BatchingConfig)
		**out = **in
	}
	if in.HealthMonitoring != nil {
		in, out := &in.HealthMonitoring, &out.HealthMonitoring
		*out = new(HealthMonitoringConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataParallelConfig.
func (in *DataParallelConfig) DeepCopy() *DataParallelConfig {
	if in == nil {
		return nil
	}
	out := new(DataParallelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthMonitoringConfig) DeepCopyInto(out *HealthMonitoringConfig) {
	*out = *in
	if in.EnableActiveChecks != nil {
		in, out := &in.EnableActiveChecks, &out.EnableActiveChecks
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthMonitoringConfig.
func (in *HealthMonitoringConfig) DeepCopy() *HealthMonitoringConfig {
	if in == nil {
		return nil
	}
	out := new(HealthMonitoringConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Security) DeepCopyInto(out *Security) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLS)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Security.
func (in *Security) DeepCopy() *Security {
	if in == nil {
		return nil
	}
	out := new(Security)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerConfig) DeepCopyInto(out *ServerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerConfig.
func (in *ServerConfig) DeepCopy() *ServerConfig {
	if in == nil {
		return nil
	}
	out := new(ServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLS) DeepCopyInto(out *TLS) {
	*out = *in
	out.CertificateKeySecretRef = in.CertificateKeySecretRef
	if in.CAConfigMapRef != nil {
		in, out := &in.CAConfigMapRef, &out.CAConfigMapRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLS.
func (in *TLS) DeepCopy() *TLS {
	if in == nil {
		return nil
	}
	out := new(TLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VoyageAI) DeepCopyInto(out *VoyageAI) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VoyageAI.
func (in *VoyageAI) DeepCopy() *VoyageAI {
	if in == nil {
		return nil
	}
	out := new(VoyageAI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VoyageAI) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VoyageAIList) DeepCopyInto(out *VoyageAIList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VoyageAI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VoyageAIList.
func (in *VoyageAIList) DeepCopy() *VoyageAIList {
	if in == nil {
		return nil
	}
	out := new(VoyageAIList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VoyageAIList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VoyageAISpec) DeepCopyInto(out *VoyageAISpec) {
	*out = *in
	out.Server = in.Server
	in.Security.DeepCopyInto(&out.Security)
	in.DataParallel.DeepCopyInto(&out.DataParallel)
	if in.ResourceRequirements != nil {
		in, out := &in.ResourceRequirements, &out.ResourceRequirements
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeAffinity != nil {
		in, out := &in.NodeAffinity, &out.NodeAffinity
		*out = new(v1.NodeAffinity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VoyageAISpec.
func (in *VoyageAISpec) DeepCopy() *VoyageAISpec {
	if in == nil {
		return nil
	}
	out := new(VoyageAISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VoyageAIStatus) DeepCopyInto(out *VoyageAIStatus) {
	*out = *in
	in.Common.DeepCopyInto(&out.Common)
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make([]status.Warning, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VoyageAIStatus.
func (in *VoyageAIStatus) DeepCopy() *VoyageAIStatus {
	if in == nil {
		return nil
	}
	out := new(VoyageAIStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VoyageAIVersionOption) DeepCopyInto(out *VoyageAIVersionOption) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VoyageAIVersionOption.
func (in *VoyageAIVersionOption) DeepCopy() *VoyageAIVersionOption {
	if in == nil {
		return nil
	}
	out := new(VoyageAIVersionOption)
	in.DeepCopyInto(out)
	return out
}
