import os

RELEASE_INITIAL_VERSION_ENV_VAR = "RELEASE_INITIAL_VERSION"
RELEASE_INITIAL_COMMIT_SHA_ENV_VAR = "RELEASE_INITIAL_COMMIT_SHA"

DEFAULT_RELEASE_INITIAL_VERSION = "1.0.0"
DEFAULT_RELEASE_INITIAL_COMMIT_SHA = "9ed5f98fc70c5b3442f633d2393265fb8a2aba0c"
DEFAULT_CHANGELOG_PATH = "changelog/"
DEFAULT_REPOSITORY_PATH = "."


def get_initial_version() -> str:
    return os.getenv(RELEASE_INITIAL_VERSION_ENV_VAR, DEFAULT_RELEASE_INITIAL_VERSION)


def get_initial_commit_sha() -> str:
    return os.getenv(RELEASE_INITIAL_COMMIT_SHA_ENV_VAR, DEFAULT_RELEASE_INITIAL_COMMIT_SHA)
