name: 'Switch context and export all environment variables'
inputs:
  context-name:
    description: 'Context name to switch to'
    required: true
runs:
  using: "composite"
  steps:
    - name: Switch context
      shell: bash
      run: |
        echo "Initializing context files"
        cp scripts/dev/contexts/gha-private-context scripts/dev/contexts/private-context
        scripts/dev/switch_context.sh ${{inputs.context-name}}
        echo "Finished initializing to the ${{inputs.context-name}}"
        while read line; do
          echo "$line" >> $GITHUB_ENV
        done < <(tail -n +5 .generated/context.env | sed 's/\"//g')
