package construct

import (
	"fmt"
	"os"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/intstr"
	"k8s.io/utils/ptr"

	mdbv1 "github.com/mongodb/mongodb-kubernetes/api/v1/mdb"
	"github.com/mongodb/mongodb-kubernetes/pkg/kube"
)

const (
	monarchHealthPort      int32 = 8080
	monarchReplicationPort int32 = 9995
	monarchAPIPort         int32 = 1122

	defaultMonarchImage = "268558157000.dkr.ecr.us-east-1.amazonaws.com/staging/mongodb-kubernetes-monarch-injector:latest"

	// DefaultMonarchReplicas is the default number of Monarch instances (shippers or injectors).
	// Multiple instances provide redundancy - the CAS protocol on S3 ensures only one write
	// per oplog entry is accepted, so duplicates are safe.
	DefaultMonarchReplicas = 3

	monarchConfigVolumeName = "monarch-config"
	monarchConfigMountPath  = "/etc/monarch"
	monarchConfigFileName   = "config.yaml"
)

// MonarchDeploymentName returns the name for the Monarch Deployment.
// Role is "shipper" for active clusters, "injector" for standby.
func MonarchDeploymentName(mdbName, role string) string {
	return fmt.Sprintf("%s-monarch-%s", mdbName, role)
}

// MonarchServiceName returns the name for the Monarch Service.
func MonarchServiceName(mdbName, role string) string {
	return fmt.Sprintf("%s-monarch-%s-svc", mdbName, role)
}

// MonarchConfigMapName returns the name for the Monarch ConfigMap.
func MonarchConfigMapName(mdbName, role string) string {
	return fmt.Sprintf("%s-monarch-%s-config", mdbName, role)
}

// GetMonarchServiceDNS returns the in-cluster DNS name for the Monarch Service.
func GetMonarchServiceDNS(mdbName, role, namespace string) string {
	return fmt.Sprintf("%s.%s.svc.cluster.local", MonarchServiceName(mdbName, role), namespace)
}

// monarchLabels returns the labels for Monarch resources.
func monarchLabels(mdb *mdbv1.MongoDB, role string) map[string]string {
	return map[string]string{
		"app":               fmt.Sprintf("monarch-%s", role),
		"mongodb":           mdb.Name,
		"monarch-component": role,
	}
}

// MdbMonarchImageEnv is the env var for overriding the Monarch image (for dev/testing).
const MdbMonarchImageEnv = "MDB_MONARCH_IMAGE"

// monarchImage returns the image to use for Monarch.
// Priority: 1) spec.monarch.image, 2) MDB_MONARCH_IMAGE env var, 3) default
func monarchImage(spec *mdbv1.MonarchSpec) string {
	if spec.Image != "" {
		return spec.Image
	}
	if envImage := os.Getenv(MdbMonarchImageEnv); envImage != "" {
		return envImage
	}
	return defaultMonarchImage
}

// monarchRole returns "shipper" for active clusters, "injector" for standby.
func monarchRole(spec *mdbv1.MonarchSpec) string {
	if spec.Role == mdbv1.MonarchRoleActive {
		return "shipper"
	}
	return "injector"
}

// BuildMonarchConfigMap creates a ConfigMap with the Monarch YAML configuration.
func BuildMonarchConfigMap(mdb *mdbv1.MongoDB, namespace string, srcURI string) *corev1.ConfigMap {
	spec := mdb.Spec.Monarch
	role := monarchRole(spec)
	labels := monarchLabels(mdb, role)

	// Build YAML config - monarch reads this via --config flag
	// Build per-member host list: <rs>-0.<svc>.<ns>.svc.cluster.local:27017,...
	svcName := fmt.Sprintf("%s-svc", mdb.Name)
	hosts := make([]string, mdb.Spec.Members)
	for i := 0; i < mdb.Spec.Members; i++ {
		hosts[i] = fmt.Sprintf("%s-%d.%s.%s.svc.cluster.local:27017", mdb.Name, i, svcName, namespace)
	}

	replSetHostsYAML := ""
	for _, h := range hosts {
		replSetHostsYAML += fmt.Sprintf("\n  - \"%s\"", h)
	}

	// AWS credentials use credentialsChain mode (reads from AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY env vars)
	config := fmt.Sprintf(`# Monarch %s configuration - generated by mongodb-kubernetes-operator
clusterPrefix: %s
shardId: "0"
replSetName: "%s"
replSetHosts:%s

srcURI: "%s"
backupMongoNodeURI: "%s"

aws:
  authMode: credentialsChain
  bucketName: %s
  region: %s`,
		role,
		spec.ClusterPrefix,
		mdb.Name,
		replSetHostsYAML,
		srcURI,
		srcURI, // backupMongoNodeURI uses same URI for now
		spec.S3BucketName,
		spec.AWSRegion,
	)

	// Add optional S3 endpoint config for MinIO/LocalStack
	if spec.S3BucketEndpoint != "" {
		config += fmt.Sprintf(`
  customBaseEndpoint: %s`, spec.S3BucketEndpoint)
	}
	if spec.S3PathStyleAccess {
		config += `
  usePathStyle: true`
	}

	// Bind all ports to 0.0.0.0 so the Kubernetes Service can route traffic to pods
	config += fmt.Sprintf(`

bindIp: "0.0.0.0"
port: %d
healthApiEndpoint: "0.0.0.0:%d"
monarchApiEndpoint: "0.0.0.0:%d"
`, monarchReplicationPort, monarchHealthPort, monarchAPIPort)

	return &corev1.ConfigMap{
		ObjectMeta: metav1.ObjectMeta{
			Name:            MonarchConfigMapName(mdb.Name, role),
			Namespace:       namespace,
			Labels:          labels,
			OwnerReferences: kube.BaseOwnerReference(mdb),
		},
		Data: map[string]string{
			monarchConfigFileName: config,
		},
	}
}

// BuildMonarchDeployment creates a Deployment for Monarch shipper (active) or injector (standby).
// The deployment has multiple replicas for redundancy.
func BuildMonarchDeployment(mdb *mdbv1.MongoDB, namespace string) *appsv1.Deployment {
	spec := mdb.Spec.Monarch
	role := monarchRole(spec)
	name := MonarchDeploymentName(mdb.Name, role)
	labels := monarchLabels(mdb, role)

	// Command uses --config to read YAML configuration
	configPath := fmt.Sprintf("%s/%s", monarchConfigMountPath, monarchConfigFileName)
	command := []string{
		"monarch", role,
		fmt.Sprintf("--config=%s", configPath),
	}

	// AWS credentials via env vars (monarch reads these with credentialsChain auth mode)
	envVars := []corev1.EnvVar{
		{
			Name: "AWS_ACCESS_KEY_ID",
			ValueFrom: &corev1.EnvVarSource{
				SecretKeyRef: &corev1.SecretKeySelector{
					LocalObjectReference: corev1.LocalObjectReference{Name: spec.CredentialsSecretRef.Name},
					Key:                  "awsAccessKeyId",
				},
			},
		},
		{
			Name: "AWS_SECRET_ACCESS_KEY",
			ValueFrom: &corev1.EnvVarSource{
				SecretKeyRef: &corev1.SecretKeySelector{
					LocalObjectReference: corev1.LocalObjectReference{Name: spec.CredentialsSecretRef.Name},
					Key:                  "awsSecretAccessKey",
				},
			},
		},
	}

	replicas := int32(DefaultMonarchReplicas)

	return &appsv1.Deployment{
		ObjectMeta: metav1.ObjectMeta{
			Name:            name,
			Namespace:       namespace,
			Labels:          labels,
			OwnerReferences: kube.BaseOwnerReference(mdb),
		},
		Spec: appsv1.DeploymentSpec{
			Replicas: ptr.To(replicas),
			Selector: &metav1.LabelSelector{
				MatchLabels: labels,
			},
			Template: corev1.PodTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{
					Labels: labels,
				},
				Spec: corev1.PodSpec{
					Containers: []corev1.Container{
						{
							Name:    fmt.Sprintf("monarch-%s", role),
							Image:   monarchImage(spec),
							Command: command,
							Ports: []corev1.ContainerPort{
								{Name: "health", ContainerPort: monarchHealthPort, Protocol: corev1.ProtocolTCP},
								{Name: "replication", ContainerPort: monarchReplicationPort, Protocol: corev1.ProtocolTCP},
								{Name: "monarch-api", ContainerPort: monarchAPIPort, Protocol: corev1.ProtocolTCP},
							},
							ReadinessProbe: &corev1.Probe{
								ProbeHandler: corev1.ProbeHandler{
									HTTPGet: &corev1.HTTPGetAction{
										Path: "/api/v1/status",
										Port: intstr.FromInt32(monarchHealthPort),
									},
								},
								InitialDelaySeconds: 5,
								PeriodSeconds:       10,
								FailureThreshold:    3,
							},
							Env: envVars,
							VolumeMounts: []corev1.VolumeMount{
								{
									Name:      monarchConfigVolumeName,
									MountPath: monarchConfigMountPath,
									ReadOnly:  true,
								},
							},
						},
					},
					Volumes: []corev1.Volume{
						{
							Name: monarchConfigVolumeName,
							VolumeSource: corev1.VolumeSource{
								ConfigMap: &corev1.ConfigMapVolumeSource{
									LocalObjectReference: corev1.LocalObjectReference{
										Name: MonarchConfigMapName(mdb.Name, role),
									},
								},
							},
						},
					},
				},
			},
		},
	}
}

// BuildMonarchService creates a Service that fronts the Monarch Deployment.
func BuildMonarchService(mdb *mdbv1.MongoDB, namespace string) *corev1.Service {
	spec := mdb.Spec.Monarch
	role := monarchRole(spec)
	labels := monarchLabels(mdb, role)

	return &corev1.Service{
		ObjectMeta: metav1.ObjectMeta{
			Name:            MonarchServiceName(mdb.Name, role),
			Namespace:       namespace,
			Labels:          labels,
			OwnerReferences: kube.BaseOwnerReference(mdb),
		},
		Spec: corev1.ServiceSpec{
			Selector: labels,
			Ports: []corev1.ServicePort{
				{Name: "health", Port: monarchHealthPort, TargetPort: intstr.FromInt32(monarchHealthPort), Protocol: corev1.ProtocolTCP},
				{Name: "replication", Port: monarchReplicationPort, TargetPort: intstr.FromInt32(monarchReplicationPort), Protocol: corev1.ProtocolTCP},
				{Name: "monarch-api", Port: monarchAPIPort, TargetPort: intstr.FromInt32(monarchAPIPort), Protocol: corev1.ProtocolTCP},
			},
		},
	}
}
