#!/usr/bin/env python3
"""Send structured log events from an e2e task run to Honeycomb.

Sources (all filtered aggressively to keep event count low):
  1. events_detailed.yaml  — Kubernetes Warning events only
  2. logs/*agent-health-status.json — per-pod agent health state (always small)
  3. logs/*mongodb-kubernetes-operator*.log — Zap JSONL, ERROR/WARN level only,
     deduplicated by fingerprinted message pattern

Events are POSTed to Honeycomb's batch Events API (not OTLP) since they are
standalone diagnostic events, not part of a trace.

Usage:
  python3 send_logs_to_honeycomb.py --logs-dir logs --task-id $task_id --version-id $version_id
  python3 send_logs_to_honeycomb.py --logs-dir logs --task-id $task_id --version-id $version_id --dry-run
  python3 send_logs_to_honeycomb.py --logs-dir logs --task-id $task_id --version-id $version_id --max-events 50
"""

import argparse
import glob
import json
import logging
import os
import sys
import urllib.request
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

import yaml

# Allow running from repo root (PYTHONPATH=. is set by run_python.sh)
try:
    from kubetester.failure_fingerprint import failure_fingerprint
except ImportError:
    # Fallback when running standalone without kubetester on path
    def failure_fingerprint(msg: str) -> str:
        return msg or ""


HONEYCOMB_API_URL = "https://api.honeycomb.io/1/batch/mongodb-e2e-tests"
MAX_EVENTS_DEFAULT = 500  # hard safety cap per run

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _base_context(task_id: str, version_id: str) -> dict:
    return {
        "evergreen.task.id": task_id,
        "evergreen.version.id": version_id,
    }


def _post_batch(events: list[dict], api_key: str, dry_run: bool) -> None:
    """POST a batch of Honeycomb events. Each event is {"time": ..., "data": {...}}."""
    if not events:
        return
    if dry_run:
        log.info("[dry-run] would POST %d events to Honeycomb", len(events))
        for e in events[:5]:
            log.info("  sample: %s", json.dumps(e["data"], default=str)[:200])
        if len(events) > 5:
            log.info("  ... and %d more", len(events) - 5)
        return

    payload = json.dumps(events).encode()
    req = urllib.request.Request(
        HONEYCOMB_API_URL,
        data=payload,
        headers={
            "X-Honeycomb-Team": api_key,
            "Content-Type": "application/json",
        },
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        body = resp.read().decode()
        log.info("Honeycomb batch response %d: %s", resp.status, body[:200])


# ---------------------------------------------------------------------------
# Source 1: Kubernetes Warning events
# ---------------------------------------------------------------------------

def collect_kube_warning_events(logs_dir: Path, ctx: dict) -> list[dict]:
    """Parse *events_detailed.yaml and return one event per Warning.

    The file is generated by: kubectl get events -o yaml
    Root structure: { apiVersion: v1, items: [...Event objects...] }
    There is no root 'kind' field in this format.
    """
    # Match any *events_detailed.yaml — the dump script prefixes with namespace
    files = glob.glob(str(logs_dir / "*events_detailed.yaml"))
    if not files:
        log.debug("no *events_detailed.yaml found, skipping kube events")
        return []

    result = []
    _kube_dedup: dict = {}  # (pattern, pod_name, reason) → event
    for events_file in files:
        try:
            with open(events_file) as f:
                raw = f.read()
        except OSError as e:
            log.warning("Failed to read %s: %s", events_file, e)
            continue

        # kubectl -o yaml produces a single document with an 'items' list.
        # Use safe_load_all to handle either single or multi-document YAML.
        try:
            docs = list(yaml.safe_load_all(raw))
        except yaml.YAMLError as e:
            log.warning("Failed to parse %s: %s", events_file, e)
            continue

        for doc in docs:
            if not isinstance(doc, dict):
                continue
            # Root has 'items' list (kubectl List format) or is a single Event
            if "items" in doc:
                items = doc["items"] or []
            elif doc.get("kind") == "Event":
                items = [doc]
            else:
                continue

            for item in items:
                if not isinstance(item, dict):
                    continue
                if item.get("type") != "Warning":
                    continue
                # 'Unhealthy' probe events are extremely high volume (100+ per OM task)
                # and mostly expected during startup — they carry no actionable signal.
                # Keep only reasons that indicate real failures or resource pressure.
                reason = item.get("reason", "")
                if reason in ("Unhealthy", "ProbeWarning"):
                    continue
                obj = item.get("involvedObject") or {}
                msg = item.get("message", "")
                pattern = failure_fingerprint(msg)
                pod_name = obj.get("name", "")
                # Deduplicate: same (pattern, pod, reason) is one logical event.
                # Keep the one with the highest count and latest timestamp.
                # Dedup key: first 80 chars of pattern captures the failure class
                # without being thrown by per-pod variation in the tail of the message.
                dedup_key = (pattern[:80], pod_name, reason)
                if dedup_key not in _kube_dedup:
                    _kube_dedup[dedup_key] = {
                        "time": item.get("lastTimestamp") or _now_iso(),
                        "data": {
                            **ctx,
                            "source": "kube_events",
                            "reason": reason,
                            "message": msg,
                            "message_pattern": pattern,
                            "involved_object_kind": obj.get("kind", ""),
                            "involved_object_name": pod_name,
                            "namespace": (item.get("metadata") or {}).get("namespace", ""),
                            "count": item.get("count", 1),
                            "first_timestamp": item.get("firstTimestamp", ""),
                            "last_timestamp": item.get("lastTimestamp", ""),
                            "source_component": (item.get("source") or {}).get("component", ""),
                        },
                    }
                else:
                    # Accumulate count, keep latest timestamp
                    _kube_dedup[dedup_key]["data"]["count"] += item.get("count", 1)
                    _kube_dedup[dedup_key]["data"]["last_timestamp"] = item.get("lastTimestamp", "")

    result = list(_kube_dedup.values())
    log.info("kube Warning events: %d (deduplicated from raw events)", len(result))
    return result


# ---------------------------------------------------------------------------
# Source 2: Agent health status JSON
# ---------------------------------------------------------------------------

def collect_agent_health(logs_dir: Path, ctx: dict) -> list[dict]:
    """Collect per-pod agent health status. Always send — files are tiny (~1KB each)."""
    result = []
    pattern = str(logs_dir / "**" / "*agent-health-status.json")
    files = glob.glob(pattern, recursive=True)
    if not files:
        # Also try flat layout
        files = glob.glob(str(logs_dir / "*agent-health-status.json"))

    for path in files:
        pod_name = Path(path).parent.name if Path(path).parent != logs_dir else Path(path).stem.replace("-agent-health-status", "")
        try:
            with open(path) as f:
                data = json.load(f)
        except (json.JSONDecodeError, OSError) as e:
            log.warning("Failed to parse %s: %s", path, e)
            continue

        mms = data.get("mmsStatus") or {}
        statuses = data.get("statuses") or {}

        for name, status in {**mms, **{k: v for k, v in statuses.items() if k not in mms}}.items():
            is_in_goal = status.get("IsInGoalState", status.get("lastGoalVersionAchieved") is not None)
            error_str = status.get("errorString", "")
            error_code = status.get("errorCode", 0)

            # Find last failed step in most recent plan
            last_failed_step = ""
            plans = status.get("plans") or []
            if plans:
                last_plan = plans[-1]
                for move in reversed(last_plan.get("moves") or []):
                    for step in reversed(move.get("steps") or []):
                        if step.get("result") == "failure":
                            last_failed_step = f"{move.get('move','')}/{step.get('step','')}"
                            break
                    if last_failed_step:
                        break

            result.append({
                "time": _now_iso(),
                "data": {
                    **ctx,
                    "source": "agent_health",
                    "pod_name": pod_name,
                    "process_name": name,
                    "is_in_goal_state": bool(is_in_goal),
                    "last_goal_version_achieved": status.get("lastGoalVersionAchieved", 0),
                    "error_code": error_code,
                    "error_string": error_str,
                    "last_failed_step": last_failed_step,
                },
            })

    log.info("agent health events: %d", len(result))
    return result


# ---------------------------------------------------------------------------
# Source 3: Operator Zap logs (ERROR/WARN only, deduplicated by pattern)
# ---------------------------------------------------------------------------

def collect_operator_errors(logs_dir: Path, ctx: dict) -> list[dict]:
    """Parse operator Zap JSONL logs, keep only ERROR/WARN, deduplicate by msg_pattern."""
    result = []
    patterns = [
        str(logs_dir / "**" / "*mongodb-kubernetes-operator*.log"),
        str(logs_dir / "*mongodb-kubernetes-operator*.log"),
        # Operator pod containers also match this pattern in some dump layouts
        str(logs_dir / "**" / "*-mongodb-kubernetes-operator.log"),
        str(logs_dir / "*-mongodb-kubernetes-operator.log"),
    ]
    files = []
    for p in patterns:
        files.extend(glob.glob(p, recursive=True))
    files = list(set(files))

    # group by fingerprinted message → count occurrences
    buckets: dict[str, dict] = {}  # msg_pattern → first event data

    for path in files:
        try:
            with open(path) as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        entry = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    level = entry.get("level", "").lower()
                    if level not in ("error", "warn", "warning"):
                        continue
                    msg = entry.get("msg", "")
                    pattern = failure_fingerprint(msg)
                    if pattern not in buckets:
                        buckets[pattern] = {
                            "time": entry.get("ts", _now_iso()),
                            "data": {
                                **ctx,
                                "source": "operator_logs",
                                "level": level,
                                "msg": msg,
                                "msg_pattern": pattern,
                                "logger": entry.get("logger", ""),
                                "ts": entry.get("ts", ""),
                                "count": 0,
                                # Include any extra top-level fields from Zap
                                **{k: v for k, v in entry.items()
                                   if k not in ("level", "msg", "ts", "logger")
                                   and isinstance(v, (str, int, float, bool))},
                            },
                        }
                    buckets[pattern]["data"]["count"] += 1
        except OSError as e:
            log.warning("Failed to read %s: %s", path, e)

    result = list(buckets.values())
    log.info("operator error/warn events (deduplicated): %d", len(result))
    return result


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Send e2e log events to Honeycomb")
    parser.add_argument("--logs-dir", required=True, help="Path to the logs directory")
    parser.add_argument("--task-id", default=os.getenv("TASK_ID", "unknown"))
    parser.add_argument("--version-id", default=os.getenv("VERSION_ID", "unknown"))
    parser.add_argument("--dry-run", action="store_true", help="Print events without POSTing")
    parser.add_argument("--max-events", type=int, default=MAX_EVENTS_DEFAULT,
                        help="Hard cap on total events sent (default %(default)s)")
    args = parser.parse_args()

    api_key = os.getenv("HONEYCOMB_API_KEY", "")
    if not api_key and not args.dry_run:
        log.info("HONEYCOMB_API_KEY not set — skipping Honeycomb log ingestion")
        return

    logs_dir = Path(args.logs_dir)
    if not logs_dir.is_dir():
        log.warning("logs dir %s not found — skipping", logs_dir)
        return

    ctx = _base_context(args.task_id, args.version_id)

    all_events: list[dict] = []
    all_events.extend(collect_kube_warning_events(logs_dir, ctx))
    all_events.extend(collect_agent_health(logs_dir, ctx))
    all_events.extend(collect_operator_errors(logs_dir, ctx))

    if len(all_events) > args.max_events:
        log.warning("Capping events at %d (collected %d)", args.max_events, len(all_events))
        all_events = all_events[: args.max_events]

    log.info("Total events to send: %d", len(all_events))
    _post_batch(all_events, api_key, args.dry_run)


if __name__ == "__main__":
    main()
