#!/usr/bin/env bash

set -Eeou pipefail

script_name=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "${script_name}")

# shellcheck disable=SC1091
source "$script_dir/root-context"
# shellcheck disable=SC1091
source "$script_dir/variables/om50"

export KUBE_ENVIRONMENT_NAME=kind
