#!/usr/bin/env bash

set -Eeou pipefail

script_name=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "${script_name}")

# shellcheck disable=SC1091
source "$script_dir/root-context"

export ops_manager_version="cloud_qa"

export CLUSTER_DOMAIN="testdomain.local"

export CUSTOM_MDB_VERSION=6.0.5
