#!/usr/bin/env bash

set -Eeou pipefail

script_name=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "${script_name}")

source "${script_dir}/root-context"
source "${script_dir}/variables/e2e_smoke_base"

export ops_manager_version="cloud_qa"

CUSTOM_OM_VERSION=$(grep -E "^\s*-\s*&ops_manager_70_latest\s+(\S+)\s+#" <"${script_dir}"/../../../.evergreen.yml | awk '{print $3}')
export CUSTOM_OM_VERSION

export CUSTOM_MDB_VERSION=7.0.22 # we only have ibm static images starting with 7.0.22
export KUBE_ENVIRONMENT_NAME=kind
export CLUSTER_TYPE=kind
export MDB_DEFAULT_ARCHITECTURE=static
