#!/usr/bin/env bash

set -Eeou pipefail

script_name=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "${script_name}")

source "${script_dir}/root-context"

export ops_manager_version="cloud_qa"

# This is required to be able to rebuild the om image and use that image which has been rebuild
export OPS_MANAGER_REGISTRY=268558157000.dkr.ecr.us-east-1.amazonaws.com/dev
CUSTOM_OM_VERSION=$(grep -E "^\s*-\s*&ops_manager_70_latest\s+(\S+)\s+#" <"${script_dir}"/../../../.evergreen.yml | awk '{print $3}')
export CUSTOM_OM_VERSION

export CUSTOM_MDB_VERSION=6.0.5-ent
export CUSTOM_MDB_PREV_VERSION=5.0.7-ent
export KUBE_ENVIRONMENT_NAME=minikube
export CLUSTER_TYPE=minikube
export CONTAINER_RUNTIME=podman

# TODO: change once we have image building
export BASE_REPO_URL="268558157000.dkr.ecr.us-east-1.amazonaws.com/lucian.tosa"
export REGISTRY="${BASE_REPO_URL}"
export INIT_DATABASE_IMAGE_REPOSITORY="${BASE_REPO_URL}/mongodb-kubernetes-init-database"
export OPERATOR_REGISTRY=${BASE_REPO_URL}
export DATABASE_REGISTRY=${BASE_REPO_URL}
export INIT_DATABASE_REGISTRY=${BASE_REPO_URL}

