#!/usr/bin/env bash

set -Eeou pipefail

script_name=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "${script_name}")

source "${script_dir}/root-context"
source "${script_dir}/variables/om70"

export KUBE_ENVIRONMENT_NAME=kind

# this is the only variant to fully deactivate telemetry.
# the test harness translates this into OperatorConfig.spec.telemetry.mode=Disabled, exercising the
# telemetry master switch.
export MDB_OPERATOR_TELEMETRY_ENABLED=false
