#!/usr/bin/env bash

set -Eeou pipefail -o posix

script_name=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "${script_name}")

source "${script_dir}/root-context"

export KUBE_ENVIRONMENT_NAME=multi
export CLUSTER_NAME="kind-e2e-cluster-1"
export MEMBER_CLUSTERS="kind-e2e-cluster-1 kind-e2e-cluster-2"
export CENTRAL_CLUSTER=kind-e2e-cluster-1
export test_pod_cluster=kind-e2e-cluster-1
export ops_manager_version="cloud_qa"

export MDB_DEFAULT_ARCHITECTURE=static
export CUSTOM_MDB_VERSION=6.0.5
