#!/usr/bin/env bash

set -Eeou pipefail -o posix

script_name=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "${script_name}")

source "${script_dir}/root-context"
source "${script_dir}/variables/om70"

# This is required to be able to rebuild the om image and use that image which has been rebuild
export MDB_MAX_CONCURRENT_RECONCILES=10
export MDB_DEFAULT_ARCHITECTURE=static
export KUBE_ENVIRONMENT_NAME=performance
