#!/usr/bin/env bash

set -Eeou pipefail

script_name=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "${script_name}")

source "${script_dir}/root-context"

export ops_manager_version="cloud_qa"

export CUSTOM_MDB_VERSION=8.0.12-ent
export KUBE_ENVIRONMENT_NAME=kind
export CLUSTER_TYPE=kind

# During release the meko-tests image is pushed to a staging registry. We don't want to push it to production registry
export MEKO_TESTS_REGISTRY="268558157000.dkr.ecr.us-east-1.amazonaws.com/staging"
