#!/usr/bin/env bash

set -Eeou pipefail

script_name=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "${script_name}")

source "${script_dir}/e2e_static_multi_cluster_om_appdb"
source "${script_dir}/variables/om80"
source "${script_dir}/variables/mongodb_slim"

export CUSTOM_MDB_VERSION="${SLIM_MDB_VERSION}-ubi${SLIM_UBI_VERSION}-slim"
export CUSTOM_APPDB_VERSION="${SLIM_MDB_VERSION}-ubi${SLIM_UBI_VERSION}-slim"