#!/usr/bin/env bash

set -Eeou pipefail

script_name=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "${script_name}")

source "${script_dir}/root-context"
source "${script_dir}/variables/om70"

export MDB_DEFAULT_ARCHITECTURE=static
# For static smoke tests we need the previous MDB version to have a ubi9 binary
export CUSTOM_MDB_PREV_VERSION=6.0.5
