#!/usr/bin/env bash

set -Eeou pipefail

script_name=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "${script_name}")

source "${script_dir}/root-context"
source "${script_dir}/variables/om70"

export ops_manager_version="cloud_qa"
export MDB_DEFAULT_ARCHITECTURE=static

export CUSTOM_MDB_VERSION=6.0.16
# We can't use a 5.0.x version for this static variant because there's no UBI9 image for the 5.0.x series
export CUSTOM_MDB_PREV_VERSION=6.0.5
