#!/usr/bin/env bash

set -Eeou pipefail

script_name=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "${script_name}")

source "$script_dir/root-context"
source "$script_dir/variables/om60"

export ops_manager_version="cloud_qa"
export MDB_DEFAULT_ARCHITECTURE=static

export e2e_cloud_qa_orgid_owner="${e2e_cloud_qa_orgid_owner_static_2}"
export e2e_cloud_qa_apikey_owner="${e2e_cloud_qa_apikey_owner_static_2}"
export e2e_cloud_qa_user_owner="${e2e_cloud_qa_user_owner_static_2}"