#!/usr/bin/env bash

set -Eeou pipefail

script_name=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "${script_name}")

source "${script_dir}/root-context"
source "${script_dir}/variables/om70"

export DATABASE_REGISTRY="${QUAY_REGISTRY}"
export APPDB_REGISTRY="${QUAY_REGISTRY}"
export INIT_OPS_MANAGER_REGISTRY="${QUAY_REGISTRY}"
export OPS_MANAGER_REGISTRY="${QUAY_REGISTRY}"
export OPERATOR_REGISTRY="${QUAY_REGISTRY}"
export INIT_IMAGES_REGISTRY="${QUAY_REGISTRY}"
export INIT_APPDB_REGISTRY="${QUAY_REGISTRY}"
export INIT_DATABASE_REGISTRY="${QUAY_REGISTRY}"
OPERATOR_VERSION="$(./scripts/release/calculate_next_version.py --initial_version '1.1.0' --initial_commit_sha '13431e8fa6ae9ac8476034093e18c7da162fbd45')"
export OPERATOR_VERSION
INIT_DATABASE_VERSION="$OPERATOR_VERSION"
export INIT_DATABASE_VERSION
INIT_APPDB_VERSION="$OPERATOR_VERSION"
export INIT_APPDB_VERSION
INIT_OPS_MANAGER_VERSION="$OPERATOR_VERSION"
export INIT_OPS_MANAGER_VERSION
DATABASE_VERSION="$OPERATOR_VERSION"
export DATABASE_VERSION
export MDB_DEFAULT_ARCHITECTURE=static
# For static smoke tests we need the previous MDB version to have a ubi9 binary
export CUSTOM_MDB_PREV_VERSION=6.0.5
