#!/usr/bin/env bash

set -Eeou pipefail

script_name=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "${script_name}")

source "${script_dir}/root-context"
source "${script_dir}/variables/e2e_smoke_base"
source "${script_dir}/variables/e2e_ibm_smoke_base"

CUSTOM_OM_VERSION=$(grep -E "^\s*-\s*&ops_manager_70_latest\s+(\S+)\s+#" <"${script_dir}"/../../../.evergreen.yml | awk '{print $3}')
export CUSTOM_OM_VERSION

export MDB_DEFAULT_ARCHITECTURE=static
# MDB supports s390x on RHEL9 only from 8.0.12 onwards
export CUSTOM_MDB_VERSION=8.0.12-ent
