#!/usr/bin/env bash

set -Eeou pipefail

script_name=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "${script_name}")

source "${script_dir}/root-context"
source "${script_dir}/variables/e2e_ibm_smoke_base"

# This is required to be able to rebuild the om image and use that image which has been rebuild
export OPS_MANAGER_REGISTRY=268558157000.dkr.ecr.us-east-1.amazonaws.com/dev
CUSTOM_OM_VERSION=$(grep -E "^\s*-\s*&ops_manager_70_latest\s+(\S+)\s+#" <"${script_dir}"/../../../.evergreen.yml | awk '{print $3}')
export CUSTOM_OM_VERSION
export MDB_DEFAULT_ARCHITECTURE=static
# MDB doesn't fully support s390x for 7.x.x on RHEL9
export CUSTOM_MDB_VERSION=8.0.12
