#!/usr/bin/env bash

set -Eeou pipefail

script_name=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "${script_name}")

source "$script_dir/root-context"
source "$script_dir/variables/om60"

export ops_manager_version="cloud_qa"
export MDB_DEFAULT_ARCHITECTURE=static
