#!/usr/bin/env bash

# This context is usable when generating OLM bundles locally that will be deployed on OpenShift.
# OpenShift must have managed security context enabled.

set -Eeou pipefail

script_name=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "${script_name}")

source "${script_dir}/root-context"

export MANAGED_SECURITY_CONTEXT="true"
