#!/usr/bin/env bash

set -Eeou pipefail

# This context is the defacto local development default context, where we set sane defaults for everyone to be able to get started.
# This is the first context we source, therefore we can easily overwrite this. in the private-context or overrides.
# In case you don't agree with those defaults you can override them im your private-context without affecting
# others.

script_name=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "${script_name}")

PROJECT_DIR=$(realpath "${script_dir}/../../../")
# DEPRECATED: usage of workdir is deprecated, use PROJECT_DIR instead
workdir=$(realpath "${script_dir}/../../../")
export PROJECT_DIR
export workdir

# Here are all the required registries used by the Operator. We are defaulting to images ecr for most, some to quay
# The main registry to use for local test runs
# - global: <registry>/dev is the shared registry
# - dedicated: <registry>/<my-registry>
# Note: in our root-context we default the image tag to latest, if VERSION_ID is not preset on your machine
# Note2: For quick local development defaults we only use shared images
export QUAY_REGISTRY=quay.io/mongodb
export BASE_REPO_URL_SHARED="268558157000.dkr.ecr.us-east-1.amazonaws.com/dev"
# Note: the Operator registry (OPERATOR_REGISTRY variable) is defined in the private context
export REGISTRY="${BASE_REPO_URL_SHARED}"

export INIT_IMAGES_REGISTRY=${INIT_IMAGES_REGISTRY:-"${REGISTRY}"}

export INIT_APPDB_REGISTRY="${BASE_REPO_URL_SHARED}"
export INIT_OPS_MANAGER_REGISTRY=${BASE_REPO_URL_SHARED:-"${QUAY_REGISTRY}"}
export INIT_DATABASE_REGISTRY=${BASE_REPO_URL_SHARED:-"${QUAY_REGISTRY}"}
export INIT_DATABASE_IMAGE_REPOSITORY="${BASE_REPO_URL_SHARED}/mongodb-kubernetes-init-database"
export DATABASE_REGISTRY=${BASE_REPO_URL_SHARED:-"${QUAY_REGISTRY}"}
export OPS_MANAGER_REGISTRY="${QUAY_REGISTRY}"
export MONGODB_REPO_URL="${QUAY_REGISTRY}"
export APPDB_REGISTRY="${QUAY_REGISTRY}"
export MONGODB_ENTERPRISE_DATABASE_IMAGE="${INIT_IMAGES_REGISTRY}/mongodb-kubernetes-database"
export MDB_AGENT_IMAGE_OPERATOR_VERSION=latest
export MDB_AGENT_IMAGE_REPOSITORY="${BASE_REPO_URL_SHARED}/mongodb-agent-ubi"
export AGENT_BASE_REGISTRY=${BASE_REPO_URL_SHARED}
export AGENT_IMAGE="268558157000.dkr.ecr.us-east-1.amazonaws.com/dev/mongodb-agent-ubi:12.0.30.7791-1"

# these are needed to deploy OM
export INIT_APPDB_IMAGE_REPOSITORY="${INIT_IMAGES_REGISTRY}/mongodb-kubernetes-init-appdb"
export OPS_MANAGER_IMAGE_REPOSITORY="${QUAY_REGISTRY}/mongodb-enterprise-ops-manager-ubi"
export INIT_OPS_MANAGER_IMAGE_REPOSITORY="${INIT_IMAGES_REGISTRY}/mongodb-kubernetes-init-ops-manager"

# Environment variable needed for local development
# Used in controllers/operator/mongodbopsmanager_controller.go
# The file is created by scripts/dev/prepare_local_e2e_run.sh
export MDB_OM_VERSION_MAPPING_PATH="${PROJECT_DIR}/release.json"
export ENV_FILE="${PROJECT_DIR}/.ops-manager-env"
export NAMESPACE_FILE="${PROJECT_DIR}/.namespace"

# TO ensure we don't release by accident via pipeline.py
export skip_tags="release"

# This setting is set if you want to remove your namespaces after running the tests
export ALWAYS_REMOVE_TESTING_NAMESPACE="true"

# MCO settings
## whether we want to run cleanup after the run
export PERFORM_CLEANUP=false

# TODO: unify this with MEKO local operator
## Should local runs use the local operator
export MDB_LOCAL_OPERATOR=true
