#!/usr/bin/env bash

set -Eeou pipefail

# This context is the defacto local development default context, where we set sane defaults for everyone to be able to get started.
# This is the first context we source, therefore we can easily overwrite this. in the private-context or overrides.
# In case you don't agree with those defaults you can override them im your private-context without affecting
# others.

script_name=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "${script_name}")

PROJECT_DIR=$(realpath "${script_dir}/../../../")
# DEPRECATED: usage of workdir is deprecated, use PROJECT_DIR instead
workdir=$(realpath "${script_dir}/../../../")
export PROJECT_DIR
export workdir

# Here are all the required registries used by the Operator. We are defaulting to images ecr for most, some to quay
# The main registry to use for local test runs
# - global: <registry>/dev is the shared registry
# - dedicated: <registry>/<my-registry>
# Note: in our root-context we default the image tag to latest, if OPERATOR_VERSION is not preset on your machine
# Note2: For quick local development defaults we only use shared images
export QUAY_REGISTRY=quay.io/mongodb
export BASE_REPO_URL_SHARED="268558157000.dkr.ecr.us-east-1.amazonaws.com/staging"
# Note: the Operator registry (OPERATOR_REGISTRY variable) is defined in the private context
export REGISTRY="${BASE_REPO_URL_SHARED}"

# Environment variable needed for local development
# Used in controllers/operator/mongodbopsmanager_controller.go
# The file is created by scripts/dev/prepare_local_e2e_run.sh
export MDB_OM_VERSION_MAPPING_PATH="${PROJECT_DIR}/release.json"
export ENV_FILE="${PROJECT_DIR}/.ops-manager-env"
export NAMESPACE_FILE="${PROJECT_DIR}/.namespace"

# This setting is set if you want to remove your namespaces after running the tests
export ALWAYS_REMOVE_TESTING_NAMESPACE="true"

# MCO settings
## whether we want to run cleanup after the run
export PERFORM_CLEANUP=false
