#!/usr/bin/env bash

# this context file is for code snippets running on kind clusters
set -Eeou pipefail

# overrides of public env_variables.sh
script_name=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "${script_name}")

source "${script_dir}/root-context"

export CODE_SNIPPETS_FLAVOR=e2e_prerelease
export CODE_SNIPPETS_COMMIT_OUTPUT=true
export ops_manager_version="cloud_qa"

export PRERELEASE_IMAGE_PULLSECRET="${PRERELEASE_PULLSECRET_DOCKERCONFIGJSON}"
