#!/usr/bin/env bash

# this context file is for code snippets running on GKE clusters
set -Eeou pipefail

# overrides of public env_variables.sh
script_name=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "${script_name}")

source "${script_dir}/root-context"

export NAMESPACE=mongodb
export CODE_SNIPPETS_FLAVOR=e2e_private
