#!/usr/bin/env bash

# this context file is for code snippets running on GKE clusters
set -Eeou pipefail

# overrides of public env_variables.sh
script_name=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "${script_name}")

source "${script_dir}/root-context"

export KUBE_ENVIRONMENT_NAME=multi

export MDB_GKE_PROJECT="scratch-kubernetes-team"
# shellcheck disable=SC2154
export K8S_CLUSTER_SUFFIX="${K8S_CLUSTER_SUFFIX:-"-${version_id}-${RANDOM}"}"

# we reset evg host to use a default ~/.kube/config for GKE instead of the one from evg host
export EVG_HOST_NAME=""

# ENV_VARIABLES.SH overrides
export OPERATOR_ADDITIONAL_HELM_VALUES=""
export OPERATOR_HELM_CHART=""
export CODE_SNIPPETS_COMMIT_OUTPUT=true
