#!/usr/bin/env bash

# this context file is for executing the following snippets for docs:
#  public/samples/ops-manager-multi-cluster
set -Eeou pipefail

script_name=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "${script_name}")

source public/samples/ops-manager-multi-cluster/env_variables.sh

source "${script_dir}/root-context"
source "${script_dir}/variables/om60"

export NAMESPACE="mongodb-operator"
export WATCH_NAMESPACE="mongodb"
export KUBE_ENVIRONMENT_NAME=multi
export CLUSTER_NAME="${K8S_CLUSTER_0_CONTEXT_NAME}"
export MEMBER_CLUSTERS="${K8S_CLUSTER_0_CONTEXT_NAME} ${K8S_CLUSTER_1_CONTEXT_NAME} ${K8S_CLUSTER_2_CONTEXT_NAME}"
export CENTRAL_CLUSTER="${K8S_CLUSTER_0_CONTEXT_NAME}"
export test_pod_cluster=${K8S_CLUSTER_0_CONTEXT_NAME}
export ops_manager_version="cloud_qa"
# we reset evg host to use a default ~/.kube/config for GKE instead of the one from evg host
export EVG_HOST_NAME=""

source scripts/funcs/operator_deployment
# overrides of public env_variables.sh
OPERATOR_ADDITIONAL_HELM_VALUES=$(get_operator_helm_values | tr ' ' ',')
export OPERATOR_ADDITIONAL_HELM_VALUES
export MDB_GKE_PROJECT="scratch-kubernetes-team"
export OPERATOR_HELM_CHART=../../../helm_chart



