#!/usr/bin/env bash

# this context file is for *manually* executing the public/samples/ops-manager-multi-cluster from official helm charts
#
set -Eeou pipefail

source public/samples/ops-manager-multi-cluster/env_variables.sh

# overrides of public env_variables.sh
export MDB_GKE_PROJECT="scratch-kubernetes-team"



