#!/usr/bin/env bash

# this context file is for code snippets running on GKE clusters
set -Eeou pipefail

# overrides of public env_variables.sh
script_name=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "${script_name}")

source "${script_dir}/root-context"

source "${script_dir}/funcs/gke"
K8S_CLUSTER_SUFFIX="$(create_k8s_cluster_suffix)"
export K8S_CLUSTER_SUFFIX

export KUBE_ENVIRONMENT_NAME=multi

export MDB_GKE_PROJECT="scratch-kubernetes-team"

# we reset evg host to use a default ~/.kube/config for GKE instead of the one from evg host
export EVG_HOST_NAME=""

# ENV_VARIABLES.SH overrides
export OPERATOR_HELM_CHART_VERSION="${OPERATOR_VERSION}"
export OPERATOR_ADDITIONAL_HELM_VALUES=""
export OPERATOR_HELM_CHART=""
