#!/usr/bin/env bash

set -Eeou pipefail

script_name=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "${script_name}")

# This will be removed once the main branch of the Static Containers will be merged.
source "${script_dir}/root-context"

export preflight_submit=false
export include_tags=release
