//go:build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package status

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Common) DeepCopyInto(out *Common) {
	*out = *in
	if in.ResourcesNotReady != nil {
		in, out := &in.ResourcesNotReady, &out.ResourcesNotReady
		*out = make([]ResourceNotReady, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PVCs != nil {
		in, out := &in.PVCs, &out.PVCs
		*out = make(PVCS, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Common.
func (in *Common) DeepCopy() *Common {
	if in == nil {
		return nil
	}
	out := new(Common)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongodbShardedClusterSizeConfig) DeepCopyInto(out *MongodbShardedClusterSizeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongodbShardedClusterSizeConfig.
func (in *MongodbShardedClusterSizeConfig) DeepCopy() *MongodbShardedClusterSizeConfig {
	if in == nil {
		return nil
	}
	out := new(MongodbShardedClusterSizeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongodbShardedSizeStatusInClusters) DeepCopyInto(out *MongodbShardedSizeStatusInClusters) {
	*out = *in
	if in.ShardMongodsInClusters != nil {
		in, out := &in.ShardMongodsInClusters, &out.ShardMongodsInClusters
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MongosCountInClusters != nil {
		in, out := &in.MongosCountInClusters, &out.MongosCountInClusters
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ConfigServerMongodsInClusters != nil {
		in, out := &in.ConfigServerMongodsInClusters, &out.ConfigServerMongodsInClusters
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongodbShardedSizeStatusInClusters.
func (in *MongodbShardedSizeStatusInClusters) DeepCopy() *MongodbShardedSizeStatusInClusters {
	if in == nil {
		return nil
	}
	out := new(MongodbShardedSizeStatusInClusters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceError) DeepCopyInto(out *ResourceError) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceError.
func (in *ResourceError) DeepCopy() *ResourceError {
	if in == nil {
		return nil
	}
	out := new(ResourceError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceNotReady) DeepCopyInto(out *ResourceNotReady) {
	*out = *in
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]ResourceError, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceNotReady.
func (in *ResourceNotReady) DeepCopy() *ResourceNotReady {
	if in == nil {
		return nil
	}
	out := new(ResourceNotReady)
	in.DeepCopyInto(out)
	return out
}
