//go:build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package role

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMongoDBRole) DeepCopyInto(out *ClusterMongoDBRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMongoDBRole.
func (in *ClusterMongoDBRole) DeepCopy() *ClusterMongoDBRole {
	if in == nil {
		return nil
	}
	out := new(ClusterMongoDBRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterMongoDBRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMongoDBRoleBuilder) DeepCopyInto(out *ClusterMongoDBRoleBuilder) {
	*out = *in
	if in.finalizers != nil {
		in, out := &in.finalizers, &out.finalizers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.annotations != nil {
		in, out := &in.annotations, &out.annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.mongoDBRole.DeepCopyInto(&out.mongoDBRole)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMongoDBRoleBuilder.
func (in *ClusterMongoDBRoleBuilder) DeepCopy() *ClusterMongoDBRoleBuilder {
	if in == nil {
		return nil
	}
	out := new(ClusterMongoDBRoleBuilder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMongoDBRoleList) DeepCopyInto(out *ClusterMongoDBRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterMongoDBRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMongoDBRoleList.
func (in *ClusterMongoDBRoleList) DeepCopy() *ClusterMongoDBRoleList {
	if in == nil {
		return nil
	}
	out := new(ClusterMongoDBRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterMongoDBRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMongoDBRoleSpec) DeepCopyInto(out *ClusterMongoDBRoleSpec) {
	*out = *in
	in.MongoDBRole.DeepCopyInto(&out.MongoDBRole)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMongoDBRoleSpec.
func (in *ClusterMongoDBRoleSpec) DeepCopy() *ClusterMongoDBRoleSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterMongoDBRoleSpec)
	in.DeepCopyInto(out)
	return out
}
