//go:build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package role

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBCustomRole) DeepCopyInto(out *MongoDBCustomRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBCustomRole.
func (in *MongoDBCustomRole) DeepCopy() *MongoDBCustomRole {
	if in == nil {
		return nil
	}
	out := new(MongoDBCustomRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongoDBCustomRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBCustomRoleList) DeepCopyInto(out *MongoDBCustomRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MongoDBCustomRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBCustomRoleList.
func (in *MongoDBCustomRoleList) DeepCopy() *MongoDBCustomRoleList {
	if in == nil {
		return nil
	}
	out := new(MongoDBCustomRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongoDBCustomRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBCustomRoleSpec) DeepCopyInto(out *MongoDBCustomRoleSpec) {
	*out = *in
	in.MongoDBRole.DeepCopyInto(&out.MongoDBRole)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBCustomRoleSpec.
func (in *MongoDBCustomRoleSpec) DeepCopy() *MongoDBCustomRoleSpec {
	if in == nil {
		return nil
	}
	out := new(MongoDBCustomRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBCustomRoleStatus) DeepCopyInto(out *MongoDBCustomRoleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBCustomRoleStatus.
func (in *MongoDBCustomRoleStatus) DeepCopy() *MongoDBCustomRoleStatus {
	if in == nil {
		return nil
	}
	out := new(MongoDBCustomRoleStatus)
	in.DeepCopyInto(out)
	return out
}
