---
# Source: mongodb-kubernetes/templates/operator-roles-clustermongodbroles.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-kubernetes-operator-mongodb-cluster-mongodb-role
rules:
  - apiGroups:
      - mongodb.com
    verbs:
      - '*'
    resources:
      - clustermongodbroles
---
# Source: mongodb-kubernetes/templates/operator-roles-clustermongodbroles.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-kubernetes-operator-mongodb-cluster-mongodb-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mongodb-kubernetes-operator-mongodb-cluster-mongodb-role
subjects:
  - kind: ServiceAccount
    name: mongodb-kubernetes-operator
    namespace: mongodb
