---
# Source: mongodb-kubernetes/templates/operator-roles-telemetry.yaml
# Additional ClusterRole for clusterVersionDetection
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-kubernetes-operator-cluster-telemetry
rules:
  # Non-resource URL permissions
  - nonResourceURLs:
      - "/version"
    verbs:
      - get
  # Cluster-scoped resource permissions
  - apiGroups:
      - ''
    resources:
      - namespaces
    resourceNames:
      - kube-system
    verbs:
      - get
  - apiGroups:
      - ''
    resources:
      - nodes
    verbs:
      - list
---
# Source: mongodb-kubernetes/templates/operator-roles-telemetry.yaml
# ClusterRoleBinding for clusterVersionDetection
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-kubernetes-operator-mongodb-cluster-telemetry-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mongodb-kubernetes-operator-cluster-telemetry
subjects:
  - kind: ServiceAccount
    name: mongodb-kubernetes-operator
    namespace: mongodb
