//go:build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package mdb

import (
	"github.com/mongodb/mongodb-kubernetes/api/v1/status"
	"github.com/mongodb/mongodb-kubernetes/mongodb-community-operator/api/v1"
	"github.com/mongodb/mongodb-kubernetes/mongodb-community-operator/api/v1/common"
	"github.com/mongodb/mongodb-kubernetes/mongodb-community-operator/pkg/automationconfig"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentAuthentication) DeepCopyInto(out *AgentAuthentication) {
	*out = *in
	in.AutomationPasswordSecretRef.DeepCopyInto(&out.AutomationPasswordSecretRef)
	in.ClientCertificateSecretRefWrap.DeepCopyInto(&out.ClientCertificateSecretRefWrap)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentAuthentication.
func (in *AgentAuthentication) DeepCopy() *AgentAuthentication {
	if in == nil {
		return nil
	}
	out := new(AgentAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentConfig) DeepCopyInto(out *AgentConfig) {
	*out = *in
	in.BackupAgent.DeepCopyInto(&out.BackupAgent)
	in.MonitoringAgent.DeepCopyInto(&out.MonitoringAgent)
	in.Mongod.DeepCopyInto(&out.Mongod)
	in.ReadinessProbe.DeepCopyInto(&out.ReadinessProbe)
	if in.StartupParameters != nil {
		in, out := &in.StartupParameters, &out.StartupParameters
		*out = make(StartupParameters, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LogRotate != nil {
		in, out := &in.LogRotate, &out.LogRotate
		*out = new(automationconfig.CrdLogRotate)
		**out = **in
	}
	if in.SystemLog != nil {
		in, out := &in.SystemLog, &out.SystemLog
		*out = new(automationconfig.SystemLog)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentConfig.
func (in *AgentConfig) DeepCopy() *AgentConfig {
	if in == nil {
		return nil
	}
	out := new(AgentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentLoggingMongodConfig) DeepCopyInto(out *AgentLoggingMongodConfig) {
	*out = *in
	if in.LogRotate != nil {
		in, out := &in.LogRotate, &out.LogRotate
		*out = new(automationconfig.CrdLogRotate)
		**out = **in
	}
	if in.AuditLogRotate != nil {
		in, out := &in.AuditLogRotate, &out.AuditLogRotate
		*out = new(automationconfig.CrdLogRotate)
		**out = **in
	}
	if in.SystemLog != nil {
		in, out := &in.SystemLog, &out.SystemLog
		*out = new(automationconfig.SystemLog)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentLoggingMongodConfig.
func (in *AgentLoggingMongodConfig) DeepCopy() *AgentLoggingMongodConfig {
	if in == nil {
		return nil
	}
	out := new(AgentLoggingMongodConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Authentication) DeepCopyInto(out *Authentication) {
	*out = *in
	if in.Modes != nil {
		in, out := &in.Modes, &out.Modes
		*out = make([]AuthMode, len(*in))
		copy(*out, *in)
	}
	if in.Ldap != nil {
		in, out := &in.Ldap, &out.Ldap
		*out = new(Ldap)
		(*in).DeepCopyInto(*out)
	}
	if in.OIDCProviderConfigs != nil {
		in, out := &in.OIDCProviderConfigs, &out.OIDCProviderConfigs
		*out = make([]OIDCProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Agents.DeepCopyInto(&out.Agents)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Authentication.
func (in *Authentication) DeepCopy() *Authentication {
	if in == nil {
		return nil
	}
	out := new(Authentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthenticationRestriction) DeepCopyInto(out *AuthenticationRestriction) {
	*out = *in
	if in.ClientSource != nil {
		in, out := &in.ClientSource, &out.ClientSource
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ServerAddress != nil {
		in, out := &in.ServerAddress, &out.ServerAddress
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticationRestriction.
func (in *AuthenticationRestriction) DeepCopy() *AuthenticationRestriction {
	if in == nil {
		return nil
	}
	out := new(AuthenticationRestriction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Backup) DeepCopyInto(out *Backup) {
	*out = *in
	if in.SnapshotSchedule != nil {
		in, out := &in.SnapshotSchedule, &out.SnapshotSchedule
		*out = new(SnapshotSchedule)
		(*in).DeepCopyInto(*out)
	}
	if in.Encryption != nil {
		in, out := &in.Encryption, &out.Encryption
		*out = new(Encryption)
		(*in).DeepCopyInto(*out)
	}
	if in.AssignmentLabels != nil {
		in, out := &in.AssignmentLabels, &out.AssignmentLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Backup.
func (in *Backup) DeepCopy() *Backup {
	if in == nil {
		return nil
	}
	out := new(Backup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupAgent) DeepCopyInto(out *BackupAgent) {
	*out = *in
	if in.LogRotate != nil {
		in, out := &in.LogRotate, &out.LogRotate
		*out = new(LogRotateForBackupAndMonitoring)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupAgent.
func (in *BackupAgent) DeepCopy() *BackupAgent {
	if in == nil {
		return nil
	}
	out := new(BackupAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupStatus) DeepCopyInto(out *BackupStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupStatus.
func (in *BackupStatus) DeepCopy() *BackupStatus {
	if in == nil {
		return nil
	}
	out := new(BackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpecItem) DeepCopyInto(out *ClusterSpecItem) {
	*out = *in
	if in.ExternalAccessConfiguration != nil {
		in, out := &in.ExternalAccessConfiguration, &out.ExternalAccessConfiguration
		*out = new(ExternalAccessConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.MemberConfig != nil {
		in, out := &in.MemberConfig, &out.MemberConfig
		*out = make([]automationconfig.MemberOptions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StatefulSetConfiguration != nil {
		in, out := &in.StatefulSetConfiguration, &out.StatefulSetConfiguration
		*out = (*in).DeepCopy()
	}
	if in.PodSpec != nil {
		in, out := &in.PodSpec, &out.PodSpec
		*out = new(MongoDbPodSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpecItem.
func (in *ClusterSpecItem) DeepCopy() *ClusterSpecItem {
	if in == nil {
		return nil
	}
	out := new(ClusterSpecItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpecItemOverride) DeepCopyInto(out *ClusterSpecItemOverride) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = new(int)
		**out = **in
	}
	if in.MemberConfig != nil {
		in, out := &in.MemberConfig, &out.MemberConfig
		*out = make([]automationconfig.MemberOptions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StatefulSetConfiguration != nil {
		in, out := &in.StatefulSetConfiguration, &out.StatefulSetConfiguration
		*out = (*in).DeepCopy()
	}
	if in.PodSpec != nil {
		in, out := &in.PodSpec, &out.PodSpec
		*out = new(MongoDbPodSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpecItemOverride.
func (in *ClusterSpecItemOverride) DeepCopy() *ClusterSpecItemOverride {
	if in == nil {
		return nil
	}
	out := new(ClusterSpecItemOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ClusterSpecList) DeepCopyInto(out *ClusterSpecList) {
	{
		in := &in
		*out = make(ClusterSpecList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpecList.
func (in ClusterSpecList) DeepCopy() ClusterSpecList {
	if in == nil {
		return nil
	}
	out := new(ClusterSpecList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapRef) DeepCopyInto(out *ConfigMapRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapRef.
func (in *ConfigMapRef) DeepCopy() *ConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(ConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionSpec) DeepCopyInto(out *ConnectionSpec) {
	*out = *in
	in.SharedConnectionSpec.DeepCopyInto(&out.SharedConnectionSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionSpec.
func (in *ConnectionSpec) DeepCopy() *ConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(ConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerResourceRequirements) DeepCopyInto(out *ContainerResourceRequirements) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerResourceRequirements.
func (in *ContainerResourceRequirements) DeepCopy() *ContainerResourceRequirements {
	if in == nil {
		return nil
	}
	out := new(ContainerResourceRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Credentials) DeepCopyInto(out *Credentials) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Credentials.
func (in *Credentials) DeepCopy() *Credentials {
	if in == nil {
		return nil
	}
	out := new(Credentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DbCommonSpec) DeepCopyInto(out *DbCommonSpec) {
	*out = *in
	if in.FeatureCompatibilityVersion != nil {
		in, out := &in.FeatureCompatibilityVersion, &out.FeatureCompatibilityVersion
		*out = new(string)
		**out = **in
	}
	in.Agent.DeepCopyInto(&out.Agent)
	in.ConnectionSpec.DeepCopyInto(&out.ConnectionSpec)
	if in.ExternalAccessConfiguration != nil {
		in, out := &in.ExternalAccessConfiguration, &out.ExternalAccessConfiguration
		*out = new(ExternalAccessConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Persistent != nil {
		in, out := &in.Persistent, &out.Persistent
		*out = new(bool)
		**out = **in
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(Security)
		(*in).DeepCopyInto(*out)
	}
	if in.Connectivity != nil {
		in, out := &in.Connectivity, &out.Connectivity
		*out = new(MongoDBConnectivity)
		(*in).DeepCopyInto(*out)
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(Backup)
		(*in).DeepCopyInto(*out)
	}
	if in.Prometheus != nil {
		in, out := &in.Prometheus, &out.Prometheus
		*out = new(v1.Prometheus)
		**out = **in
	}
	if in.StatefulSetConfiguration != nil {
		in, out := &in.StatefulSetConfiguration, &out.StatefulSetConfiguration
		*out = (*in).DeepCopy()
	}
	if in.AdditionalMongodConfig != nil {
		in, out := &in.AdditionalMongodConfig, &out.AdditionalMongodConfig
		*out = (*in).DeepCopy()
	}
	if in.DuplicateServiceObjects != nil {
		in, out := &in.DuplicateServiceObjects, &out.DuplicateServiceObjects
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DbCommonSpec.
func (in *DbCommonSpec) DeepCopy() *DbCommonSpec {
	if in == nil {
		return nil
	}
	out := new(DbCommonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Encryption) DeepCopyInto(out *Encryption) {
	*out = *in
	if in.Kmip != nil {
		in, out := &in.Kmip, &out.Kmip
		*out = new(KmipConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Encryption.
func (in *Encryption) DeepCopy() *Encryption {
	if in == nil {
		return nil
	}
	out := new(Encryption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in EnvironmentVariables) DeepCopyInto(out *EnvironmentVariables) {
	{
		in := &in
		*out = make(EnvironmentVariables, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentVariables.
func (in EnvironmentVariables) DeepCopy() EnvironmentVariables {
	if in == nil {
		return nil
	}
	out := new(EnvironmentVariables)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalAccessConfiguration) DeepCopyInto(out *ExternalAccessConfiguration) {
	*out = *in
	in.ExternalService.DeepCopyInto(&out.ExternalService)
	if in.ExternalDomain != nil {
		in, out := &in.ExternalDomain, &out.ExternalDomain
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalAccessConfiguration.
func (in *ExternalAccessConfiguration) DeepCopy() *ExternalAccessConfiguration {
	if in == nil {
		return nil
	}
	out := new(ExternalAccessConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalServiceConfiguration) DeepCopyInto(out *ExternalServiceConfiguration) {
	*out = *in
	if in.SpecWrapper != nil {
		in, out := &in.SpecWrapper, &out.SpecWrapper
		*out = (*in).DeepCopy()
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalServiceConfiguration.
func (in *ExternalServiceConfiguration) DeepCopy() *ExternalServiceConfiguration {
	if in == nil {
		return nil
	}
	out := new(ExternalServiceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InheritedRole) DeepCopyInto(out *InheritedRole) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InheritedRole.
func (in *InheritedRole) DeepCopy() *InheritedRole {
	if in == nil {
		return nil
	}
	out := new(InheritedRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmipConfig) DeepCopyInto(out *KmipConfig) {
	*out = *in
	out.Client = in.Client
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmipConfig.
func (in *KmipConfig) DeepCopy() *KmipConfig {
	if in == nil {
		return nil
	}
	out := new(KmipConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ldap) DeepCopyInto(out *Ldap) {
	*out = *in
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TransportSecurity != nil {
		in, out := &in.TransportSecurity, &out.TransportSecurity
		*out = new(TransportSecurity)
		**out = **in
	}
	if in.ValidateLDAPServerConfig != nil {
		in, out := &in.ValidateLDAPServerConfig, &out.ValidateLDAPServerConfig
		*out = new(bool)
		**out = **in
	}
	if in.CAConfigMapRef != nil {
		in, out := &in.CAConfigMapRef, &out.CAConfigMapRef
		*out = new(corev1.ConfigMapKeySelector)
		(*in).DeepCopyInto(*out)
	}
	out.BindQuerySecretRef = in.BindQuerySecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ldap.
func (in *Ldap) DeepCopy() *Ldap {
	if in == nil {
		return nil
	}
	out := new(Ldap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogRotateForBackupAndMonitoring) DeepCopyInto(out *LogRotateForBackupAndMonitoring) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogRotateForBackupAndMonitoring.
func (in *LogRotateForBackupAndMonitoring) DeepCopy() *LogRotateForBackupAndMonitoring {
	if in == nil {
		return nil
	}
	out := new(LogRotateForBackupAndMonitoring)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDB) DeepCopyInto(out *MongoDB) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDB.
func (in *MongoDB) DeepCopy() *MongoDB {
	if in == nil {
		return nil
	}
	out := new(MongoDB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongoDB) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBBuilder) DeepCopyInto(out *MongoDBBuilder) {
	*out = *in
	if in.mdb != nil {
		in, out := &in.mdb, &out.mdb
		*out = new(MongoDB)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBBuilder.
func (in *MongoDBBuilder) DeepCopy() *MongoDBBuilder {
	if in == nil {
		return nil
	}
	out := new(MongoDBBuilder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBConnectionStringBuilder) DeepCopyInto(out *MongoDBConnectionStringBuilder) {
	*out = *in
	in.MongoDB.DeepCopyInto(&out.MongoDB)
	if in.hostnames != nil {
		in, out := &in.hostnames, &out.hostnames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBConnectionStringBuilder.
func (in *MongoDBConnectionStringBuilder) DeepCopy() *MongoDBConnectionStringBuilder {
	if in == nil {
		return nil
	}
	out := new(MongoDBConnectionStringBuilder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBConnectivity) DeepCopyInto(out *MongoDBConnectivity) {
	*out = *in
	if in.ReplicaSetHorizons != nil {
		in, out := &in.ReplicaSetHorizons, &out.ReplicaSetHorizons
		*out = make([]MongoDBHorizonConfig, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(MongoDBHorizonConfig, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBConnectivity.
func (in *MongoDBConnectivity) DeepCopy() *MongoDBConnectivity {
	if in == nil {
		return nil
	}
	out := new(MongoDBConnectivity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in MongoDBHorizonConfig) DeepCopyInto(out *MongoDBHorizonConfig) {
	{
		in := &in
		*out = make(MongoDBHorizonConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBHorizonConfig.
func (in MongoDBHorizonConfig) DeepCopy() MongoDBHorizonConfig {
	if in == nil {
		return nil
	}
	out := new(MongoDBHorizonConfig)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBList) DeepCopyInto(out *MongoDBList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MongoDB, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBList.
func (in *MongoDBList) DeepCopy() *MongoDBList {
	if in == nil {
		return nil
	}
	out := new(MongoDBList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongoDBList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDbPodSpec) DeepCopyInto(out *MongoDbPodSpec) {
	*out = *in
	out.ContainerResourceRequirements = in.ContainerResourceRequirements
	in.PodTemplateWrapper.DeepCopyInto(&out.PodTemplateWrapper)
	if in.Persistence != nil {
		in, out := &in.Persistence, &out.Persistence
		*out = new(common.Persistence)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDbPodSpec.
func (in *MongoDbPodSpec) DeepCopy() *MongoDbPodSpec {
	if in == nil {
		return nil
	}
	out := new(MongoDbPodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDbRole) DeepCopyInto(out *MongoDbRole) {
	*out = *in
	if in.AuthenticationRestrictions != nil {
		in, out := &in.AuthenticationRestrictions, &out.AuthenticationRestrictions
		*out = make([]AuthenticationRestriction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Privileges != nil {
		in, out := &in.Privileges, &out.Privileges
		*out = make([]Privilege, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]InheritedRole, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDbRole.
func (in *MongoDbRole) DeepCopy() *MongoDbRole {
	if in == nil {
		return nil
	}
	out := new(MongoDbRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDbSpec) DeepCopyInto(out *MongoDbSpec) {
	*out = *in
	in.DbCommonSpec.DeepCopyInto(&out.DbCommonSpec)
	in.ShardedClusterSpec.DeepCopyInto(&out.ShardedClusterSpec)
	out.MongodbShardedClusterSizeConfig = in.MongodbShardedClusterSizeConfig
	if in.PodSpec != nil {
		in, out := &in.PodSpec, &out.PodSpec
		*out = new(MongoDbPodSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MemberConfig != nil {
		in, out := &in.MemberConfig, &out.MemberConfig
		*out = make([]automationconfig.MemberOptions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDbSpec.
func (in *MongoDbSpec) DeepCopy() *MongoDbSpec {
	if in == nil {
		return nil
	}
	out := new(MongoDbSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDbStatus) DeepCopyInto(out *MongoDbStatus) {
	*out = *in
	in.Common.DeepCopyInto(&out.Common)
	if in.BackupStatus != nil {
		in, out := &in.BackupStatus, &out.BackupStatus
		*out = new(BackupStatus)
		**out = **in
	}
	out.MongodbShardedClusterSizeConfig = in.MongodbShardedClusterSizeConfig
	if in.SizeStatusInClusters != nil {
		in, out := &in.SizeStatusInClusters, &out.SizeStatusInClusters
		*out = new(status.MongodbShardedSizeStatusInClusters)
		(*in).DeepCopyInto(*out)
	}
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make([]status.Warning, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDbStatus.
func (in *MongoDbStatus) DeepCopy() *MongoDbStatus {
	if in == nil {
		return nil
	}
	out := new(MongoDbStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongodbCleanUpOptions) DeepCopyInto(out *MongodbCleanUpOptions) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongodbCleanUpOptions.
func (in *MongodbCleanUpOptions) DeepCopy() *MongodbCleanUpOptions {
	if in == nil {
		return nil
	}
	out := new(MongodbCleanUpOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringAgent) DeepCopyInto(out *MonitoringAgent) {
	*out = *in
	if in.LogRotate != nil {
		in, out := &in.LogRotate, &out.LogRotate
		*out = new(LogRotateForBackupAndMonitoring)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringAgent.
func (in *MonitoringAgent) DeepCopy() *MonitoringAgent {
	if in == nil {
		return nil
	}
	out := new(MonitoringAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringAgentConfig) DeepCopyInto(out *MonitoringAgentConfig) {
	*out = *in
	if in.StartupParameters != nil {
		in, out := &in.StartupParameters, &out.StartupParameters
		*out = make(StartupParameters, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringAgentConfig.
func (in *MonitoringAgentConfig) DeepCopy() *MonitoringAgentConfig {
	if in == nil {
		return nil
	}
	out := new(MonitoringAgentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCProviderConfig) DeepCopyInto(out *OIDCProviderConfig) {
	*out = *in
	if in.GroupsClaim != nil {
		in, out := &in.GroupsClaim, &out.GroupsClaim
		*out = new(string)
		**out = **in
	}
	if in.ClientId != nil {
		in, out := &in.ClientId, &out.ClientId
		*out = new(string)
		**out = **in
	}
	if in.RequestedScopes != nil {
		in, out := &in.RequestedScopes, &out.RequestedScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCProviderConfig.
func (in *OIDCProviderConfig) DeepCopy() *OIDCProviderConfig {
	if in == nil {
		return nil
	}
	out := new(OIDCProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistenceConfigBuilder) DeepCopyInto(out *PersistenceConfigBuilder) {
	*out = *in
	if in.config != nil {
		in, out := &in.config, &out.config
		*out = new(common.PersistenceConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistenceConfigBuilder.
func (in *PersistenceConfigBuilder) DeepCopy() *PersistenceConfigBuilder {
	if in == nil {
		return nil
	}
	out := new(PersistenceConfigBuilder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSpecWrapper) DeepCopyInto(out *PodSpecWrapper) {
	*out = *in
	in.MongoDbPodSpec.DeepCopyInto(&out.MongoDbPodSpec)
	in.Default.DeepCopyInto(&out.Default)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSpecWrapper.
func (in *PodSpecWrapper) DeepCopy() *PodSpecWrapper {
	if in == nil {
		return nil
	}
	out := new(PodSpecWrapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSpecWrapperBuilder) DeepCopyInto(out *PodSpecWrapperBuilder) {
	*out = *in
	in.spec.DeepCopyInto(&out.spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSpecWrapperBuilder.
func (in *PodSpecWrapperBuilder) DeepCopy() *PodSpecWrapperBuilder {
	if in == nil {
		return nil
	}
	out := new(PodSpecWrapperBuilder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateCloudConfig) DeepCopyInto(out *PrivateCloudConfig) {
	*out = *in
	out.ConfigMapRef = in.ConfigMapRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateCloudConfig.
func (in *PrivateCloudConfig) DeepCopy() *PrivateCloudConfig {
	if in == nil {
		return nil
	}
	out := new(PrivateCloudConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Privilege) DeepCopyInto(out *Privilege) {
	*out = *in
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Resource.DeepCopyInto(&out.Resource)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Privilege.
func (in *Privilege) DeepCopy() *Privilege {
	if in == nil {
		return nil
	}
	out := new(Privilege)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectConfig) DeepCopyInto(out *ProjectConfig) {
	*out = *in
	out.SSLProjectConfig = in.SSLProjectConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectConfig.
func (in *ProjectConfig) DeepCopy() *ProjectConfig {
	if in == nil {
		return nil
	}
	out := new(ProjectConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadinessProbe) DeepCopyInto(out *ReadinessProbe) {
	*out = *in
	if in.EnvironmentVariables != nil {
		in, out := &in.EnvironmentVariables, &out.EnvironmentVariables
		*out = make(EnvironmentVariables, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadinessProbe.
func (in *ReadinessProbe) DeepCopy() *ReadinessProbe {
	if in == nil {
		return nil
	}
	out := new(ReadinessProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resource) DeepCopyInto(out *Resource) {
	*out = *in
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resource.
func (in *Resource) DeepCopy() *Resource {
	if in == nil {
		return nil
	}
	out := new(Resource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Security) DeepCopyInto(out *Security) {
	*out = *in
	if in.TLSConfig != nil {
		in, out := &in.TLSConfig, &out.TLSConfig
		*out = new(TLSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(Authentication)
		(*in).DeepCopyInto(*out)
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]MongoDbRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Security.
func (in *Security) DeepCopy() *Security {
	if in == nil {
		return nil
	}
	out := new(Security)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardOverride) DeepCopyInto(out *ShardOverride) {
	*out = *in
	if in.ShardNames != nil {
		in, out := &in.ShardNames, &out.ShardNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.ShardedClusterComponentOverrideSpec.DeepCopyInto(&out.ShardedClusterComponentOverrideSpec)
	if in.PodSpec != nil {
		in, out := &in.PodSpec, &out.PodSpec
		*out = new(MongoDbPodSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = new(int)
		**out = **in
	}
	if in.MemberConfig != nil {
		in, out := &in.MemberConfig, &out.MemberConfig
		*out = make([]automationconfig.MemberOptions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StatefulSetConfiguration != nil {
		in, out := &in.StatefulSetConfiguration, &out.StatefulSetConfiguration
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardOverride.
func (in *ShardOverride) DeepCopy() *ShardOverride {
	if in == nil {
		return nil
	}
	out := new(ShardOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardedClusterComponentOverrideSpec) DeepCopyInto(out *ShardedClusterComponentOverrideSpec) {
	*out = *in
	if in.AdditionalMongodConfig != nil {
		in, out := &in.AdditionalMongodConfig, &out.AdditionalMongodConfig
		*out = (*in).DeepCopy()
	}
	if in.Agent != nil {
		in, out := &in.Agent, &out.Agent
		*out = new(AgentConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterSpecList != nil {
		in, out := &in.ClusterSpecList, &out.ClusterSpecList
		*out = make([]ClusterSpecItemOverride, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardedClusterComponentOverrideSpec.
func (in *ShardedClusterComponentOverrideSpec) DeepCopy() *ShardedClusterComponentOverrideSpec {
	if in == nil {
		return nil
	}
	out := new(ShardedClusterComponentOverrideSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardedClusterComponentSpec) DeepCopyInto(out *ShardedClusterComponentSpec) {
	*out = *in
	if in.AdditionalMongodConfig != nil {
		in, out := &in.AdditionalMongodConfig, &out.AdditionalMongodConfig
		*out = (*in).DeepCopy()
	}
	in.Agent.DeepCopyInto(&out.Agent)
	if in.ClusterSpecList != nil {
		in, out := &in.ClusterSpecList, &out.ClusterSpecList
		*out = make(ClusterSpecList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardedClusterComponentSpec.
func (in *ShardedClusterComponentSpec) DeepCopy() *ShardedClusterComponentSpec {
	if in == nil {
		return nil
	}
	out := new(ShardedClusterComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardedClusterSpec) DeepCopyInto(out *ShardedClusterSpec) {
	*out = *in
	if in.ConfigSrvSpec != nil {
		in, out := &in.ConfigSrvSpec, &out.ConfigSrvSpec
		*out = new(ShardedClusterComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MongosSpec != nil {
		in, out := &in.MongosSpec, &out.MongosSpec
		*out = new(ShardedClusterComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ShardSpec != nil {
		in, out := &in.ShardSpec, &out.ShardSpec
		*out = new(ShardedClusterComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ShardOverrides != nil {
		in, out := &in.ShardOverrides, &out.ShardOverrides
		*out = make([]ShardOverride, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ConfigSrvPodSpec != nil {
		in, out := &in.ConfigSrvPodSpec, &out.ConfigSrvPodSpec
		*out = new(MongoDbPodSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MongosPodSpec != nil {
		in, out := &in.MongosPodSpec, &out.MongosPodSpec
		*out = new(MongoDbPodSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ShardPodSpec != nil {
		in, out := &in.ShardPodSpec, &out.ShardPodSpec
		*out = new(MongoDbPodSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ShardSpecificPodSpec != nil {
		in, out := &in.ShardSpecificPodSpec, &out.ShardSpecificPodSpec
		*out = make([]MongoDbPodSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardedClusterSpec.
func (in *ShardedClusterSpec) DeepCopy() *ShardedClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ShardedClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedConnectionSpec) DeepCopyInto(out *SharedConnectionSpec) {
	*out = *in
	if in.OpsManagerConfig != nil {
		in, out := &in.OpsManagerConfig, &out.OpsManagerConfig
		*out = new(PrivateCloudConfig)
		**out = **in
	}
	if in.CloudManagerConfig != nil {
		in, out := &in.CloudManagerConfig, &out.CloudManagerConfig
		*out = new(PrivateCloudConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedConnectionSpec.
func (in *SharedConnectionSpec) DeepCopy() *SharedConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(SharedConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotSchedule) DeepCopyInto(out *SnapshotSchedule) {
	*out = *in
	if in.SnapshotIntervalHours != nil {
		in, out := &in.SnapshotIntervalHours, &out.SnapshotIntervalHours
		*out = new(int)
		**out = **in
	}
	if in.SnapshotRetentionDays != nil {
		in, out := &in.SnapshotRetentionDays, &out.SnapshotRetentionDays
		*out = new(int)
		**out = **in
	}
	if in.DailySnapshotRetentionDays != nil {
		in, out := &in.DailySnapshotRetentionDays, &out.DailySnapshotRetentionDays
		*out = new(int)
		**out = **in
	}
	if in.WeeklySnapshotRetentionWeeks != nil {
		in, out := &in.WeeklySnapshotRetentionWeeks, &out.WeeklySnapshotRetentionWeeks
		*out = new(int)
		**out = **in
	}
	if in.MonthlySnapshotRetentionMonths != nil {
		in, out := &in.MonthlySnapshotRetentionMonths, &out.MonthlySnapshotRetentionMonths
		*out = new(int)
		**out = **in
	}
	if in.PointInTimeWindowHours != nil {
		in, out := &in.PointInTimeWindowHours, &out.PointInTimeWindowHours
		*out = new(int)
		**out = **in
	}
	if in.ReferenceHourOfDay != nil {
		in, out := &in.ReferenceHourOfDay, &out.ReferenceHourOfDay
		*out = new(int)
		**out = **in
	}
	if in.ReferenceMinuteOfHour != nil {
		in, out := &in.ReferenceMinuteOfHour, &out.ReferenceMinuteOfHour
		*out = new(int)
		**out = **in
	}
	if in.FullIncrementalDayOfWeek != nil {
		in, out := &in.FullIncrementalDayOfWeek, &out.FullIncrementalDayOfWeek
		*out = new(string)
		**out = **in
	}
	if in.ClusterCheckpointIntervalMin != nil {
		in, out := &in.ClusterCheckpointIntervalMin, &out.ClusterCheckpointIntervalMin
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotSchedule.
func (in *SnapshotSchedule) DeepCopy() *SnapshotSchedule {
	if in == nil {
		return nil
	}
	out := new(SnapshotSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in StartupParameters) DeepCopyInto(out *StartupParameters) {
	{
		in := &in
		*out = make(StartupParameters, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartupParameters.
func (in StartupParameters) DeepCopy() StartupParameters {
	if in == nil {
		return nil
	}
	out := new(StartupParameters)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	if in.AdditionalCertificateDomains != nil {
		in, out := &in.AdditionalCertificateDomains, &out.AdditionalCertificateDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}
