//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package mdb

import (
	"github.com/10gen/ops-manager-kubernetes/api/v1/status"
	v1 "github.com/mongodb/mongodb-kubernetes-operator/api/v1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentAuthentication) DeepCopyInto(out *AgentAuthentication) {
	*out = *in
	in.AutomationPasswordSecretRef.DeepCopyInto(&out.AutomationPasswordSecretRef)
	in.ClientCertificateSecretRefWrap.DeepCopyInto(&out.ClientCertificateSecretRefWrap)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentAuthentication.
func (in *AgentAuthentication) DeepCopy() *AgentAuthentication {
	if in == nil {
		return nil
	}
	out := new(AgentAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentConfig) DeepCopyInto(out *AgentConfig) {
	*out = *in
	if in.StartupParameters != nil {
		in, out := &in.StartupParameters, &out.StartupParameters
		*out = make(StartupParameters, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentConfig.
func (in *AgentConfig) DeepCopy() *AgentConfig {
	if in == nil {
		return nil
	}
	out := new(AgentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Authentication) DeepCopyInto(out *Authentication) {
	*out = *in
	if in.Modes != nil {
		in, out := &in.Modes, &out.Modes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Ldap != nil {
		in, out := &in.Ldap, &out.Ldap
		*out = new(Ldap)
		(*in).DeepCopyInto(*out)
	}
	in.Agents.DeepCopyInto(&out.Agents)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Authentication.
func (in *Authentication) DeepCopy() *Authentication {
	if in == nil {
		return nil
	}
	out := new(Authentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthenticationRestriction) DeepCopyInto(out *AuthenticationRestriction) {
	*out = *in
	if in.ClientSource != nil {
		in, out := &in.ClientSource, &out.ClientSource
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ServerAddress != nil {
		in, out := &in.ServerAddress, &out.ServerAddress
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticationRestriction.
func (in *AuthenticationRestriction) DeepCopy() *AuthenticationRestriction {
	if in == nil {
		return nil
	}
	out := new(AuthenticationRestriction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Backup) DeepCopyInto(out *Backup) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Backup.
func (in *Backup) DeepCopy() *Backup {
	if in == nil {
		return nil
	}
	out := new(Backup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupStatus) DeepCopyInto(out *BackupStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupStatus.
func (in *BackupStatus) DeepCopy() *BackupStatus {
	if in == nil {
		return nil
	}
	out := new(BackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientCertificateSecretRefWrapper) DeepCopyInto(out *ClientCertificateSecretRefWrapper) {
	clone := in.DeepCopy()
	*out = *clone
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapRef) DeepCopyInto(out *ConfigMapRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapRef.
func (in *ConfigMapRef) DeepCopy() *ConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(ConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionSpec) DeepCopyInto(out *ConnectionSpec) {
	*out = *in
	if in.OpsManagerConfig != nil {
		in, out := &in.OpsManagerConfig, &out.OpsManagerConfig
		*out = new(PrivateCloudConfig)
		**out = **in
	}
	if in.CloudManagerConfig != nil {
		in, out := &in.CloudManagerConfig, &out.CloudManagerConfig
		*out = new(PrivateCloudConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionSpec.
func (in *ConnectionSpec) DeepCopy() *ConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(ConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerResourceRequirements) DeepCopyInto(out *ContainerResourceRequirements) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerResourceRequirements.
func (in *ContainerResourceRequirements) DeepCopy() *ContainerResourceRequirements {
	if in == nil {
		return nil
	}
	out := new(ContainerResourceRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Credentials) DeepCopyInto(out *Credentials) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Credentials.
func (in *Credentials) DeepCopy() *Credentials {
	if in == nil {
		return nil
	}
	out := new(Credentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InheritedRole) DeepCopyInto(out *InheritedRole) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InheritedRole.
func (in *InheritedRole) DeepCopy() *InheritedRole {
	if in == nil {
		return nil
	}
	out := new(InheritedRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelSelectorWrapper) DeepCopyInto(out *LabelSelectorWrapper) {
	clone := in.DeepCopy()
	*out = *clone
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ldap) DeepCopyInto(out *Ldap) {
	*out = *in
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TransportSecurity != nil {
		in, out := &in.TransportSecurity, &out.TransportSecurity
		*out = new(TransportSecurity)
		**out = **in
	}
	if in.ValidateLDAPServerConfig != nil {
		in, out := &in.ValidateLDAPServerConfig, &out.ValidateLDAPServerConfig
		*out = new(bool)
		**out = **in
	}
	if in.CAConfigMapRef != nil {
		in, out := &in.CAConfigMapRef, &out.CAConfigMapRef
		*out = new(corev1.ConfigMapKeySelector)
		(*in).DeepCopyInto(*out)
	}
	out.BindQuerySecretRef = in.BindQuerySecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ldap.
func (in *Ldap) DeepCopy() *Ldap {
	if in == nil {
		return nil
	}
	out := new(Ldap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDB) DeepCopyInto(out *MongoDB) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDB.
func (in *MongoDB) DeepCopy() *MongoDB {
	if in == nil {
		return nil
	}
	out := new(MongoDB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongoDB) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBBuilder) DeepCopyInto(out *MongoDBBuilder) {
	*out = *in
	if in.mdb != nil {
		in, out := &in.mdb, &out.mdb
		*out = new(MongoDB)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBBuilder.
func (in *MongoDBBuilder) DeepCopy() *MongoDBBuilder {
	if in == nil {
		return nil
	}
	out := new(MongoDBBuilder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBConnectivity) DeepCopyInto(out *MongoDBConnectivity) {
	*out = *in
	if in.ReplicaSetHorizons != nil {
		in, out := &in.ReplicaSetHorizons, &out.ReplicaSetHorizons
		*out = make([]MongoDBHorizonConfig, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(MongoDBHorizonConfig, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBConnectivity.
func (in *MongoDBConnectivity) DeepCopy() *MongoDBConnectivity {
	if in == nil {
		return nil
	}
	out := new(MongoDBConnectivity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in MongoDBHorizonConfig) DeepCopyInto(out *MongoDBHorizonConfig) {
	{
		in := &in
		*out = make(MongoDBHorizonConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBHorizonConfig.
func (in MongoDBHorizonConfig) DeepCopy() MongoDBHorizonConfig {
	if in == nil {
		return nil
	}
	out := new(MongoDBHorizonConfig)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBList) DeepCopyInto(out *MongoDBList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MongoDB, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBList.
func (in *MongoDBList) DeepCopy() *MongoDBList {
	if in == nil {
		return nil
	}
	out := new(MongoDBList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongoDBList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDbPodSpec) DeepCopyInto(out *MongoDbPodSpec) {
	*out = *in
	out.ContainerResourceRequirements = in.ContainerResourceRequirements
	in.PodAffinityWrapper.DeepCopyInto(&out.PodAffinityWrapper)
	in.NodeAffinityWrapper.DeepCopyInto(&out.NodeAffinityWrapper)
	in.PodTemplateWrapper.DeepCopyInto(&out.PodTemplateWrapper)
	if in.Persistence != nil {
		in, out := &in.Persistence, &out.Persistence
		*out = new(Persistence)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDbPodSpec.
func (in *MongoDbPodSpec) DeepCopy() *MongoDbPodSpec {
	if in == nil {
		return nil
	}
	out := new(MongoDbPodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDbRole) DeepCopyInto(out *MongoDbRole) {
	*out = *in
	if in.AuthenticationRestrictions != nil {
		in, out := &in.AuthenticationRestrictions, &out.AuthenticationRestrictions
		*out = make([]AuthenticationRestriction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Privileges != nil {
		in, out := &in.Privileges, &out.Privileges
		*out = make([]Privilege, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]InheritedRole, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDbRole.
func (in *MongoDbRole) DeepCopy() *MongoDbRole {
	if in == nil {
		return nil
	}
	out := new(MongoDbRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDbSpec) DeepCopyInto(out *MongoDbSpec) {
	*out = *in
	in.ShardedClusterSpec.DeepCopyInto(&out.ShardedClusterSpec)
	if in.FeatureCompatibilityVersion != nil {
		in, out := &in.FeatureCompatibilityVersion, &out.FeatureCompatibilityVersion
		*out = new(string)
		**out = **in
	}
	in.ConnectionSpec.DeepCopyInto(&out.ConnectionSpec)
	if in.Persistent != nil {
		in, out := &in.Persistent, &out.Persistent
		*out = new(bool)
		**out = **in
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(Backup)
		**out = **in
	}
	if in.Prometheus != nil {
		in, out := &in.Prometheus, &out.Prometheus
		*out = new(v1.Prometheus)
		**out = **in
	}
	out.MongodbShardedClusterSizeConfig = in.MongodbShardedClusterSizeConfig
	in.Agent.DeepCopyInto(&out.Agent)
	if in.PodSpec != nil {
		in, out := &in.PodSpec, &out.PodSpec
		*out = new(MongoDbPodSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(Security)
		(*in).DeepCopyInto(*out)
	}
	if in.Connectivity != nil {
		in, out := &in.Connectivity, &out.Connectivity
		*out = new(MongoDBConnectivity)
		(*in).DeepCopyInto(*out)
	}
	in.AdditionalMongodConfig.DeepCopyInto(&out.AdditionalMongodConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDbSpec.
func (in *MongoDbSpec) DeepCopy() *MongoDbSpec {
	if in == nil {
		return nil
	}
	out := new(MongoDbSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDbStatus) DeepCopyInto(out *MongoDbStatus) {
	*out = *in
	in.Common.DeepCopyInto(&out.Common)
	if in.BackupStatus != nil {
		in, out := &in.BackupStatus, &out.BackupStatus
		*out = new(BackupStatus)
		**out = **in
	}
	out.MongodbShardedClusterSizeConfig = in.MongodbShardedClusterSizeConfig
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make([]status.Warning, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDbStatus.
func (in *MongoDbStatus) DeepCopy() *MongoDbStatus {
	if in == nil {
		return nil
	}
	out := new(MongoDbStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongodbShardedClusterSizeConfig) DeepCopyInto(out *MongodbShardedClusterSizeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongodbShardedClusterSizeConfig.
func (in *MongodbShardedClusterSizeConfig) DeepCopy() *MongodbShardedClusterSizeConfig {
	if in == nil {
		return nil
	}
	out := new(MongodbShardedClusterSizeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiplePersistenceConfig) DeepCopyInto(out *MultiplePersistenceConfig) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = new(PersistenceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Journal != nil {
		in, out := &in.Journal, &out.Journal
		*out = new(PersistenceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = new(PersistenceConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiplePersistenceConfig.
func (in *MultiplePersistenceConfig) DeepCopy() *MultiplePersistenceConfig {
	if in == nil {
		return nil
	}
	out := new(MultiplePersistenceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAffinityWrapper) DeepCopyInto(out *NodeAffinityWrapper) {
	clone := in.DeepCopy()
	*out = *clone
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Persistence) DeepCopyInto(out *Persistence) {
	*out = *in
	if in.SingleConfig != nil {
		in, out := &in.SingleConfig, &out.SingleConfig
		*out = new(PersistenceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MultipleConfig != nil {
		in, out := &in.MultipleConfig, &out.MultipleConfig
		*out = new(MultiplePersistenceConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Persistence.
func (in *Persistence) DeepCopy() *Persistence {
	if in == nil {
		return nil
	}
	out := new(Persistence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistenceConfig) DeepCopyInto(out *PersistenceConfig) {
	*out = *in
	if in.StorageClass != nil {
		in, out := &in.StorageClass, &out.StorageClass
		*out = new(string)
		**out = **in
	}
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistenceConfig.
func (in *PersistenceConfig) DeepCopy() *PersistenceConfig {
	if in == nil {
		return nil
	}
	out := new(PersistenceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistenceConfigBuilder) DeepCopyInto(out *PersistenceConfigBuilder) {
	*out = *in
	if in.config != nil {
		in, out := &in.config, &out.config
		*out = new(PersistenceConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistenceConfigBuilder.
func (in *PersistenceConfigBuilder) DeepCopy() *PersistenceConfigBuilder {
	if in == nil {
		return nil
	}
	out := new(PersistenceConfigBuilder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodAffinityWrapper) DeepCopyInto(out *PodAffinityWrapper) {
	clone := in.DeepCopy()
	*out = *clone
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSpecWrapper) DeepCopyInto(out *PodSpecWrapper) {
	*out = *in
	in.MongoDbPodSpec.DeepCopyInto(&out.MongoDbPodSpec)
	in.Default.DeepCopyInto(&out.Default)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSpecWrapper.
func (in *PodSpecWrapper) DeepCopy() *PodSpecWrapper {
	if in == nil {
		return nil
	}
	out := new(PodSpecWrapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSpecWrapperBuilder) DeepCopyInto(out *PodSpecWrapperBuilder) {
	*out = *in
	in.spec.DeepCopyInto(&out.spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSpecWrapperBuilder.
func (in *PodSpecWrapperBuilder) DeepCopy() *PodSpecWrapperBuilder {
	if in == nil {
		return nil
	}
	out := new(PodSpecWrapperBuilder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodTemplateSpecWrapper) DeepCopyInto(out *PodTemplateSpecWrapper) {
	clone := in.DeepCopy()
	*out = *clone
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateCloudConfig) DeepCopyInto(out *PrivateCloudConfig) {
	*out = *in
	out.ConfigMapRef = in.ConfigMapRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateCloudConfig.
func (in *PrivateCloudConfig) DeepCopy() *PrivateCloudConfig {
	if in == nil {
		return nil
	}
	out := new(PrivateCloudConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Privilege) DeepCopyInto(out *Privilege) {
	*out = *in
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Resource.DeepCopyInto(&out.Resource)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Privilege.
func (in *Privilege) DeepCopy() *Privilege {
	if in == nil {
		return nil
	}
	out := new(Privilege)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectConfig) DeepCopyInto(out *ProjectConfig) {
	*out = *in
	out.SSLProjectConfig = in.SSLProjectConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectConfig.
func (in *ProjectConfig) DeepCopy() *ProjectConfig {
	if in == nil {
		return nil
	}
	out := new(ProjectConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resource) DeepCopyInto(out *Resource) {
	*out = *in
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resource.
func (in *Resource) DeepCopy() *Resource {
	if in == nil {
		return nil
	}
	out := new(Resource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Security) DeepCopyInto(out *Security) {
	*out = *in
	if in.TLSConfig != nil {
		in, out := &in.TLSConfig, &out.TLSConfig
		*out = new(TLSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(Authentication)
		(*in).DeepCopyInto(*out)
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]MongoDbRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Security.
func (in *Security) DeepCopy() *Security {
	if in == nil {
		return nil
	}
	out := new(Security)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardedClusterComponentSpec) DeepCopyInto(out *ShardedClusterComponentSpec) {
	*out = *in
	in.AdditionalMongodConfig.DeepCopyInto(&out.AdditionalMongodConfig)
	in.Agent.DeepCopyInto(&out.Agent)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardedClusterComponentSpec.
func (in *ShardedClusterComponentSpec) DeepCopy() *ShardedClusterComponentSpec {
	if in == nil {
		return nil
	}
	out := new(ShardedClusterComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardedClusterSpec) DeepCopyInto(out *ShardedClusterSpec) {
	*out = *in
	if in.ConfigSrvSpec != nil {
		in, out := &in.ConfigSrvSpec, &out.ConfigSrvSpec
		*out = new(ShardedClusterComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MongosSpec != nil {
		in, out := &in.MongosSpec, &out.MongosSpec
		*out = new(ShardedClusterComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ShardSpec != nil {
		in, out := &in.ShardSpec, &out.ShardSpec
		*out = new(ShardedClusterComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigSrvPodSpec != nil {
		in, out := &in.ConfigSrvPodSpec, &out.ConfigSrvPodSpec
		*out = new(MongoDbPodSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MongosPodSpec != nil {
		in, out := &in.MongosPodSpec, &out.MongosPodSpec
		*out = new(MongoDbPodSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ShardPodSpec != nil {
		in, out := &in.ShardPodSpec, &out.ShardPodSpec
		*out = new(MongoDbPodSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardedClusterSpec.
func (in *ShardedClusterSpec) DeepCopy() *ShardedClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ShardedClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in StartupParameters) DeepCopyInto(out *StartupParameters) {
	{
		in := &in
		*out = make(StartupParameters, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartupParameters.
func (in StartupParameters) DeepCopy() StartupParameters {
	if in == nil {
		return nil
	}
	out := new(StartupParameters)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulSetSpecWrapper) DeepCopyInto(out *StatefulSetSpecWrapper) {
	clone := in.DeepCopy()
	*out = *clone
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	if in.AdditionalCertificateDomains != nil {
		in, out := &in.AdditionalCertificateDomains, &out.AdditionalCertificateDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSSecretRef) DeepCopyInto(out *TLSSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSSecretRef.
func (in *TLSSecretRef) DeepCopy() *TLSSecretRef {
	if in == nil {
		return nil
	}
	out := new(TLSSecretRef)
	in.DeepCopyInto(out)
	return out
}
