apiVersion: v2
name: mongodb-kubernetes
description: MongoDB Kubernetes Operator
version: 0.1.0
kubeVersion: '>=1.16-0'
type: application
keywords:
- mongodb
- database
- nosql
icon: https://mongodb-images-new.s3.eu-west-1.amazonaws.com/leaf-green-dark.png
home: https://github.com/mongodb/mongodb-kubernetes
maintainers:
- name: MongoDB
  email: support@mongodb.com
