export K8S_CTX="${CLUSTER_NAME}"

export OPERATOR_ADDITIONAL_HELM_VALUES=""
export OPERATOR_HELM_CHART=${PROJECT_DIR}/helm_chart

export AUTO_EMBEDDING_API_INDEXING_KEY="${AI_MONGODB_EMBEDDING_INDEXING_KEY}"
export AUTO_EMBEDDING_API_QUERY_KEY="${AI_MONGODB_EMBEDDING_QUERY_KEY}"
