OCI_HELM_VERSION = "OCI_HELM_VERSION"
OCI_HELM_REGISTRY_ENV_VAR_NAME = "OCI_HELM_REGISTRY"
OCI_HELM_REPOSITORY_ENV_VAR_NAME = "OCI_HELM_REPOSITORY"
OCI_HELM_REGION_ENV_VAR_NAME = "OCI_HELM_REGION"

LEGACY_OPERATOR_CHART = "mongodb/enterprise-operator"
MCK_HELM_CHART = "mongodb/mongodb-kubernetes"
