apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  annotations:
    mongodb.com/migrate-tool-version: 5dc66aef
    mongodb.com/migration-dry-run: "true"
  name: rs0
  namespace: bughunt-nam
spec:
  agent:
    backupAgent:
      logRotate:
        sizeThresholdMB: 1000
        timeThresholdHrs: 24
    mongod:
      auditlogRotate:
        percentOfDiskspace: "0"
        sizeThresholdMB: "1000"
        timeThresholdHrs: 24
      logRotate:
        percentOfDiskspace: "0"
        sizeThresholdMB: "1000"
        timeThresholdHrs: 24
      systemLog:
        destination: file
        logAppend: false
        path: /data/mongod.log
    monitoringAgent:
      logRotate:
        sizeThresholdMB: 1000
        timeThresholdHrs: 24
  credentials: my-credentials
  externalMembers:
  - hostname: vm-mongodb-0.vm-mongodb.bughunt-nam.svc.cluster.local:27017
    processName: rs0_0
    replicaSetName: rs0
    type: mongod
  - hostname: vm-mongodb-1.vm-mongodb.bughunt-nam.svc.cluster.local:27017
    processName: rs0_1
    replicaSetName: rs0
    type: mongod
  - hostname: vm-mongodb-2.vm-mongodb.bughunt-nam.svc.cluster.local:27017
    processName: rs0_2
    replicaSetName: rs0
    type: mongod
  featureCompatibilityVersion: "7.0"
  opsManager:
    configMapRef:
      name: my-project
  security:
    authentication:
      agents:
        automationUserName: mms-automation
        mode: SCRAM
      enabled: true
      ignoreUnknownUsers: true
      modes:
      - SCRAM
    certsSecretPrefix: mdb
    tls:
      ca: rs0-ca
  type: ReplicaSet
  version: 7.0.12
