{{ if .Values.operator.createResourcesServiceAccountsAndRoles }}

{{- $watchNamespace := include "mongodb-enterprise-operator.namespace" . | list }}
{{- if .Values.operator.watchNamespace }}
{{- $watchNamespace = regexSplit "," .Values.operator.watchNamespace -1 }}
{{- end }}


{{- range $idx, $namespace := $watchNamespace }}

{{- $namespaceBlock := printf "namespace: %s" $namespace }}
{{- if eq $namespace "*" }}
{{- $namespaceBlock = include "mongodb-enterprise-operator.namespace" $ | printf "namespace: %s"  }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-enterprise-appdb
  {{ $namespaceBlock }}
{{- if $.Values.registry.imagePullSecrets}}
imagePullSecrets:
  - name: {{ $.Values.registry.imagePullSecrets }}
{{- end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-enterprise-database-pods
  {{ $namespaceBlock }}
{{- if $.Values.registry.imagePullSecrets}}
imagePullSecrets:
  - name: {{ $.Values.registry.imagePullSecrets }}
{{- end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-enterprise-ops-manager
  {{ $namespaceBlock }}
{{- if $.Values.registry.imagePullSecrets}}
imagePullSecrets:
  - name: {{ $.Values.registry.imagePullSecrets }}
{{- end }}

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-enterprise-appdb
  {{ $namespaceBlock }}
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - patch
      - delete
      - get

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-enterprise-appdb
  {{ $namespaceBlock }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mongodb-enterprise-appdb
subjects:
  - kind: ServiceAccount
    name: mongodb-enterprise-appdb
    {{ $namespaceBlock }}

{{- end }}
{{- end }}{{/* if .Values.operator.createResourcesServiceAccountsAndRoles */}}

{{/*TODO MCK: these are MCO rbacs*/}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.community.name }}
  namespace: {{ if .Values.database.namespace }} {{ .Values.database.namespace }} {{ else }} {{ .Release.Namespace }} {{ end }}
{{- if .Values.registry.imagePullSecrets}}
imagePullSecrets:
  - name: {{ .Values.registry.imagePullSecrets }}
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.community.name }}
  namespace: {{ if .Values.database.namespace }} {{ .Values.database.namespace }} {{ else }} {{ .Release.Namespace }} {{ end }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - patch
      - delete
      - get

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.community.name }}
  namespace: {{ if .Values.database.namespace }} {{ .Values.database.namespace }} {{ else }} {{ .Release.Namespace }} {{ end }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.community.name }}
roleRef:
  kind: Role
  name: {{ .Values.community.name }}
  apiGroup: rbac.authorization.k8s.io
