#!/usr/bin/env bash

pushd "${PWD}" > /dev/null || return
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "${DIR}" || return
source errors
popd > /dev/null || return

check_env_var() {
    local var_name="$1"
    local msg="$2"
    set +u
    if [[ -z "${!var_name}" ]]; then
        echo "${msg}"
        exit 1
    fi
}

check_app() {
    local var="$1"
    local msg="$2"
    if ! which "${var}" > /dev/null; then
        echo "${msg}"
        exit 1
    fi
}

check_mandatory_param() {
    local param="${1-}"
    local param_name="${2-}"
    if [[ -z "${param}" ]]; then
        fatal "Parameter ${param_name} must be specified!"
    fi
}

