#!/usr/bin/env bash

set -euo pipefail

# Downloads a binary <bin> from <url> and moves it into <dir> directory.
# Example usage: download_and_install_binary ${workdir}/bin jq "https://..."
download_and_install_binary() {
  dir=$1
  bin=$2
  url=$3

  mkdir -p "${dir}"
  echo "Downloading ${url}"
  curl --retry 10 --retry-delay 10 --retry-all-errors --max-time 300 -fsSL "${url}" -o "${bin}"
  chmod +x "${bin}"
  mv "${bin}" "${dir}"
  echo "Installed ${bin} to ${dir}"
}
