#!/usr/bin/env bash

set -Eeou pipefail

pushd "$PWD" > /dev/null || return
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$DIR" || return
# shellcheck source=scripts/funcs/checks
source checks
# shellcheck source=scripts/funcs/errors
source errors
# shellcheck source=scripts/funcs/printing
source printing
popd > /dev/null || return

ensure_namespace() {
    local namespace="${1}"
    local tmp_file
    tmp_file=$(mktemp)
    cat <<EOF > "${tmp_file}"
apiVersion: v1
kind: Namespace
metadata:
  name: ${namespace}
  labels:
    evg: task
  annotations:
    evg/version: "https://evergreen.mongodb.com/version/${version_id:-'not-specified'}"
    evg/task-name: ${TASK_NAME:-'not-specified'}
    evg/task: "https://evergreen.mongodb.com/task/${task_id:-'not-specified'}"
    evg/mms-version: "${MMS_VERSION:-'not-specified'}"
EOF

    if kubectl get "ns/${namespace}" -o name &> /dev/null; then
        echo "Namespace ${namespace} already exists!"
    else
        echo "Creating new namespace: ${namespace}"
        cat "${tmp_file}"
        kubectl create -f "${tmp_file}"
    fi
}

# the function installs Ops Manager (legacy dev version) into Kubernetes cluster if it's not installed already
# Note, that this requires the k8s node with 4 Gb of free memory
ensure_ops_manager_k8s() {
    local ops_manager_namespace="${1}"
    local ops_manager_version="${2}"
    local node_port="${3}"

    if [ -z "${ops_manager_namespace}" ]; then
        error "ops_manager_namespace must be set!"
        exit 1
    fi
    if [ -z "${ops_manager_version}" ]; then
        error "ops_manager_version must be set!"
        exit 1
    fi
    if [ -z "${node_port}" ]; then
        error "node_port must be set!"
        exit 1
    fi

    echo "##### Installing Ops Manager ${ops_manager_version} (namespace ${ops_manager_namespace} into Kubernetes..."

    if _is_ops_manager_down "${ops_manager_namespace}"; then
        echo "Ops Manager is not installed in this cluster. Doing it now."
        echo "Run \"make -C docker/mongodb-enterprise-ops-manager-dev IMAGE_VERSION=${ops_manager_version} push\" to update Ops Manager image in ECR if necessary"

        echo "Installing Ops Manager ${ops_manager_version}"

        helm template -f scripts/evergreen/deployments/values-ops-manager.yaml \
            --set namespace="${ops_manager_namespace}" \
            --set opsManager.version="${ops_manager_version}" \
            --set opsManager.host="ops-manager.${ops_manager_namespace}.svc.cluster.local" \
            --set opsManager.nodePort="${node_port}" \
            docker/mongodb-enterprise-ops-manager-dev/helm_chart > mongodb-enterprise-ops-manager.yaml

        echo

        kubectl delete -f mongodb-enterprise-ops-manager.yaml || true
        kubectl apply -f mongodb-enterprise-ops-manager.yaml

        rm mongodb-enterprise-ops-manager.yaml

        echo "Waiting until Statefulset for Ops Manager is running..."

        local cmd
        # shellcheck disable=SC2016
        cmd='while [[ $(kubectl -n '${ops_manager_namespace}' get statefulset mongodb-enterprise-ops-manager -o jsonpath="{.status.currentReplicas}") != "1" ]]; do sleep 1; done'
        timeout "1m" bash -c "${cmd}" || true

        echo "Statefulset is ready, waiting for Ops Manager to start..."

        # We can't communicate with Ops Manager if it is inside Kubernetes, so we just
        # wait for this command to succeed.
        # Note, that for OM check for "status.phase==Running" may not work - we need to check the container status
        local cmd
        cmd="while ! kubectl get pod/mongodb-enterprise-ops-manager-0 -o jsonpath=\"{.status.containerStatuses[0].ready}\" -n ${ops_manager_namespace} | grep -q \"true\"; do sleep 4; done"
        timeout "10m" bash -c "${cmd}" || true

        if ! kubectl get pod/mongodb-enterprise-ops-manager-0 -o jsonpath="{.status.containerStatuses[0].ready}" -n "${ops_manager_namespace}" | grep -q "true"; then
            error "Ops Manager hasn't started!"
            kubectl describe pod/mongodb-enterprise-ops-manager-0 -n "${ops_manager_namespace}"
            exit 1
        fi
        echo "Pod is ready, waiting for the admin to get registered..."

        local cmd
        cmd="while ! kubectl -n ${ops_manager_namespace} exec mongodb-enterprise-ops-manager-0 ls \"/opt/mongodb/mms/env/.ops-manager-env\" &>/dev/null; do sleep 2; done"
        timeout "4m" bash -c "${cmd}" || true

        if ! kubectl -n "${ops_manager_namespace}" exec mongodb-enterprise-ops-manager-0 ls "/opt/mongodb/mms/env/.ops-manager-env" &>/dev/null; then
            error "No env file found in Ops Manager!"
            # todo print logs when OM image is fixed and rebuilt
            # kubectl logs  -n operator-testing mongodb-enterprise-ops-manager-0

            exit 1
        fi

        # we try to open ports for both security groups - in kops and openshift clusters
        _ensure_vpc_rules "us-east-2" "nodes.e2e"

        echo "Ops Manager is installed in this cluster. A new user will be added for automated tests to run."
    else
        echo "Ops Manager is already installed in this cluster."
        echo "If you want to start with a fresh Ops Manager installation, please delete the \"${ops_manager_namespace}\" namespace."
    fi

    echo "##### Ops Manager is ready"

    _print_om_endpoint "" "${ops_manager_namespace}" "${node_port}"
}

_print_om_endpoint() {
    local ops_manager_namespace="${2}"
    if [ -z "$ops_manager_namespace" ]; then
        error "No ops_manager_namespace set: not able to find Ops Manager external IP"
    else
        local node_port="${3}"
        local node_name
        node_name=$(kubectl get pods/mongodb-enterprise-ops-manager-0 -n "${ops_manager_namespace}" -o wide | tail -n 1 | awk '{print $7}')
        local external_ip
        external_ip="$(kubectl get nodes -o wide | grep "${node_name}" | awk '{print $7}')"

        echo "Use the following address to access Ops Manager from the browser: http://${external_ip}:${node_port}"
    fi
}

_ensure_vpc_rules() {
    local region="$1"
    local prefix="$2"
    local group_id
    group_id=$(aws ec2 describe-security-groups --region "${region}" | jq -r '.SecurityGroups[] | select(.GroupName | startswith( "'"$prefix"'")) | .GroupId')

    if [[ -z $group_id ]]; then
        echo "Failed to find group id for EC2 security group with prefix $prefix"
        return 1
    fi
    # note, that the attempt to add the same rule will result in "already exists" error - so we just ignore errors by now
    # open multiple node ports for different versions of Ops Manager
    for i in $(seq 30039 30043); do
        aws ec2 authorize-security-group-ingress --region "${region}" --group-id "${group_id}" --protocol tcp --port "${i}" --cidr "0.0.0.0/0" 2>/dev/null || true
        echo "Opened port ${i} in AWS for the security group with prefix $prefix (group id: $group_id)"
    done

}
# returns true if the namespace doesn't exist or if the OM pod is not running and this lasts for more than or equal to 1 hour.
# This is supposed to work for concurrent builds when one of the builds is starting Ops Manager (ideally we need to check for 10 minutes
# but parsing dates in bash is hard :( )
_is_ops_manager_down() {
    ! kubectl get "namespace/${1}" &> /dev/null || \
    ! kubectl get pod/mongodb-enterprise-ops-manager-0 -n "${1}" 2>/dev/null ||
    kubectl get pod/mongodb-enterprise-ops-manager-0 -o jsonpath="{.status.containerStatuses[0].ready}" -n "${1}" | grep -q "false"

}

delete_operator() {
    local ns="$1"
    local name=${OPERATOR_NAME:=mongodb-enterprise-operator}

    title "Removing the Operator deployment ${name}"
    ! kubectl --namespace "${ns}" get deployments | grep -q ${name} \
        || kubectl delete deployment $name -n "${ns}"
}

# wait_for_operator waits for the Operator to start
wait_for_operator_start() {
    local ns="$1"
    local timeout="${2:-2m}"
    echo "Waiting until the Operator gets to Running state..."
    export OPERATOR_NAME

    local cmd

    # Waiting until there is only one pod left as this could be the upgrade operation (very fast in practice)
    # shellcheck disable=SC2016
    cmd='while [[ $(kubectl -n '"${ns}"' get pods -l app.kubernetes.io/name=${OPERATOR_NAME}  --no-headers 2>/dev/null | wc -l) -gt 1 ]] ; do printf .; sleep 1; done'
    timeout --foreground "1m" bash -c "${cmd}" || true

    cmd="while ! kubectl -n ${ns} get pods -l app.kubernetes.io/name=${OPERATOR_NAME} -o jsonpath={.items[0].status.phase} 2>/dev/null | grep -q Running ; do printf .; sleep 1; done"
    timeout --foreground "${timeout}" bash -c "${cmd}" || true

    # In the end let's check again and print the state
    if ! kubectl -n "${ns}" get pods -l "app.kubernetes.io/name=${OPERATOR_NAME}" -o jsonpath="{.items[0].status.phase}" | grep -q "Running"; then
        error "Operator hasn't reached RUNNING state after ${timeout}. The full yaml configuration for the pod is:"
        kubectl -n "${ns}" get pods -l "app.kubernetes.io/name=${OPERATOR_NAME}" -o yaml

        title "Operator failed to start, exiting"
        return 1
    fi
    echo ""

    title "The Operator successfully installed to the Kubernetes cluster"
}

# Creates kops cluster and adds the support for dashboard
create_kops_cluster() {
    local cluster_name="${1}"
    local node_count=${2}
    local node_volume_size=${3}
    local node_size="${4}"
    local master_size="${5}"
    local zones="${6}"
    local k8s_version="${7:-}"

    if [[ -z "${k8s_version}" ]]; then
        k8s_version='v1.15.10'
    fi

    title "Creating kops cluster $cluster_name (master: $master_size, nodes: $master_size, zones: $zones)"

    check_env_var "KOPS_STATE_STORE" "Make sure you add \"export KOPS_STATE_STORE=s3://kube-om-state-store\" to your ~/.bashrc"

    echo "Make sure you use the latest version of kops (>= 1.14.0): 'brew upgrade kops'"
    kops create cluster \
         --node-count "$node_count" \
         --zones "${zones}" \
         --node-size "${node_size}" \
         --node-volume-size "${node_volume_size}" \
         --master-size="${master_size}" \
         --master-volume-size 16  \
         --kubernetes-version="${k8s_version}" \
         --ssh-public-key=~/.ssh/id_rsa.pub \
         --authorization RBAC "${cluster_name}"

    kops create secret --name "${cluster_name}" sshpublickey admin -i ~/.ssh/id_rsa.pub

    kops update cluster "${cluster_name}" --yes

    echo "Waiting until kops cluster gets ready..."
    kops validate cluster "${cluster_name}" --wait 10m

    title "Kops cluster ${cluster_name} is ready! Note, that you need to use 'admin' user if you want to ssh to the nodes"

    title "Adding support for Kubernetes dashboard"
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml

    title 'Kubernetes dashboard is installed, use "make dashboard" to open it'
}

# Makes sure the ECR repository exists.
# The incoming parameter is expected to be the full ECR url (e.g. "268558157000.dkr.ecr.us-east-1.amazonaws.com/alis/ubuntu/mongodb-enterprise-appdb")
ensure_ecr_repository() {
    local repo_url=$1
    local repo_name

    if [[ $(expr "${BASE_REPO_URL}" : '.*\.ecr\..*') -gt 0 ]]; then
        repo_name="$(echo "${repo_url}" | cut -d "/" -f2-)" # "alis/ubuntu/mongodb-enterprise-appdb"
        if ! aws ecr describe-repositories | grep "${repo_name}" > /dev/null; then
            echo "Creating repository ${repo_name} as it doesn't exist"
            aws ecr create-repository --repository-name="${repo_name}"
        fi
    fi
}
