//go:build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package mdbmulti

import (
	"github.com/10gen/ops-manager-kubernetes/api/v1/mdb"
	"github.com/10gen/ops-manager-kubernetes/api/v1/status"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatusItem) DeepCopyInto(out *ClusterStatusItem) {
	*out = *in
	in.Common.DeepCopyInto(&out.Common)
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make([]status.Warning, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatusItem.
func (in *ClusterStatusItem) DeepCopy() *ClusterStatusItem {
	if in == nil {
		return nil
	}
	out := new(ClusterStatusItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatusList) DeepCopyInto(out *ClusterStatusList) {
	*out = *in
	if in.ClusterStatuses != nil {
		in, out := &in.ClusterStatuses, &out.ClusterStatuses
		*out = make([]ClusterStatusItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatusList.
func (in *ClusterStatusList) DeepCopy() *ClusterStatusList {
	if in == nil {
		return nil
	}
	out := new(ClusterStatusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBMultiCluster) DeepCopyInto(out *MongoDBMultiCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBMultiCluster.
func (in *MongoDBMultiCluster) DeepCopy() *MongoDBMultiCluster {
	if in == nil {
		return nil
	}
	out := new(MongoDBMultiCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongoDBMultiCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBMultiClusterList) DeepCopyInto(out *MongoDBMultiClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MongoDBMultiCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBMultiClusterList.
func (in *MongoDBMultiClusterList) DeepCopy() *MongoDBMultiClusterList {
	if in == nil {
		return nil
	}
	out := new(MongoDBMultiClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongoDBMultiClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBMultiSpec) DeepCopyInto(out *MongoDBMultiSpec) {
	*out = *in
	in.DbCommonSpec.DeepCopyInto(&out.DbCommonSpec)
	if in.ClusterSpecList != nil {
		in, out := &in.ClusterSpecList, &out.ClusterSpecList
		*out = make(mdb.ClusterSpecList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Mapping != nil {
		in, out := &in.Mapping, &out.Mapping
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBMultiSpec.
func (in *MongoDBMultiSpec) DeepCopy() *MongoDBMultiSpec {
	if in == nil {
		return nil
	}
	out := new(MongoDBMultiSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBMultiStatus) DeepCopyInto(out *MongoDBMultiStatus) {
	*out = *in
	in.Common.DeepCopyInto(&out.Common)
	in.ClusterStatusList.DeepCopyInto(&out.ClusterStatusList)
	if in.BackupStatus != nil {
		in, out := &in.BackupStatus, &out.BackupStatus
		*out = new(mdb.BackupStatus)
		**out = **in
	}
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make([]status.Warning, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBMultiStatus.
func (in *MongoDBMultiStatus) DeepCopy() *MongoDBMultiStatus {
	if in == nil {
		return nil
	}
	out := new(MongoDBMultiStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiReplicaSetBuilder) DeepCopyInto(out *MultiReplicaSetBuilder) {
	*out = *in
	if in.MongoDBMultiCluster != nil {
		in, out := &in.MongoDBMultiCluster, &out.MongoDBMultiCluster
		*out = new(MongoDBMultiCluster)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiReplicaSetBuilder.
func (in *MultiReplicaSetBuilder) DeepCopy() *MultiReplicaSetBuilder {
	if in == nil {
		return nil
	}
	out := new(MultiReplicaSetBuilder)
	in.DeepCopyInto(out)
	return out
}
