#!/usr/bin/env bash

set -Eeou pipefail

CUSTOM_OM_PREV_VERSION=$(grep -E "^\s*-\s*&ops_manager_60_latest\s+(\S+)\s+#" <"${PROJECT_DIR}"/.evergreen.yml | awk '{print $3}')
export CUSTOM_OM_PREV_VERSION
CUSTOM_OM_VERSION=$(grep -E "^\s*-\s*&ops_manager_70_latest\s+(\S+)\s+#" <"${PROJECT_DIR}"/.evergreen.yml | awk '{print $3}')
export CUSTOM_OM_VERSION

export CUSTOM_MDB_VERSION=7.0.18
export CUSTOM_MDB_PREV_VERSION=6.0.21

export AGENT_VERSION=107.0.18.8784-1
export AGENT_IMAGE="${MDB_AGENT_IMAGE_REPOSITORY}:${AGENT_VERSION}"

export CUSTOM_APPDB_VERSION=7.0.18-ent
export TEST_MODE=opsmanager
export OPS_MANAGER_REGISTRY="${REGISTRY}"
