#!/usr/bin/env bash

set -Eeou pipefail

script_name=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "${script_name}")

export om_download_url="https://s3.amazonaws.com/mongodb-mms-build-onprem/c89c2e555fdfbcb80467ddfc6f7abbe01fb3fb25/mongodb-mms-7.0.0-rc10.500.20231214T2109Z.tar.gz"

om_version=$(grep -E "^\s*-\s*&ops_manager_70_latest\s+(\S+)\s+#" < "$script_dir"/../../../../.evergreen.yml | awk '{print $3}')
export om_version
