#!/usr/bin/env bash

set -Eeou pipefail

script_name=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "${script_name}")

om_version=$(grep -E "^\s*-\s*&ops_manager_80_latest\s+(\S+)\s+#" < "$script_dir"/../../../../.evergreen.yml | awk '{print $3}')
export om_version

# This URL override needs to be removed once we approach OM 8.0.0 GA
om_download_url="https://mongodb-mms-build-onprem.s3.amazonaws.com/4efad2cd2b3466350e237eb3a31212d8f75ef58e/mongodb-mms-8.0.0-rc1.500.20240827T1654Z.tar.gz"
export om_download_url
