# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/mongodb.com_mongodb.yaml
- bases/mongodb.com_mongodbusers.yaml
- bases/mongodb.com_opsmanagers.yaml
- bases/mongodb.com_mongodbmulticluster.yaml
- bases/mongodb.com_mongodbsearch.yaml
- bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
- bases/mongodb.com_clustermongodbroles.yaml
# +kubebuilder:scaffold:crdkustomizeresource

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
