# Member Cluster, cluster-scoped resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    multi-cluster: "true"
  name: mongodb-kubernetes-operator-multi-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  - services
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
  - deletecollection
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
  - deletecollection
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - create
  - update
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - delete
  - deletecollection
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
- apiGroups:
  - ""
  resourceNames:
  - kube-system
  resources:
  - namespaces
  verbs:
  - get
- nonResourceURLs:
  - /version
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    multi-cluster: "true"
  name: mongodb-kubernetes-operator-multi-cluster-role-telemetry
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
- apiGroups:
  - ""
  resourceNames:
  - kube-system
  resources:
  - namespaces
  verbs:
  - get
- nonResourceURLs:
  - /version
  verbs:
  - get

---
# Member Cluster, cluster-scoped resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    multi-cluster: "true"
  name: mongodb-kubernetes-operator-multi-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mongodb-kubernetes-operator-multi-cluster-role
subjects:
- kind: ServiceAccount
  name: mongodb-kubernetes-operator-multicluster
  namespace: central-namespace

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    multi-cluster: "true"
  name: mongodb-kubernetes-operator-multi-telemetry-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mongodb-kubernetes-operator-multi-cluster-role-telemetry
subjects:
- kind: ServiceAccount
  name: mongodb-kubernetes-operator-multicluster
  namespace: central-namespace

---
# Member Cluster, cluster-scoped resources
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    multi-cluster: "true"
  name: mongodb-kubernetes-appdb
  namespace: member-namespace

---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    multi-cluster: "true"
  name: mongodb-kubernetes-database-pods
  namespace: member-namespace

---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    multi-cluster: "true"
  name: mongodb-kubernetes-ops-manager
  namespace: member-namespace

---
