# Member Cluster, cluster-scoped resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    multi-cluster: "true"
  name: mongodb-kubernetes-operator-multi-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  - services
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
  - deletecollection
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
  - deletecollection
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - watch

---
# Member Cluster, cluster-scoped resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    multi-cluster: "true"
  name: mongodb-kubernetes-operator-multi-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mongodb-kubernetes-operator-multi-cluster-role
subjects:
- kind: ServiceAccount
  name: test-service-account
  namespace: member-namespace

---
# Member Cluster, cluster-scoped resources
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    multi-cluster: "true"
  name: mongodb-enterprise-appdb
  namespace: member-namespace

---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    multi-cluster: "true"
  name: mongodb-enterprise-database-pods
  namespace: member-namespace

---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    multi-cluster: "true"
  name: mongodb-enterprise-ops-manager
  namespace: member-namespace

---
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
- name: image-registries-secret
metadata:
  creationTimestamp: null
  labels:
    multi-cluster: "true"
  name: test-service-account
  namespace: member-namespace

---
