# Central Cluster, namespace-scoped resources
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    multi-cluster: "true"
  name: mongodb-kubernetes-operator-multi-role
  namespace: central-namespace
rules:
- apiGroups:
  - mongodb.com
  resources:
  - mongodbmulticluster
  - mongodbmulticluster/finalizers
  - mongodbmulticluster/status
  - mongodbusers
  - mongodbusers/status
  - opsmanagers
  - opsmanagers/finalizers
  - opsmanagers/status
  - mongodb
  - mongodb/finalizers
  - mongodb/status
  - mongodbsearch
  - mongodbsearch/finalizers
  - mongodbsearch/status
  verbs:
  - '*'
- apiGroups:
  - mongodbcommunity.mongodb.com
  resources:
  - mongodbcommunity
  - mongodbcommunity/status
  - mongodbcommunity/spec
  - mongodbcommunity/finalizers
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  - services
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
  - deletecollection
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
  - deletecollection
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - create
  - update
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - delete
  - deletecollection

---
# Central Cluster, namespace-scoped resources
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    multi-cluster: "true"
  name: mongodb-kubernetes-operator-multi-role-binding
  namespace: central-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mongodb-kubernetes-operator-multi-role
subjects:
- kind: ServiceAccount
  name: mongodb-kubernetes-operator-multicluster
  namespace: central-namespace

---
# Central Cluster, namespace-scoped resources
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    multi-cluster: "true"
  name: mongodb-kubernetes-operator-multicluster
  namespace: central-namespace

---
