apiVersion: v1
kind: ConfigMap
metadata:
  name: __OPS_MANAGER_CONFIGMAP__
  namespace: __NAMESPACE__
data:
  baseUrl: __OPS_MANAGER_BASE_URL__
  orgId: __OPS_MANAGER_ORG_ID__
  projectName: __OPS_MANAGER_PROJECT_NAME__
