apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: mc-no-mesh-selfsigned
  namespace: __NAMESPACE__
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mc-no-mesh-ca
  namespace: __NAMESPACE__
spec:
  secretName: mc-no-mesh-ca-key-pair
  commonName: mc-no-mesh-ca
  isCA: true
  duration: 8760h
  renewBefore: 720h
  usages:
    - cert sign
    - crl sign
  issuerRef:
    name: mc-no-mesh-selfsigned
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: mc-no-mesh-ca-issuer
  namespace: __NAMESPACE__
spec:
  ca:
    secretName: mc-no-mesh-ca-key-pair
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mc-no-mesh-mdb
  namespace: __NAMESPACE__
spec:
  secretName: mc-no-mesh-mdb-cert
  dnsNames:
    - "*.__CLUSTER0_DOMAIN__"
    - "*.__CLUSTER1_DOMAIN__"
  duration: 2160h
  renewBefore: 360h
  usages:
    - server auth
    - client auth
  issuerRef:
    name: mc-no-mesh-ca-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mc-no-mesh-mdb-agent
  namespace: __NAMESPACE__
spec:
  secretName: mc-no-mesh-mdb-agent-certs
  commonName: mms-automation-agent
  duration: 2160h
  renewBefore: 360h
  usages:
    - client auth
  issuerRef:
    name: mc-no-mesh-ca-issuer
    kind: Issuer
