export K8S_CLUSTER_0_CONTEXT_NAME="${CLUSTER_NAME}"

export PRIVATE_PREVIEW_IMAGE_PULLSECRET="${COMMUNITY_PRIVATE_PREVIEW_PULLSECRET_DOCKERCONFIGJSON}"

export OPERATOR_ADDITIONAL_HELM_VALUES=""
export OPERATOR_HELM_CHART="${PROJECT_DIR}/helm_chart"
