#!/usr/bin/env bash

source scripts/funcs/kubernetes

deploy_operator \
    "${REGISTRY}" \
    "${REVISION:-}" \
    "${PROJECT_NAMESPACE}" \
    "${WATCH_NAMESPACE:-$PROJECT_NAMESPACE}" \
    "Always" \
    "${MANAGED_SECURITY_CONTEXT:-}" \
    "2m"
