#!/usr/bin/env bash

start_time=$(date +%s)

# shellcheck disable=SC1091

if [[ -n "${KUBECONFIG}" && ! -f "${KUBECONFIG}" ]]; then
    echo "Kube configuration file does not exist!"
    exit 1
fi

set -uo pipefail
cd "$(git rev-parse --show-toplevel || echo "Failed to find git root"; exit 1)"

source scripts/funcs
source scripts/evergreen/e2e/dump_diagnostic_information

# Externally Configured Ops Manager (Cloud Manager)
test -f "${OPS_MANAGER_ENV:-}" && source "${OPS_MANAGER_ENV}"

timeout=$(get_timeout_for_task "${TASK_NAME}")

#
# This is the main entry point for running e2e tests. It can be used both for simple e2e tests (running a single test
# application) and for the Operator upgrade ones involving two steps (deploy previous Operator version, run test, deploy
# a new Operator - run verification tests)
# All the preparation work (fetching OM information, configuring resources) is done before running tests but
# it should be moved to e2e tests themselves (TODO)
#
check_env_var "TASK_NAME" "The 'TASK_NAME' must be specified for the Operator e2e tests"

# 1. Ensure the namespace exists - generate its name if not specified

if [[ -z "${PROJECT_NAMESPACE-}" ]]; then
    PROJECT_NAMESPACE=$(generate_random_namespace)
    export PROJECT_NAMESPACE

    echo "$PROJECT_NAMESPACE" > "${NAMESPACE_FILE}"
fi

ensure_namespace "${PROJECT_NAMESPACE}"

# 2. Fetch OM connection information - it will be saved to environment variables
# shellcheck disable=SC1091
. scripts/evergreen/e2e/fetch_om_information

# 3. Configure Operator resources
. scripts/evergreen/e2e/configure_operator

export TEST_NAME="${TASK_NAME}"
delete_operator "${PROJECT_NAMESPACE}"

# 4. (optionally) Preliminary step in the case of Operator upgrade
if echo "${TASK_NAME}" | egrep -q "^e2e_op_upgrade"; then
    export TEST_NAME="${TASK_NAME}_first"
    header "Performing the first stage (${TEST_NAME}) of an Operator upgrade test"

    # If the version of the Operator to upgrade from not specified then we assume it's the latest
    export REVISION="${OPERATOR_VERSION_UPGRADE_FROM:-"latest"}"

    # TODO add support for quay.io UBI images as well
    REGISTRY="quay.io/mongodb" ./scripts/evergreen/e2e/deploy_operator
    if ! ./scripts/evergreen/e2e/single_e2e; then
        dump_all
        scripts/evergreen/e2e/teardown
        exit 1
    fi
    # Setting the second test to be run after the Operator upgrade after 'if' block
    # Note, that in this case the second Operator will be upgraded, not deleted-created
    export TEST_NAME="${TASK_NAME}_second"
    header "Performing the second stage (${TEST_NAME})"
fi

# 5. Main test run. In case of Operator upgrade this will be the second test run and
# the Operator won't be removed - only upgraded
export REVISION="${OPERATOR_VERSION}"

if ! scripts/evergreen/e2e/deploy_operator; then
    echo "Operator failed to start"
    exit 1
fi


# We'll have the task running for the allocated time, minus the time it took us
# to get all the way here, assuming configuring and deploying the operator can
# take a bit of time. This is needed because Evergreen kills the process *AND*
# Docker containers running on the host when it hits a timeout. Under these
# circumstances and in Kind based environments, it is impossible to fetch the
# results from the Kubernetes cluster running on top of Docker.
#
current_time=$(date +%s)
elapsed_time=$((current_time - start_time))
timeout=$((timeout - elapsed_time - 60))
echo "This task is allowed to run for ${timeout} seconds"
timeout --foreground "${timeout}" scripts/evergreen/e2e/single_e2e
TEST_RESULTS=$?

# Dump all the information we can from this namespace
dump_all

if [[ "${TEST_RESULTS}" -ne 0 ]]; then
    # Mark namespace as failed to be cleaned later
    kubectl label "namespace/${PROJECT_NAMESPACE}" "evg/state=failed" --overwrite=true

    if [ "${always_remove_testing_namespace-}" = "true" ]; then
        # Failed namespaces might cascade into more failures if the namespaces
        # are not being removed soon enough.
        scripts/evergreen/e2e/teardown
    fi
else
    # If the test pass, then the namespace is removed
    scripts/evergreen/e2e/teardown
fi

# We exit with the test result to surface status to Evergreen.
exit $TEST_RESULTS
