#!/usr/bin/env bash

[[ "${MODE-}" = "dev" ]] && exit 0

echo "Removing all CRs and the test namespace ${PROJECT_NAMESPACE}"
kubectl delete mdb --all -n "${PROJECT_NAMESPACE}" || true
kubectl delete mdbu --all -n "${PROJECT_NAMESPACE}" || true
kubectl delete om --all -n "${PROJECT_NAMESPACE}" || true
kubectl delete "namespace/${PROJECT_NAMESPACE}" --wait=false || true

echo "Removing CSRs"
kubectl delete "$(kubectl get csr -o name | grep "${PROJECT_NAMESPACE}")" &> /dev/null || true
