#!/usr/bin/env bash

set -Eeou pipefail

# script checks if kubectl has the matching contexts - if not - then tries to create Kube cluster


source scripts/dev/read_context.sh
source scripts/funcs/printing

if [[ -n "${MONGODB_RESOURCES-}" ]]; then
	title "Creating the following resources: \"${MONGODB_RESOURCES}\""

	for f in ${MONGODB_RESOURCES}; do
		kubectl apply -f "${f}"
	done
fi
