#!/bin/bash
# Build all images needed for Monarch testing with :monarch tag
#
# Usage: ./build-monarch-images.sh [--agent-path=PATH] [--om-path=PATH]
#
# Builds agent and ops-manager from source by default using:
#   ~/projects/mms-automation
#   ~/projects/ops-manager
#
# Monarch-injector uses the released binary (local builds not supported).
#
# Images pushed to staging ECR with :monarch tag:
#   - mongodb-agent:monarch
#   - mongodb-enterprise-ops-manager-ubi:monarch
#   - mongodb-kubernetes-monarch-injector:monarch

set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"

AGENT_PATH=""
OM_PATH=""
PLATFORM="${DOCKER_PLATFORM:-linux/amd64}"

while [[ $# -gt 0 ]]; do
    case $1 in
        --agent-path=*) AGENT_PATH="${1#*=}"; shift ;;
        --om-path=*) OM_PATH="${1#*=}"; shift ;;
        --platform=*) PLATFORM="${1#*=}"; shift ;;
        -h|--help)
            head -17 "$0" | tail -n +2 | sed 's/^# //' | sed 's/^#//'
            exit 0
            ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

cd "${PROJECT_DIR}"

echo "============================================"
echo "Building Monarch test images"
echo "============================================"
echo "Platform: ${PLATFORM}"
echo "Tag: monarch"
echo "============================================"
echo ""

# Build agent
echo ">>> Building agent:monarch"
if [[ -n "$AGENT_PATH" ]]; then
    python scripts/release/pipeline.py agent -b staging --agent-path="$AGENT_PATH" --version monarch -p "$PLATFORM"
else
    python scripts/release/pipeline.py agent -b staging --agent-path --version monarch -p "$PLATFORM"
fi

echo ""
echo ">>> Building ops-manager:monarch"
if [[ -n "$OM_PATH" ]]; then
    python scripts/release/pipeline.py ops-manager -b staging --om-path="$OM_PATH" --version monarch -p "$PLATFORM"
else
    python scripts/release/pipeline.py ops-manager -b staging --om-path --version monarch -p "$PLATFORM"
fi

echo ""
echo ">>> Building monarch-injector:monarch"
python scripts/release/pipeline.py monarch-injector -b staging --version monarch -p "$PLATFORM"

echo ""
echo "============================================"
echo "Done! Images pushed to staging ECR:"
echo "  - mongodb-agent:monarch"
echo "  - mongodb-enterprise-ops-manager-ubi:monarch"
echo "  - mongodb-kubernetes-monarch-injector:monarch"
echo ""
echo "To use these images, switch context with monarch override:"
echo "  make switch context=e2e_static_om80_kind_ubi additional_override=private-context-monarch"
echo "============================================"

# Create context override file (must be named private-context-* for switch_context.sh)
OVERRIDE_FILE="${PROJECT_DIR}/scripts/dev/contexts/private-context-monarch"
cat > "${OVERRIDE_FILE}" << 'EOF'
# Monarch testing image overrides
# Generated by scripts/dev/build-monarch-images.sh
_MONARCH_ECR="268558157000.dkr.ecr.us-east-1.amazonaws.com/staging"
export MDB_AGENT_IMAGE="${_MONARCH_ECR}/mongodb-agent:monarch"
export MDB_OM_IMAGE="${_MONARCH_ECR}/mongodb-enterprise-ops-manager-ubi:monarch"
export MDB_MONARCH_IMAGE="${_MONARCH_ECR}/mongodb-kubernetes-monarch-injector:monarch"
EOF
echo "Created context override: scripts/dev/contexts/private-context-monarch"

echo ""
echo "Switching context..."
make -C "${PROJECT_DIR}" switch context=e2e_static_om80_kind_ubi additional_override=private-context-monarch
