#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel || echo "Failed to find git root"; exit 1)"

source scripts/dev/set_env_context

title "Building Database image..."

if [[ ${REPO_TYPE} = "ecr" ]]; then
    ensure_ecr_repository "${REPO_URL}/mongodb-enterprise-database"
fi

repo_host="$(echo ${REPO_URL} | cut -d "/" -f 1)"
repo_name="$(echo ${REPO_URL} | cut -d "/" -f 2)"

make -C docker/mongodb-enterprise-database push IMAGE_DIR="${repo_name}" AWS_IMAGE_REPO="${repo_host}" IMAGE_TYPE="${IMAGE_TYPE}"

title "Database image successfully built and pushed to ${REPO_TYPE} registry"
