#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel || echo "Failed to find git root"; exit 1)"

source scripts/dev/read_context

title "Building Database image..."

if [[ ${REPO_TYPE} = "local" ]]; then
	eval "$(minikube docker-env)"
	make -C docker/mongodb-enterprise-database build IMAGE_DIR=local
	title "Database image successfully built"
elif [[ ${REPO_TYPE} = "ecr" ]]; then
	eval "$(aws ecr get-login --no-include-email --region us-east-1)" &> /dev/null

	repo_name="$(echo ${REPO_URL} | cut -d "/" -f 2)"

	if ! aws ecr describe-repositories | grep -q "${repo_name}/mongodb-enterprise-database"; then
		aws ecr create-repository --repository-name="${repo_name}/mongodb-enterprise-database"
	fi

	make -C docker/mongodb-enterprise-database build IMAGE_DIR="${repo_name}"
	docker tag "${repo_name}"/mongodb-enterprise-database "${REPO_URL}"/mongodb-enterprise-database
	docker push "${REPO_URL}"/mongodb-enterprise-database

	title "Database image successfully built and pushed to the ECR registry"
elif [[ ${REPO_TYPE} = "quay" ]]; then
	title "Skipping build of the database as current Docker registry is quay.io"
fi
