#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel || echo "Failed to find git root"; exit 1)"

source scripts/dev/set_env_context

# Script builds and optionally pushes the test image
# Note, that unlike corresponding scripts for operator/database it adds the tag to the image - this is because our
# e2e procedure in Evergreen uses the same repo and git SHA is the only way to isolate different images - we just use the
# same approach

title "Building e2e tests application image..."

TEST_IMAGE_TAG=$(git rev-parse HEAD)

if [[ ${REPO_TYPE} = "ecr" ]]; then
    # note that 'aws login' should be called before - 'make' takes care of it
    ensure_ecr_repository "${REPO_URL}/mongodb-enterprise-tests"
fi

image="${REPO_URL}/mongodb-enterprise-tests:${TEST_IMAGE_TAG}"
docker build docker/mongodb-enterprise-tests -t "${image}"
docker push "${image}"

title "Enterprise tests successfully built and pushed to ${REPO_TYPE} registry"
