#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel || echo "Failed to find git root"; exit 1)"

source scripts/dev/set_env_context

title "Building Operator image..."

if [[ ${REPO_TYPE} = "local" ]]; then
	eval "$(minikube docker-env)"
	make -C docker/mongodb-enterprise-operator build IMAGE_DIR=local || scripts/build/prepare_build_environment && make -C docker/mongodb-enterprise-operator build IMAGE_DIR=local
	title "Operator image successfully built"
elif [[ ${REPO_TYPE} = "ecr" ]]; then
	repo_name="$(echo ${REPO_URL} | cut -d "/" -f 2)"

	if ! aws ecr describe-repositories | grep -q "${repo_name}/mongodb-enterprise-operator"; then
		aws ecr create-repository --repository-name="${repo_name}/mongodb-enterprise-operator"
	fi

	make -C docker/mongodb-enterprise-operator build IMAGE_DIR="${repo_name}" || scripts/build/prepare_build_environment && make -C docker/mongodb-enterprise-operator build IMAGE_DIR="${repo_name}"
	docker tag "${repo_name}"/mongodb-enterprise-operator "${REPO_URL}"/mongodb-enterprise-operator
	docker push "${REPO_URL}"/mongodb-enterprise-operator

	title "Operator image successfully built and pushed to the ECR registry"
elif [[ ${REPO_TYPE} = "quay" ]]; then
	title "Skipping build of the Operator as current Docker registry is quay.io"
fi

