#!/usr/bin/env bash

ecr_registry=${1}
# First we need to create proper "auths" entry for our ECR registry,
# using docker-credential-ecr-login (which is faster to install than Python + aws-cli).
secret=$(echo "${ecr_registry}" | docker-credential-ecr-login get | jq -r .Secret)
auth=$(echo "AWS:${secret}" | base64 -w0)

echo '{"auths":{"'${ecr_registry}'":{"auth":"'${auth}'"}}}'
