#!/usr/bin/env bash

set -euo pipefail

cd "$(git rev-parse --show-toplevel || echo "Failed to find git root"; exit 1)"

source scripts/dev/set_env_context

DEBUG="${1-}"

title "Deploying the Operator to Kubernetes cluster..."

# checking the status of k8s cluster
if [[ ${CLUSTER_TYPE} = "minikube" ]]; then
    ensure_minikube
elif [[ ${CLUSTER_TYPE} = "kops" ]]; then
    if kops validate cluster "${CLUSTER_NAME}" | grep -q "not found"; then
        fatal "kops cluster is not running, call \"make\" to create it"
    fi
elif [[ ${CLUSTER_TYPE} = "openshift" ]]; then
    if ! oc get nodes &> /dev/null; then
        fatal "Could not communicate to Openshift cluster"
    fi
else
    fatal "CLUSTER_TYPE=${CLUSTER_TYPE} not recognized"
fi

# making sure the namespace is created
ensure_namespace "${NAMESPACE}"

#installing the operator
if [[ ${REPO_TYPE} = "local" ]]; then
    pull_policy="Never"
fi

if [[ ${CLUSTER_TYPE} = "openshift" ]]; then
    managed_security_context=true
fi
redeploy_operator "${REPO_URL}" "${OPERATOR_VERSION:-latest}-${IMAGE_TYPE}" "${NAMESPACE:-mongodb}" "${watch_namespace:-$NAMESPACE}" "${pull_policy:-}" "${managed_security_context:-}"
