#!/usr/bin/env bash

set -euo pipefail

# script checks if kubectl has the matching contexts - if not - then tries to create Kube cluster

cd "$(git rev-parse --show-toplevel || echo "Failed to find git root"; exit 1)"

source scripts/dev/read_context
source scripts/evergreen/setup_kind

title "Ensuring Kubernetes cluster is up..."

if [[ ${CLUSTER_TYPE} = "minikube" ]]; then
	check_app "minikube" "minikube is not installed!"
elif [[ ${CLUSTER_TYPE} = "kops" ]]; then
	check_app "kops" "kops is not installed!"
elif [[ ${CLUSTER_TYPE} = "kind" ]]; then
	check_app "kind" "kind is not installed!"
fi

if [[ ${CLUSTER_TYPE} = "minikube" ]]; then
	ensure_minikube
elif [[ ${CLUSTER_TYPE} = "kops" ]] && ! kops validate cluster "${CLUSTER_NAME}" ; then
	check_app "timeout" "coreutils is not installed, call \"brew install coreutils\""

	echo "Kops cluster \"${CLUSTER_NAME}\" doesn't exist"

	create_kops_cluster ${CLUSTER_NAME} 3 16 "t2.large" "t2.small" "${KOPS_ZONES:-us-east-2a,us-east-2b,us-east-2c}"

elif [[ ${CLUSTER_TYPE} = "openshift" ]]; then
	echo "openshift is TODO"
elif [[ ${CLUSTER_TYPE} = "kind" ]]; then
  echo "deleting existing kind cluster"
  kind delete cluster
  echo "creating kind cluster"

  ecr_registry="268558157000.dkr.ecr.us-east-1.amazonaws.com"
  setup_kind "${ecr_registry}"
  kind create cluster --config $HOME/.operator-dev/kind-ecr-config.yaml
fi

title "Kubernetes cluster \"${CLUSTER_NAME}\" is up"
