#!/usr/bin/env bash

set -euo pipefail

# script starts OM in Evergreen if it's not started already and dumps its information (api_keys etc) into ~/.operator-dev
# directory for# later usage


cd "$(git rev-parse --show-toplevel || echo "Failed to find git root"; exit 1)"

source scripts/funcs

# start ops manager
ensure_ops_manager_evg

# overwrite the connectivity data for current context
mkdir -p ~/.operator-dev

if ! ssh "ubuntu@${OPS_MANAGER_HOST}" cat "~/om" &> /dev/null; then
	# generate environment data on the first run
	echo "Configuring host ${OPS_MANAGER_HOST}"
	rm ~/.operator-dev/om || true

	# todo the script just creates a user - we need to create a test organization as well
	docker/mongodb-enterprise-ops-manager/scripts/configure-ops-manager.py \
		"http://${OPS_MANAGER_HOST}:9080" ~/.operator-dev/om

	echo "Ops Manager Environment:"
	cat ~/.operator-dev/om

	scp ~/.operator-dev/om "ubuntu@${OPS_MANAGER_HOST}:om"
else
	echo "There is already env file on ${OPS_MANAGER_HOST} - reusing it"
fi

# copying the env data back to the local context to overwrite previous one
scp "ubuntu@${OPS_MANAGER_HOST}:om" ~/.operator-dev/om
chmod +x ~/.operator-dev/om

eval "$(cat ~/.operator-dev/om)"
