#!/usr/bin/env bash

set -euo pipefail

# script starts OM in Kubernetes if it's not started already and dumps its information (api_keys etc) into ~/.operator-dev
# directory for# later usage

cd "$(git rev-parse --show-toplevel || echo "Failed to find git root"; exit 1)"

source scripts/dev/read_context
# ensure Ops Manager is started in Kubernetes
ensure_ops_manager_k8s ${1} ${2} ${3}

# overwrite the connectivity data for current context
mkdir -p ~/.operator-dev
kubectl -n ${1} exec mongodb-enterprise-ops-manager-0 cat /opt/mongodb/mms/env/.ops-manager-env > ~/.operator-dev/om
chmod +x ~/.operator-dev/om

eval "$(cat ~/.operator-dev/om)"


