#!/usr/bin/env bash

set -euo pipefail

cd "$(git rev-parse --show-toplevel || echo "Failed to find git root"; exit 1)"

source scripts/funcs

title "The following tools will be installed: kubectl, minikube, kops, aws-cli"
echo "Note, that you must download 'go' and 'dep' by yourself"

# dep
brew install dep

# kubectl 1.11.3
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/41764e07727d9a86b0f8a077117dc7876ca294c4/Formula/kubernetes-cli.rb

# minikube
brew cask install minikube

# kops
brew install kops
echo "Make sure you add \"export KOPS_STATE_STORE=s3://kube-om-state-store\" to your ~/.bashrc"

# aws-cli
brew install awscli
aws configure

# helm
brew install kubernetes-helm

echo "Adding git commit hooks"
ln -s -f ../../scripts/dev/commit_hooks/pre-commit .git/hooks/pre-commit

title "Tools are installed"
