#!/usr/bin/env bash

set -Eeou pipefail

cd "$(git rev-parse --show-toplevel)"

# The script launches e2e test. Note, that the Operator and necessary resources are deployed
# inside the test

# shellcheck source=scripts/dev/set_env_context.sh
source scripts/dev/set_env_context.sh
# shellcheck source=scripts/funcs/printing
source scripts/funcs/printing


# This will allow to reuse the current namespace - it already has Operator installed
export PROJECT_NAMESPACE=${NAMESPACE}
export OM_BASE_URL=${OM_HOST}

# shellcheck disable=SC2154
title "Running the e2e test ${test}..."

if [[ ${CLUSTER_TYPE} = "openshift" ]]; then
    managed_security_context=true
fi

[[ ${skip:-} = "true" ]] && export SKIP_EXECUTION="'true'"

if [[ -n "${local:-}" ]]; then
    pytest -m "${test}" docker/mongodb-enterprise-tests --disable-pytest-warnings
else
    TASK_NAME=${test} \
    WAIT_TIMEOUT="4m" \
    MODE="dev" \
    WATCH_NAMESPACE=${watch_namespace:-$PROJECT_NAMESPACE} \
    MANAGED_SECURITY_CONTEXT=${managed_security_context:-} \
    REGISTRY=${REPO_URL} \
    DEBUG=${debug-} \
    ./scripts/evergreen/e2e/e2e.sh
fi

title "E2e test ${test} is finished"


