#!/usr/bin/env bash

set -euo pipefail

cd "$(git rev-parse --show-toplevel || echo "Failed to find git root"; exit 1)"

# The script launches e2e test. Note, that the Operator and necessary resources are deployed
# inside the test

source scripts/dev/set_env_context


# This will allow to reuse the current namespace - it already has Operator installed
export PROJECT_NAMESPACE=${NAMESPACE}
export OM_BASE_URL=${OM_HOST}

title "Running the e2e test ${test}..."

if [[ ${CLUSTER_TYPE} = "openshift" ]]; then
    managed_security_context=true
fi

[[ ${skip:-} = "true" ]] && export SKIP_EXECUTION="'true'"

if [[ -n "${local:-}" ]]; then
    pytest -m ${test} docker/mongodb-enterprise-tests --disable-pytest-warnings
else
    TASK_NAME=${test} \
    WAIT_TIMEOUT="4m" \
    MODE="dev" \
    WATCH_NAMESPACE=${watch_namespace:-$PROJECT_NAMESPACE} \
    MANAGED_SECURITY_CONTEXT=${managed_security_context:-} \
    REGISTRY=${REPO_URL} \
    ./scripts/evergreen/e2e/e2e
fi

title "E2e test ${test} is finished"


