#!/usr/bin/env bash

set -euo pipefail

cd "$(git rev-parse --show-toplevel || echo "Failed to find git root"; exit 1)"

# The script launches e2e test. Note, that it doesn't build the full environment, only runs tests on the existing one
# So the Operator, config maps etc must already exist

source scripts/dev/read_context
source ${OPERATOR_DIR}/om

# This will allow to reuse the current namespace - it already has Operator installed
export PROJECT_NAMESPACE=${NAMESPACE}
export OM_BASE_URL=${OM_HOST}

title "Running the e2e test ${test}..."

if [[ ${CLUSTER_TYPE} = "openshift" ]]; then
    managed_security_context=true
fi

if [[ -n "${local:-}" ]]; then
    pytest -m ${test} docker/mongodb-enterprise-tests --disable-pytest-warnings
else
    TASK_NAME=${test} WAIT_TIMEOUT="4m" MODE="dev" WATCH_NAMESPACE=${watch_namespace:-$PROJECT_NAMESPACE} MANAGED_SECURITY_CONTEXT=${managed_security_context:-} ./scripts/evergreen/e2e_tests.sh
fi

title "E2e test ${test} is finished"


