#!/usr/bin/env bash
set -Eeou pipefail

source scripts/funcs/errors

if [[ ! -d $HOME/.operator-dev/contexts ]]; then
	fatal "Contexts directory \"~/.operator-dev/contexts\" not found! You must init development environment using \"make init\" first"
fi

for f in "$HOME"/.operator-dev/contexts/*; do
	echo "----------"
	basename "$f"
	echo "----------"
	grep -v "^# " "$f"
	echo
done
