#!/usr/bin/env bash

set -euo pipefail

cd "$(git rev-parse --show-toplevel || echo "Failed to find git root"; exit 1)"

source scripts/funcs/errors

if [[ ! -d $HOME/.operator-dev/contexts ]]; then
    fatal "Contexts directory \"~/.operator-dev/contexts\" not found! You must init development environment using \"make init\" first"
fi

for f in $HOME/.operator-dev/contexts/*; do
	echo "----------"
	echo $(basename "$f")
	echo "----------"
	cat $f | grep -v "^# "
	echo
done
