#!/usr/bin/env bash

set -euo pipefail

source scripts/funcs

recreate="${1-}"

if [[ "${recreate}" != "yes" ]]; then
	fatal "Exiting as \"imsure=yes\" parameter is not specified"
fi

# make sure kops version is >= 1.11.0
if ! kops version | grep -q "1.11.0"; then
	fatal "kops must be of version 1.11.0!"
fi

CLUSTER=e2e.mongokubernetes.com

title "Deleting kops cluster $CLUSTER"

# wait until the cluster is removed (could be removed already)
kops delete cluster $CLUSTER --yes || true

title "Cluster deleted"

# Note, that for e2e cluster we use us-east-2 region as us-east-1 most of all has reached max number of VPCs (5)
create_kops_cluster ${CLUSTER} 3 32 "t2.xlarge" "t2.medium" "us-east-2a,us-east-2b,us-east-2c"

