#!/usr/bin/env bash

set -Eeou pipefail

# This is a temporary script for manual releasing of OM and appdb images
# Don't forget to authenticate in quay first

cd docker/mongodb-enterprise-ops-manager

# OM 4.2.0
docker build -t mongodb-enterprise-ops-manager:4.2.0 --build-arg OM_DOWNLOAD_LINK=https://downloads.mongodb.com/on-prem-mms/tar/mongodb-mms-4.2.0.56551.20190812T1752Z-1.x86_64.tar.gz .
docker tag mongodb-enterprise-ops-manager:4.2.0 quay.io/mongodb/mongodb-enterprise-ops-manager:4.2.0
docker push quay.io/mongodb/mongodb-enterprise-ops-manager:4.2.0

# OM 4.2.3
docker build -t mongodb-enterprise-ops-manager:4.2.3 --build-arg OM_DOWNLOAD_LINK=https://downloads.mongodb.com/on-prem-mms/tar/mongodb-mms-4.2.3.56677.20191010T1408Z-1.x86_64.tar.gz .
docker tag mongodb-enterprise-ops-manager:4.2.3 quay.io/mongodb/mongodb-enterprise-ops-manager:4.2.3
docker push quay.io/mongodb/mongodb-enterprise-ops-manager:4.2.3

cd ../mongodb-enterprise-database

# AppDB 4.2.0
docker build -t mongodb-enterprise-appdb:4.2.0 \
		--build-arg AA_DOWNLOAD_LOCATION=https://s3.amazonaws.com/mciuploads/mms-automation/mongodb-mms-build-agent/builds/automation-agent/prod \
		--build-arg AA_VERSION=10.2.5.5871-1 .
docker tag mongodb-enterprise-appdb:4.2.0 quay.io/mongodb/mongodb-enterprise-appdb:4.2.0
docker push quay.io/mongodb/mongodb-enterprise-appdb:4.2.0

# AppDB 4.2.3
docker build -t mongodb-enterprise-appdb:4.2.3 \
		--build-arg AA_DOWNLOAD_LOCATION=https://s3.amazonaws.com/mciuploads/mms-automation/mongodb-mms-build-agent/builds/automation-agent/prod \
		--build-arg AA_VERSION=10.2.8.5901-1 .
docker tag mongodb-enterprise-appdb:4.2.3 quay.io/mongodb/mongodb-enterprise-appdb:4.2.3
docker push quay.io/mongodb/mongodb-enterprise-appdb:4.2.3



# TODO parse release.json using jq
#for row in $(cat release.json | jq -c '.opsManagerImages[]|.'); do
#   echo ${row}
#   release=$(echo ${row} | jq -r ${1})
#   download=$(echo ${row} | jq -r ${2})
#
#   echo "$release -> $download"
#done

