#!/usr/bin/env bash

set -euo pipefail

ONLY_MDB="${1-}"

cd "$(git rev-parse --show-toplevel || echo "Failed to find git root"; exit 1)"

source scripts/dev/set_env_context

# Cleans the namespace. Note, that fine-grained cleanup is performed instead of just deleting the namespace as it takes
# considerably less time

title "Cleaning Kubernetes resources ${ONLY_MDB:+(only MongoDB resources)}"

ensure_namespace "${NAMESPACE}"

kubectl delete mdb --all -n "${NAMESPACE}" || true
kubectl delete mdbu --all -n "${NAMESPACE}" || true

kubectl delete $(kubectl get csr -o name | grep ${NAMESPACE}) || true

if [[ -z $ONLY_MDB ]]; then
  kubectl delete secrets --all -n "${NAMESPACE}"
  kubectl delete configmaps --all -n "${NAMESPACE}"
  kubectl delete pvc --all -n "${NAMESPACE}"
fi
