#!/usr/bin/env bash

set -euo pipefail

# script prepares environment variables relevant for the current context
# TODO add the context overriding via parameter

cd "$(git rev-parse --show-toplevel || echo "Failed to find git root"; exit 1)"

source scripts/funcs

mkdir -p ~/.operator-dev

context="$1"

if [[ ! -f ~/.operator-dev/contexts/${context} ]]; then
	fatal "Cannot switch context: there is no configuration ${context} in \"~/.operator-dev/contexts/\""
fi

echo ${context} > ~/.operator-dev/current

# Reading environment variables for the context - this is where we get "CLUSTER_NAME" var from
source scripts/dev/read_context

echo "Switched operator context to \"${context}"\"

