{% extends "Dockerfile.ubi" %}


{% block packages %}
RUN yum install --disableplugin=subscription-manager \
  cyrus-sasl \
  cyrus-sasl-gssapi \
  cyrus-sasl-plain \
  krb5-libs \
  libcurl \
  libpcap \
  lm_sensors-libs \
  net-snmp \
  net-snmp-agent-libs \
  openldap \
  openssl \
  rpm-libs \
  net-tools \
  procps-ng \
  ncurses
{% endblock %}

{% block healthcheck %}
HEALTHCHECK --timeout=30s CMD ls /mongodb-ops-manager/bin/mongodb-mms || exit 1
{% endblock %}
